### ISSUE TITLE
Long Dropown Lists with Scrollbar?

### ISSUE THREAD

**Issue by Calaelen** [davidstutz/bootstrap-multiselect#1]
Hi,

I have a multiselect box with 30+ options which opens the dropdown all over the screen (and above).

Is it possible to define a max height or something similar to create a scrollbar inside the dropdown list?

**Comment by M-Shahbaz** [comment]
@egeback Thank you, it works

**Comment by sangar82** [comment]
This is issue is not solved. @egeback solution solves the issue, but is not added in the master branch!

I would add a new feature to this: scroll up the scrollbar when open the option dropdown

**Comment by Santiago-ae** [comment]
Thanks! @egeback

**Comment by zad9999** [comment]
Big Thanks @egeback

**Comment by t2pdev02** [comment]
Greate Thanks @egeback.. 👍 :)

**Comment by WaldoRR** [comment]
it really works, great!
