### ISSUE TITLE
Multiselect boxes have disappeared completely

### ISSUE THREAD

**Issue by rciconte** [davidstutz/bootstrap-multiselect#1013]
Ok so I've been using the multiselect for a while now but I have run into an issue I cannot figure out, I must have changed something but cannot figure out what I changed.

**Here's the problem: The drop down for the multiselect does not appear when on clicks on it. The whole selection is grey and doesn't look active at all.**

So the drop down multiselect boxes do not display anymore for my drop downs. They just display as greyed out dop downs and when on clicks on them nothing happens. I 've rebuilt them entirely from scratch a few times since they have broken with no success... I think I changed something in the CSS that has caused this but am not sure. It doesnt produce an javascript errors... In fact I have absolutely no errors on the page at all. 

Can someone please give me a place to look or start looking (as I have been through everything I can think of)... Unfortunently it is a internal site and I have nowhere to post this page elsewhere.

PLEASE HELP.

~Robert

**Comment by mohe2015** [comment]
Can you provide excerpts of the JavaScript and CSS?

**Comment by rciconte** [comment]
Absolutely... Iv've set up a test page with the multiselects on it so you can see everything that's going on.

http://www.ciconte.com/CTMS/filter_test.cfm

Thank you for your help =)

**Comment by rciconte** [comment]
I set up athe site so you could see the problem here:

http://www.ciconte.com/CTMS/filter_test.cfm

Thank you for you help with this.

~Robert

**Comment by mohe2015** [comment]
@rciconte I think you need to use bootstrap 4(1.1) instead of bootstrap 3, see http://www.ciconte.com/assets/js/bootstrap.min.js

**Comment by rciconte** [comment]
I tries switch to 4.1.1 but it didn't change anything.

~Robert

**Comment by mohe2015** [comment]
@rciconte As you can see in the web console if you click on one of the dropdowns, you also need to include popper.js in your page: `TypeError: Bootstrap dropdown require Popper.js (https://popper.js.org)`. You can do this using: `<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>`

**Comment by mohe2015** [comment]
@rciconte Your jquery version is also very outdated. Use the versions from https://getbootstrap.com/docs/4.1/getting-started/introduction/

**Comment by rciconte** [comment]
ok  I've upgrade to using popper and upgrade my jquery... still no change.


~Robert

**Comment by rciconte** [comment]
Is there something I changed in the CSS that could be causing this?

~Robert

**Comment by rciconte** [comment]
yes it totally does work... thank you so much

~Robert

**Comment by mohe2015** [comment]
You are welcome. You may close the issue.

**Comment by rciconte** [comment]
Thank you for helping me fix this issue

**Comment by markusd1984** [comment]
> @rciconte I think you need to use bootstrap 4(1.1) instead of bootstrap 3, see header in http://www.ciconte.com/assets/js/bootstrap.min.js
> 
> EDIT: you also need popper.js:
> 
> ```
> <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
> <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
> ```

Surprised this isn't mentioned in the guide for getting started. =)
