### ISSUE TITLE
On blur not working

### ISSUE THREAD

**Issue by akashmulik** [davidstutz/bootstrap-multiselect#1020]
I want to apply on blur on multi select plugin

**Comment by kaushal41** [comment]
$("#Dropdown").multiselect({
                               onDropdownHide:function () {
                //Write your code here
                }
            });

**Comment by akashmulik** [comment]
thanks.. but it doesn't work.

**Comment by kaushal41** [comment]
Can you share the code which you wrote while trying the above solution?
