### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by Routhgen** [davidstutz/bootstrap-multiselect#1043]
Its so shitty done. Even that small feature with bootstrap & jqeury loaded + non minimized (stupid done) bootstrap-multiselect.js + css
It return in:
bootstrap-multiselect.js:1748 Uncaught TypeError: Cannot read property 'fn' of undefined
    at bootstrap-multiselect.js:1748
    at bootstrap-multiselect.js:53
    at bootstrap-multiselect.js:55

Watse of time... shitty product

**Comment by jasonperrone** [comment]
I just want to say this widget is gorgeous. Respect.

**Comment by rochefort** [comment]
I'm facing the same problem.
https://github.com/davidstutz/bootstrap-multiselect/issues/1092
