### ISSUE TITLE
Mobile Browser Events

### ISSUE THREAD

**Issue by HankG** [davidstutz/bootstrap-multiselect#1068]
Should the onChange, onDropdownHide, or other events be fired and intercepted by the code in Mobile?  I was testing on the desktop and everything was running great but when I started testing on Android and iOS the control being shown is a native control not an HTML one and it seems like the events aren't firing and/or not being intercepted (I'm assuming the former).  Is there a setting to force it to render as an HTML control or is it possible something else has gone wrong with the loading?  The actual multi-select behavior seems to be working from what I can tell but I need to do some logic in onChange or onDropdownHide to get it going correctly.

**Comment by HankG** [comment]
This may be a site build problem that's not loading the JS file...closing for now...

**Comment by rsavinsky** [comment]
I notice that this issue has been closed, but I'm having the same issue accept it only happens on a post request on a mobile device. When the page is first loaded everything is fine, but when it loads after the form post the native control is displayed. If I refresh the page again the HTML control is displayed. I have verified that the JS file is being loaded.
