### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by echan00** [davidstutz/bootstrap-multiselect#1092]
I'm having trouble initializing bootstrap-multiselect. I am using NPM, webpack and have made sure bootstrap-multiselect is loaded after jquery and bootstrap:

```
import $ from 'jquery';
window.jQuery = $;
window.$ = $;

import Rails from 'rails-ujs';
import Turbolinks from 'turbolinks';
Rails.start();
Turbolinks.start();

import 'bootstrap/dist/js/bootstrap';
import 'bootstrap-multiselect/dist/js/bootstrap-multiselect';
```

Would anyone have any thoughts?

**Comment by echan00** [comment]
Sorry, not a problem relating to this library

**Comment by pgiraud** [comment]
@echan00 Can you please tell us how you solve the issue? Did you add something to `webpack.config.js`?

**Comment by echan00** [comment]
Hmm I don't remember anymore. Make sure your jquery and bootstrap versions are up to date?

**Comment by Guoxweii** [comment]
+1
the same problem.

**Comment by rochefort** [comment]
I'm facing the same problem.
I am using Rails6 + Webpacker. I was able to work around the problem by doing the following, but is there any other better way?

```
     } else {
         // Browser globals
-        factory(root.jQuery, root.ko);
+        factory(window.jQuery, root.ko);
     }
    }
})(this, function ($, ko) {
```

It seems that `root` is being passed `this`, but via webpack(er), it is an empty object.

**Comment by terasawa2** [comment]
It works fine.
https://github.com/davidstutz/bootstrap-multiselect/issues/1123#issuecomment-731151754

**Comment by rochefort** [comment]
It works fine.
https://github.com/davidstutz/bootstrap-multiselect/issues/1123#issuecomment-731151754

**Comment by rochefort** [comment]
3. Use the imports-loader to configure this
https://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack/28989476#28989476

Isn't the problem with this that bootstrap-multiselect is legacy?
