### ISSUE TITLE
'Select All' doesn't work

### ISSUE THREAD

**Issue by TripleGK** [davidstutz/bootstrap-multiselect#1127]
When I initialized with below option, 'select all' option doesn't work when collapsed optGroups
refer to : https://codepen.io/TripleGK/pen/bGddGvw
(for 0.9.13, 'select all' option works, but filtering doesn't work)

{
      includeSelectAllOption: true,
      enableCollapsibleOptGroups: true,
      collapseOptGroupsByDefault: true,
      enableClickableOptGroups: true,
      enableFiltering: true
}

**Comment by nltr2** [comment]
try this:
selectAllJustVisible: false,

**Comment by TripleGK** [comment]
> try this:
> selectAllJustVisible: false,

Thank you for your response, it is helpful solution
