### ISSUE TITLE
'rebuild' disables 'enablefiltering'

### ISSUE THREAD

**Issue by Drifeter** [davidstutz/bootstrap-multiselect#113]
when a multiselect is created using enableFiltering : true like this
$('.multiselect').multiselect({
        includeSelectAllOption: true,
    enableFiltering: true
})
the search option appears and its all OK.

but after a rebuild is made
$("#mySelect").multiselect('rebuild');

the search option disappears...

how can i rebuild the multiselect with enableFiltering: true? 
or at least inject this property after the rebuild is made.

**Comment by zohaib055** [comment]
not working in updated version

**Comment by jsarkarssi** [comment]
After using this 
$select.multiselect('rebuild');
The Dropdown no longer shows the filter options which I activated during initialization. Seems like a bug to me... or am I missing anything?

**Comment by Nishantsaini04** [comment]
This issue not fixed yet? I am waiting for it
