### ISSUE TITLE
Multiselect option list won't open?

### ISSUE THREAD

**Issue by zomby22** [davidstutz/bootstrap-multiselect#1145]
I try the Bootstrap Multiselect latest version and it did not work for me.

using WET4 bootstrap government template.
browser: IE11 or IE Edge (this GitHub page didn't work properly with IE11, had to use IE edge). Also tested with firefox, same results.
both multiselect css and js files included.

code:
```
$(document).ready(function() {
    $('#txttopics1').multiselect({
				nonSelectedText: 'Select',
				includeSelectAllOption: true
    });
});
```

results: the drop down menu appears grey and nothing happens when click on it.
![multiselect](https://user-images.githubusercontent.com/20478259/83153201-ae85d380-a0cc-11ea-8882-996421f569a1.jpg)

**Comment by zomby22** [comment]
turns out government doesn't have this bootstrap js file by default, with this, its works.

**Comment by zomby22** [comment]
what class that can override to keep the select button white like the demo example. I can't use the default bootstrap css file, it messes with the template css classes.

**Comment by tiesont** [comment]
I would need to verify this, but I'd assume this gets something similar to the "native" look:

```js
$('your-selector-here').multiselect({
    buttonClass: 'btn-outline-light bg-white text-dark border'
});
```

That's assuming you're using Bootstrap 4. See http://davidstutz.de/bootstrap-multiselect/#configuration-options-buttonClass

**Comment by zomby22** [comment]
working using "btn btn-outline-dark bg-white brdr-lft brdr-rght brdr-bttm brdr-tp"
looking at matching the arrow like this:
![multiselect](https://user-images.githubusercontent.com/20478259/83653100-5e55b800-a589-11ea-868a-aa312c4cdee8.jpg)
