### ISSUE TITLE
disabledText displays when list contains items but none are selected

### ISSUE THREAD

**Issue by DanBrownSyncbak** [davidstutz/bootstrap-multiselect#1153]
the disabledText is being displayed on the dropdown when no items are selected but the list is populated. 

multiselect: {
                    disableIfEmpty: true,
                    nonSelectedText: 'Available Channels',
                    disabledText: 'No Channels Available',
                    enableCaseInsensitiveFiltering: true,
                    enableFiltering: true,
                    enableFullValueFiltering: false,
                    numberDisplayed: 1,
                    maxHeight: 200 
}

Once the page loads the dropdown is not disabled because there are items in the list but the disabledText 'No Channels Available' is still displayed.

**Comment by s-eckard** [comment]
Hello DanBrownSyncbak, this bug should be fixed now.
