### ISSUE TITLE
Release v0.9.16 not compatible with Bootstrap 3.

### ISSUE THREAD

**Issue by rdeveen** [davidstutz/bootstrap-multiselect#1156]
Version 0.9.16 is not compatible with Bootstrap 3.3.7. 

![image](https://user-images.githubusercontent.com/5731724/98820571-9e6d7080-242e-11eb-9b25-da0fa2f358b4.png)

Version 0.9.15 is working as suspected with Bootstrap 3.3.7.

![image](https://user-images.githubusercontent.com/5731724/98820645-b6dd8b00-242e-11eb-9293-89e810276050.png)

Only different between those two images is the version of bootstrap-multiselect.

Version number should have been a major upgrade, not v0.9.16 but v0.10.1.

**Comment by rdeveen** [comment]
#1154

**Comment by rdeveen** [comment]
It's not really an issue if you are using Bootstrap 4 but a major version number upgrade and some warning notes would be nice.

**Comment by jacobSpitzer** [comment]
i have the same issue. using bootstrap 3.3.7

**Comment by jacobSpitzer** [comment]
I just changed to version 0.9.13 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/0.9.13/css/bootstrap-multiselect.css">
and for that version it works fine

**Comment by davidstutz** [comment]
Thanks for pointing out. Should have indicated that in the release. I am thinking to just make a version change to 1.0 and indicate it in the message, so it's clearer.
