### ISSUE TITLE
No options within dropdown menu

### ISSUE THREAD

**Issue by Ariannnnnn** [davidstutz/bootstrap-multiselect#1159]
Hello, I am using BS4 and am using the v0.9.1.5 of your plugin. However I am not getting any options within the dropdown menu. What am I doing wrong here? Attached are the images of code and output. I have also tried this with version 2.x of jQuery, and the same issue still occurs.

![image](https://user-images.githubusercontent.com/74015577/100020772-6101cf00-2dae-11eb-960b-dd2f279aa29b.png)
![image](https://user-images.githubusercontent.com/74015577/100020805-724adb80-2dae-11eb-9072-cc519c11ecbc.png)

**Comment by Ariannnnnn** [comment]
Also here is the code that I am using:
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        
        <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css"/>
        <script type="text/javascript" src="js/jquery-3.5.1.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>

        
        <link rel="stylesheet" href="css/bootstrap-multiselect.css" type="text/css"/>
        <script type="text/javascript" src="js/bootstrap-multiselect.js"></script>
        <title></title>
    </head>
    <body>
        <select id="demo" multiple="multiple">
            <option value="cheese">Cheese</option>
            <option value="tomatoes">Tomatoes</option>
            <option value="mozarella">Mozzarella</option>
            <option value="mushrooms">Mushrooms</option>
            <option value="pepperoni">Pepperoni</option>
            <option value="onions">Onions</option>
        </select>
        
        <script type="text/javascript">
            $(document).ready(function() {
                $('#demo').multiselect();
            });
        </script>
    </body>
</html>

**Comment by Ariannnnnn** [comment]
@s-eckard would you mind looking at this issue?

**Comment by Ariannnnnn** [comment]
hadn't include popper.js

**Comment by markusd1984** [comment]
> hadn't include popper.js

Surprised this wasn't mentioned in the getting started guide....

**Comment by tiesont** [comment]
> > hadn't include popper.js
> 
> Surprised this wasn't mentioned in the getting started guide....

Well, to be fair, it _is_ mentioned in the Bootstrap docs, and I think an assumption can be made that if you're using a plugin based on Bootstrap, that the Bootstrap dependencies also apply.

One could always submit a pull-request with an updated gh-pages page, if one were so inclined.
