### ISSUE TITLE
[BUG] Selecting option in Firefox

### ISSUE THREAD

**Issue by jamesRUS52** [davidstutz/bootstrap-multiselect#1168]
Selecting option by direct click on checkbox occure submit form (refresh page).

This behavior only when multiselect inside a form tag.

Apply only firefox

**Comment by MalteKiefer** [comment]
I have the same issue here @davidstutz can you take a look into this?

**Comment by s-eckard** [comment]
I can reproduce this bug when I use the release v1.0.0 but not with the code from the master. 
Do you have this issue if you test it on the [demo page](http://davidstutz.github.io/bootstrap-multiselect/#post)?

**Comment by jamesRUS52** [comment]
This issue does not occure on demo page.
I reinstall plugin from master and issue is gone.
