### ISSUE TITLE
4 vulnerabilities listed for version 0.9.15

### ISSUE THREAD

**Issue by BhuvanaBellala** [davidstutz/bootstrap-multiselect#1176]
Hi

There are 4 vulnerabilities listed on cdn for version 0.9.15. Will these be addressed?

**Comment by tiesont** [comment]
Which CDN are you referring to?

**Comment by BhuvanaBellala** [comment]
Yes I am referring to the 0.9.15.
Thank you! I will update my jquery, I did not realize these were indirect.
