### ISSUE TITLE
Tabbing Issues

### ISSUE THREAD

**Issue by tylerguenther** [davidstutz/bootstrap-multiselect#1183]
I can't tab to the control. I can move from field to field normally with tab until I get to the multi select drop down. I'm not sure what has focus after I leave the control above it but I have to press tab twice before the multi select gets focus. Is there something I am missing? I can't seem to find any documentation that tabbing has to be set up.

**Comment by s-eckard** [comment]
This is caused by the original html select element which is hidden but still is focused when tabbing through the elements. For a quick fix you can add `tabindex='-1'` to the html select. We will also add this to the lib.
