### ISSUE TITLE
Dropdown closing when scrolling

### ISSUE THREAD

**Issue by mrcbt** [davidstutz/bootstrap-multiselect#1186]
Hello, This is very weird, when I open the multiselect and use the mousewheel to scroll the dropdown closes. Did this happened to anyone?

https://youtu.be/H1ec0zCd0rE

**Comment by s-eckard** [comment]
I couldn't reproduce this behaviour with Chrome, Firefox, Edge or IE11. Which browser are you using? Could you provide a code snipped or a link where this behaviour occures?

**Comment by mrcbt** [comment]
Fixed. It was a setting with another plugin I was using
