### ISSUE TITLE
Is there any way to ignore capitalization with the search?

### ISSUE THREAD

**Issue by Alzavio** [davidstutz/bootstrap-multiselect#1194]
It's a bit frustrating that it won't pick something up due to capitalization

**Comment by tiesont** [comment]
Have you tried [enableCaseInsensitiveFiltering](http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-enableCaseInsensitiveFiltering)?

**Comment by Alzavio** [comment]
Jeez, my bad, not sure how I missed that. Sorry about that

**Comment by tiesont** [comment]
Well, the documentation does need some refreshing. I think that's on the list of things to accomplish in 2021. One of the other collaborators is working on cleaning up the codebase and fixing some long(ish)-standing issues, so... glad that was a simple solution.
