### ISSUE TITLE
selectAll checkbox current status

### ISSUE THREAD

**Issue by ayanezeclac** [davidstutz/bootstrap-multiselect#1198]
Hi Guys,

How can I retrieve the current state of selectAll (on / off) checkbox from a given Multiselect?

So far, I can retrieve the values of the selected checkboxes, except for the selectAll checkbox. I need to read if the selectAll, is selected or not. A true / false would be fine.

I guess I'm missing something

thanks in advance
andres

**Comment by s-eckard** [comment]
Right now there is no function to read this state. The state of the selectAll checkbox also depends on the filtering.
The easiest way would probably be to access the checked state of the checkbox itself.
