### ISSUE TITLE
Multi select box position issue

### ISSUE THREAD

**Issue by topsinfor** [davidstutz/bootstrap-multiselect#1199]
Hi,

I am facing an select options box position issue whenever the select options box appears at top of the select element and then search for any option via a keyword then the select box height reduced and there is a gap between select option box and select element
![1](https://user-images.githubusercontent.com/83745799/117245145-f6be8180-ae57-11eb-87f2-e9a0e3a61de2.png)

Please help to resolve this issue

**Comment by nishittops** [comment]
I'm also facing the same issue.

**Comment by s-eckard** [comment]
This is an issue with the bootstrap dropdown element. It doesn't recognice the change of the menu height and therefore doesn't re-calculate the menu position. 
I will try to fix this problem soon.

**Comment by s-eckard** [comment]
The changes which fix this issue are now in the master.
