### ISSUE TITLE
Removing jQuery dependency

### ISSUE THREAD

**Issue by JohnJVTK** [davidstutz/bootstrap-multiselect#1201]
Hello,

Do you have any plans on removing jQuery dependency ?

Thanks,
John

**Comment by tiesont** [comment]
This probably is a better fit for the [Discussions](https://github.com/davidstutz/bootstrap-multiselect/discussions) section, but to answer your question: no, not anytime soon.

**Comment by s-eckard** [comment]
Before we remove JQuery from the plugin we will need to migrate it to Bootstrap v5.0. Removing JQuery will then be a bigger task because this is a major rewrite of the plugin.
