### ISSUE TITLE
How do you get current selected options?

### ISSUE THREAD

**Issue by yankarinRG** [davidstutz/bootstrap-multiselect#1207]
My use case is to call an API without using a button in a form, so I need to collect all the multiple checked (selected) values.
I looked on the documentation but it looks like it only works with events. Is there a better way than subscribing to the change event and push to a global variable and then retrieving like this?

For example:
`var checked = $(#my-select).multiselect('selected');
`
Thanks!

**Comment by yankarinRG** [comment]
Solution found:
`var checked = $(#my-select).val();`

**Comment by markusd1984** [comment]
or var checked = $('#my-select').find('option:checked');
