### ISSUE TITLE
It doesnt work with Bootstrap 5

### ISSUE THREAD

**Issue by htdung83** [davidstutz/bootstrap-multiselect#1226]
I am using Bootstrap 5.1.3 and try to install this plugin but it seems not to work with Bootstrap 5. The screen showed none selected unstyled button only. The list, even, doesn't show on clicking event.
![unstyled-button](https://user-images.githubusercontent.com/9692914/153110763-3c9c0d65-7c17-4143-b82d-0f3e03b55d30.JPG)
.

**Comment by tiesont** [comment]
Correct - Bootstrap 5 is not currently supported. You can use this library with Bootstrap 3 or Bootstrap 4.

**Comment by PawelPatyk** [comment]
It should help:
```
$('#custom-select').multiselect({
    templates: {
        button: '<button type="button" class="multiselect dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><span class="multiselect-selected-text"></span></button>'
    },
});
```

**Comment by htdung83** [comment]
Thanks a lot

**Comment by htdung83** [comment]
> It should help:
> 
> ```
> $('#custom-select').multiselect({
>     templates: {
>         button: '<button type="button" class="multiselect dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><span class="multiselect-selected-text"></span></button>'
>     },
> });
> ```



> It should help:
> 
> ```
> $('#custom-select').multiselect({
>     templates: {
>         button: '<button type="button" class="multiselect dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><span class="multiselect-selected-text"></span></button>'
>     },
> });
> ```

Thankss a lot

**Comment by gh-at-sqh** [comment]
`$.fn.multiselect.Constructor.prototype.defaults.templates.button = '<button type="button" class="multiselect dropdown-toggle form-control" data-bs-toggle="dropdown"><span class="multiselect-selected-text"></span></button>'`

**Comment by NorbertHanni** [comment]
text-left --> text-start and text-right --> text.end
$.fn.multiselect.Constructor.prototype.defaults.buildButton      
if (this.options.buttonTextAlignment) {
    switch (this.options.buttonTextAlignment) {
        case 'left':
            this.$button.addClass('text-start');
            break;
        case 'center':
            this.$button.addClass('text-center');
            break;
        case 'right':
            this.$button.addClass('text-end');
            break;
    }
}

**Comment by davidstutz** [comment]
Closing with reference to #1189.

**Comment by markusd1984** [comment]
> Correct - Bootstrap 5 is not currently supported. You can use this library with Bootstrap 3 or Bootstrap 4.

Thanks, that explains why I didn't get any dropdown, was hard to figure out with the lack of mention in the guide and no errors in the console, this should be mentioned in the guide and ideally an error in the console. =)

Also popper.js is required for dropdowns, neither any mentions as far I saw.
