### ISSUE TITLE
Add info in README that v0.9.15 is the last compatible version with Bootstrap 3

### ISSUE THREAD

**Issue by AlexByte** [davidstutz/bootstrap-multiselect#1237]
> [v1.0.0](https://github.com/davidstutz/bootstrap-multiselect/releases/tag/v1.0.0)
Bootstrap 4 support.

>
> Note that this release might be incompatible with Bootstrap 3 or older. Also note that this was originally release/tag v0.9.16. To indicate the change from Bootstrap 3 to Bootstrap 4, I decided to directly go to v1.0.0. So the stable release for Boostrap 3 is[ v0.9.15](https://github.com/davidstutz/bootstrap-multiselect/tree/v0.9.15).
>https://github.com/davidstutz/bootstrap-multiselect/releases/tag/v1.0.0

**Comment by davidstutz** [comment]
I think the relase note is clear enough.

**Comment by AlexByte** [comment]
Тo one will read the description of the old release. Only when it doesn't work, if.
