### ISSUE TITLE
"Dropup" list

### ISSUE THREAD

**Issue by caneta** [davidstutz/bootstrap-multiselect#124]
Hi David.
I have a simple question: a normal select toggles automatically from a dropdown list to a "dropup" list if there is room up or down the select element on the page.
For example, if a select widget is at the bottom of a page, where the browser window ends, the list is rendered up.
Is there a way to tell to boostrap-multiselect to beahave the same way?
Thank you!

**Comment by Tharunnath** [comment]
![dropup](https://cloud.githubusercontent.com/assets/19459178/15382882/d025abc6-1dab-11e6-850c-2830e287df2d.png)


please can you explain how to handle drop up when we are searching anything it is going above from text box
