### ISSUE TITLE
Removing default selected for radio buttons

### ISSUE THREAD

**Issue by jm21** [davidstutz/bootstrap-multiselect#129]
Am using bootstrap-multiselect with radio buttons and option group instead of checkboxes as I want the user to select only one option. The script works great but the first option in the dropdown is always selected, this happens only when using radio buttons, is there a way to disable this?

**Comment by pranshuagrawal** [comment]
Any workaroud for this?

**Comment by ddegil** [comment]
Simply set the selectedIndex to -1 on the select BEFORE you run multiSelect. That solves it. :)

**Comment by grunmin** [comment]
> Simply set the selectedIndex to -1 on the select BEFORE you run multiSelect. That solves it. :)

in jQuery, use $(dom).val('')  :)

**Comment by CodeBrauer** [comment]
Thanks for this... was searching a solution way to long - maybe this should be mentioned in the docs?

`$('select').val('').multiselect();` works fine now! 👍

**Comment by kaladarri** [comment]
Solution for a Placeholder.

After call 
$('#anyId').val('').multiselect();

You can set this
$('.multiselect-selected-text')[0].innerHTML = 'Any text you want';

**Comment by wd16yuan** [comment]
@kaladarri @CodeBrauer 
`
<script>
$("#tests").multiselect({
    buttonWidth: "206px",
    nonSelectedText: "test is test",
});
$("#tests").val("").multiselect();
</script>
<html>
<select id="tests" name="test1">
    <option value="t1">t1</option>
    <option value="t2">t2</option>
    <option value="t3">t3</option>
</select>
</html>
`
Default choice 't1',  This method is invalid. What's the reason?

**Comment by wd16yuan** [comment]
@kaladarri @CodeBrauer 
`
```
<script>
$("#tests").multiselect({
    buttonWidth: "206px",
    nonSelectedText: "test is test",
});
$("#tests").val("").multiselect();
</script>
<select id="tests" name="test1">
    <option value="t1">t1</option>
    <option value="t2">t2</option>
    <option value="t3">t3</option>
</select>
```
`
Default choice 't1',  This method is invalid. What's the reason?

**Comment by fperniavp** [comment]
I know it's been a while, the solution of @CodeBrauer works but if you have a configuration like:

```
$("#mySelect").multiselect({
    buttonClass: "btn btn-default btn-lg btn-block",
   buttonWidth: "100%",
   maxHeight: 400,
});
```
When adding `$("#mySelect").val("").multiselect();` you will realize that the styles you put were deleted..

**Comment by fate2** [comment]
@fperniavp Thank you , It's works!!!`$("#mySelect").val("").multiselect();`

**Comment by weijie858** [comment]
Removing default selected for radio buttons  ？
function ajaxSelectDataDefault(selectId, requestUrl, requestData) {
    $.ajax({
        type: 'POST',
        url: requestUrl,
        data: requestData,
        success: function (data) {
            var result = eval(data);
            $("#" + selectId).val("").multiselect('dataprovider', result);
        },
        error: function (XMLHttpRequest, textStatus, errorThrown) {
            console.log(XMLHttpRequest, textStatus, errorThrown)
            if (XMLHttpRequest.readyState === 4) {
                if (XMLHttpRequest.status === 401) {
                    alert("ajax fail:" + errorThrown);
                }
               
            }
        }
    });
}

**Comment by Simon-Guo1** [comment]
I have a simple solution. 
$('#multiSelect').append(
                                    $('<option class="hidden" ></option>')
                                            .val("any text you want")
                            ); 
Have fun! now.

**Comment by Simon-Guo1** [comment]
I have a simple solution by add a hidden option to the first.
`$('#multiSelect').append(
                                    $('<option class="hidden" ></option>')
                                            .val("any text you want")
                            );`
Have fun now.

**Comment by markusd1984** [comment]
> I know it's been a while, the solution of @CodeBrauer works but if you have a configuration like:
> 
> ```
> $("#mySelect").multiselect({
>     buttonClass: "btn btn-default btn-lg btn-block",
>    buttonWidth: "100%",
>    maxHeight: 400,
> });
> ```
> 
> When adding `$("#mySelect").val("").multiselect();` you will realize that the styles you put as properties are discarded. So, in order to correct that, just do: `$("#mySelect").val("");`. That's what @grunmin suggested.

+1 this avoids loosing the search bar.
