### ISSUE TITLE
Does not work on ipad or mobile

### ISSUE THREAD

**Issue by noctivityinc** [davidstutz/bootstrap-multiselect#13]
Just tried the demo on an ipad.  It displays the drop downs fine  does not allow me to select any boxes.  The drop downs simply hide.

**Comment by mrugesh2307** [comment]
@davidstutz @noctivityinc I found a solution by disabling z-index of class **.dropdown-backdro**p.
this class with div is added before ul. Just remove z-index or decrease z-index to 1. It will allow checkbox selection.

I hope this helps to you.

**Comment by NiekRood** [comment]
@mrugesh2307 Your solution worked for me.

**Comment by TamizhJayapal** [comment]
@davidstutz @programcsharp I have problem in multiselect like #52 .
I have using bootstrap 3.3.7 and bootstrap multiselect 0.9.13.I have using form in modal. I can select the dropdown options in field.But the modal is simply hide when click out of the dropdown after select the options.

**Comment by TamizhJayapal** [comment]
@davidstutz @programcsharp I have problem in multiselect like #52 .
I have using bootstrap 3.3.7 and bootstrap multiselect 0.9.13.I have using form in modal. I can select the dropdown options in field.But the modal is simply hide when click out of the dropdown after select the options.

**Comment by TamizhJayapal** [comment]
> i will update

**Comment by tiesont** [comment]
@TamizhJayapal I'm not getting the correlation to "Does not work on ipad or mobile" - if you have a different problem, you should really open a new issue.
