### ISSUE TITLE
Add indicator that results are being filtered

### ISSUE THREAD

**Issue by eerichmond** [davidstutz/bootstrap-multiselect#155]
Can we add a clear button (maybe an X) next to the search box, that would only show up when the results are being filtered? The reason I'm asking for this feature is that some of our users are forgetting that they entered something into the filter box after they close and reopen the multiselect. Another option might be to add the .warning class to a div around the input when the results are being filtered. Thanks.

**Comment by davidstutz** [comment]
This is now the default.
