### ISSUE TITLE
Problem with multiselect('refresh')

### ISSUE THREAD

**Issue by terzano** [davidstutz/bootstrap-multiselect#166]
Every time I invoke it all the items on the list are removed. 
Is this a bug or I am doing something wrong. 
The list is populated using a handlebar template. 
I am trying to deselect all the items but when I call 'refresh' all the items are gone. 

Any help is greatly appreciated.

**Comment by bayurepo** [comment]
i am experiencing the same problem too. Is it any fixing yet ?

**Comment by reinaldocoelho** [comment]
I'm having a long time to loading the refresh for combining with 1300 items.
The charge is taking 7 seconds to complete.
It´s normal?

**Comment by KhadeerUI** [comment]
I have also experienced the same issue but finally, I resolved. Please use $(selecter).multiselect("refresh"); instead of $(selecter).multiselect("reload");

**Comment by pisaq** [comment]
I also have that problem.

`$input.val([]).multiselect('refresh')`

above 1k elements
takes long time
