### ISSUE TITLE
Can't disable multiselect

### ISSUE THREAD

**Issue by donbonifacio** [davidstutz/bootstrap-multiselect#171]
Hello,

I can't seam to enable/disable a multiselect. 
Example: when I go to this page:

http://davidstutz.github.io/bootstrap-multiselect/

And on the chrome console I enter:

``` javascript
$("#example31").prop('disabled', false);
```

The select turns to the expected state, but the UI doesn't change.

Am I doing something wrong?
Thanks

**Comment by kronikles** [comment]
how can we used that enable/disable?

**Comment by Wizardre** [comment]
Using jquery
    $("#status").prop("disabled", true);

**Comment by Errol12** [comment]
Hello,

I can't seam to enable/disable a particular option in multiselect dropdown.
Any solution?

**Comment by armangithub** [comment]
@Errol12
https://github.com/davidstutz/bootstrap-multiselect/issues/476#issuecomment-71461232

That works for me
