### ISSUE TITLE
Options not visible when using multiselect inside bootstrapper Collapse

### ISSUE THREAD

**Issue by qorsmond** [davidstutz/bootstrap-multiselect#180]
When I use the bootstrap-multiselect component iside a panel the options don’t show correctly, here is a plunk: http://plnkr.co/edit/d4je5XBPk5fhfIhl8xCi?p=preview

I tried playing with the z-index but cant get it to show correctly.

**Comment by john-stephen** [comment]
Need to remove overflow:hidden or change it to overflow:visible of div. The issue get solved.

**Comment by helmus** [comment]
Please reopen this. There are numerous projects out there that handle this without issue. Take a look at bootstrap tooltip for example. We could apply the same solution here.

**Comment by rajashekharse** [comment]
Got a Solution. Checkout the below Fiddle.

https://jsfiddle.net/shekhargood/u1xfz9zh/

**Comment by IevgenBaziak** [comment]
@rajashekharse 
Sorry, but statically positioning the menu carrier will work only until you scroll the page (provided the contents of the page or settings require/allow scrolling).
Once user scrolls the page - the calculated positions are not valid anymore.

**Comment by Siddhant3five8** [comment]
@sharath-krishna is right. Did you find any solution for this?
After removing the bootstrap-3.3.2.min.js, the dropdown menu starts opening, but then the checkbox adjacent to options is getting clipped.
