### ISSUE TITLE
Method for rebuilding list

### ISSUE THREAD

**Issue by kibs** [davidstutz/bootstrap-multiselect#19]
I miss a method for rebuilding the dropdown list, which i can trigger after i have changed the options in the select.

Ay thoughts on this? At the moment i do this, after i have added or removed options from the select.

``` javascript
$select.multiselect('destroy');
$select.data('multiselect', null);
$select.multiselect();
```

**Comment by RajalakshmiBalasubramanian** [comment]
I have a need. On selecting a value in one dropdown, I have to reload the multiselect  listbox with different values.

How to remove existing options in multiselect and load different options? I am using visual studio mvc. I tried removing the options in my listbox. But it doesn't work. Am I doing wrong?

Please find the psuedocode below.

$("#States").multiselect('destroy');
LoadStates();
$("#States").multiselect('rebuild');

function LoadStates()
{
$.getJSON('/User/GetRolesSpecificToSelectedUserGroup?UserGroupId='+selectedUserGroupId, function (data) {
$.each(data, function (i, item) {
                $('#States').append('<option value="' + item.Id + '">'
                    + item.Name + '</option>');
            })
});
}
