### ISSUE TITLE
Single selection without radio buttons?

### ISSUE THREAD

**Issue by drmcclelland** [davidstutz/bootstrap-multiselect#205]
Is there a way to accomplish single-selection without showing the radio buttons?  My purpose is to have all my "selects" (single-selection and multi-selection) render visually the same, but I would rather have less visual distraction to the users when they only need to select a single item.

**Comment by peterkinnaird** [comment]
An alternative to fix the `.filter(':visible')` problem is to hide the checkboxes with `visibility: hidden;` instead, or `opacity: 0`

That will allow you to keep the original source code as-is.

**Comment by niyazpk** [comment]
Just to hide the single select radio, while keeping the checkboxes:

  .multiselect-container input[type=radio] {
      display: none;
  }

**Comment by pgoldweic** [comment]
How would one hide the checkboxes -via CSS- but only when they correspond to option groups? (I found that if I have collapsible option groups, the checkboxes always show up for the groups, while I want to disallow a check of all the items in the option group).

**Comment by markusd1984** [comment]
> 

I had to use the below to make it work

`$('.multiselect-container input[type=radio]').css("display", "none");`
