### ISSUE TITLE
Knockout async binding issues

### ISSUE THREAD

**Issue by holm-dk** [davidstutz/bootstrap-multiselect#214]
I'm having some problems with the Knockout binding. I have the following markup:

```
<select id="input-client" class="form-control" data-bind="
    options: clients,
    optionsText: 'name',
    optionsValue: 'id',
    value: selectedClientId,
    multiselect: {}">
</select>
```

This correctly renders the multiselect dropdown, but if the data is loaded asynchronously, some times the dropdown isn't rendered. I suspect that it has something to do with the multiselect list not being rebuild after having added objects to the options observable.

Does anyone know how to solve this issue?

**Comment by ghiotion** [comment]
There was a reference a while back about getting the AMD ready for use in require.js.  I'd REALLY like to do that in a project I'm working on so that the multiselect binding is available.  Can anyone offer any guidance?  Something like...

            'bootstrap-multiselect': {
                deps: ['jquery', 'bootstrap'],
                exports: 'ko.bindingHandlers.multiselect'
            }
