### ISSUE TITLE
Move menu above select element if the menu is close to the bottom of the viewport

### ISSUE THREAD

**Issue by DanielWeiner** [davidstutz/bootstrap-multiselect#218]
Just like the native select elements, have the menu be positioned above the select if it's close enough to the bottom of the viewport that it would be partially hidden from view when expanded.

**Comment by oranges13** [comment]
Hello, how do you add the class to the container?
I have added the `.dropup` class to the select and it does not work.

**Comment by davidstutz** [comment]
You can adapt the `buttonContainer` option.

**Comment by davidstutz** [comment]
I added an example in the Further Examples section that automatically drops up when scrolling.
