### ISSUE TITLE
My entire site style changed.

### ISSUE THREAD

**Issue by malhayek2014** [davidstutz/bootstrap-multiselect#220]
Hi,
my entrie site style changes. The font, spaces...... Do you have a version of the css style that will not effect the rest of the site (ie, contains only the css the are required by this widget) 

Also, when I select an option for a menu the text disperse. I don't know if this is a css issue or not.

**Comment by AlexByte** [comment]
The solution is to use site https://uncss-online.com/ to remove unneeded bootstrap styles from bootstrap.css
Algorithm: select some options in a bootstrap-multiselect, and copy html of bootstrap-multiselect in opened and closed state to the field Your HTML on this site. Then remove from shortened CSS styles for html, body, input and button elements.
