### ISSUE TITLE
IE8 support?

### ISSUE THREAD

**Issue by drmcclelland** [davidstutz/bootstrap-multiselect#224]
I don't see this working in IE8 anymore...  possibly because because jQuery 2+ dropped IE8 support (http://blog.jquery.com/2013/04/18/jquery-2-0-released).  I was wondering if anyone had gotten the current version of bootstrap-multiselect working with a jQuery 1.x release?

Here's an IE8 screenshot from the examples page:

![image](https://f.cloud.github.com/assets/6124858/2070144/8cc438ba-8d17-11e3-8421-66906e3b396e.png)

**Comment by awesomestvi** [comment]
I am getting the exact same issue, I'm using jQuery 1.12.1. Please can anyone help me with making this work with IE8.

**Comment by awesomestvi** [comment]
Okay, I've fixed this and it works for me. I was getting an error in IE8 saying 

> **Expected identifier, string or number**

 so the fix to that was really simple.

Open **bootstrap-multiselect.js** file and go to line number **1430**
`class: option.class,` just add quotations to this `'class': 'option.class',` and save the **bootstrap-multiselect.js** file.

And give it a try. It works for IE8 and IE7 as well.

**Comment by bibin-varghese-rockalltech** [comment]
When i altered this.$select.wrap('<span class="hide-native-select">') to this.$select.wrap('<span class="hide-native-select"></span>') ,line 223 of bootstrap-multiselect.js it worked. Quotations  to option.class also need to add.
