### ISSUE TITLE
Get rid of the unnecessary <a> tag in li template

### ISSUE THREAD

**Issue by philfreo** [davidstutz/bootstrap-multiselect#239]
Right now each row uses a template that contains an anchor/link tag:

`li: '<li><a href="javascript:void(0);"><label></label></a></li>',`

I propose that this `<a>` tag should be removed since it serves no semantic purpose. 

My guess is that you only kept it there for styling/spacing purposes since Bootstrap's dropdowns use links by default. However this effect could easily be achieved via tweaking styles of the `<li>` or `<label>`

Thoughts? Would you accept a PR that did this?

**Comment by cosmicdust73** [comment]
I just opened issue #480 prior to seeing this thread.  The issue is that these anchor tags are failing W3C validation.  Do I need to be concerned about the invalid markup or is it OK to leave the anchor tags in place?
