### ISSUE TITLE
Trigger event

### ISSUE THREAD

**Issue by ghost** [davidstutz/bootstrap-multiselect#248]
Is there anyway to trigger an event? Like after selecting a couple of options we may want to trigger the `onDropdownHide`...

I'm looking for something on the means of `$('#selectId').trigger('onDropdownHide');`

If there isn't please consider it, it would be most usefull

**Comment by thienedits** [comment]
@davidstutz I am using Bootstrap 3.1.1 and doing $().dropdown('toggle') does not trigger the onDropdownHidden event. Do I need to be on 3.2?

**Comment by thienedits** [comment]
Sorry nvm just figured it out, you have to select ".dropdown-toggle" selector.

**Comment by mabusalah** [comment]
I'm trying to submit the form using the below:
onDropdownHide: function(event){
this.form.submit();
}

But this is not working, any clue?
