### ISSUE TITLE
Method for overriding the search box icon, if not using glyphicons?

### ISSUE THREAD

**Issue by dflock** [davidstutz/bootstrap-multiselect#257]
I'm using icons from FontAwesome instead of glyphicons for my site. This causes the search box icon to be empty:

![screenshot - 14-03-13 - 02 28 08 pm](https://f.cloud.github.com/assets/47756/2415512/7cdf55d6-aaf6-11e3-9e1a-aacdef377000.png)

I naively tried to override the templates in my constructor:

```
  $('.multiselect').multiselect({
      includeSelectAllOption: true,
      selectAllText: 'Everyone',
      enableFiltering: true,
      enableCaseInsensitiveFiltering: true,
      templates: {
        filter: '<div class="input-group"><span class="input-group-addon"><i class="fa fa-search"></i></span><input class="form-control multiselect-search" type="text"></div>',
      },
    });
```

but that didn't work. I ended up using jQuery to replace the classes:

```
$('i.glyphicon.glyphicon-search').removeClass('glyphicon glyphicon-search').addClass('fa fa-search');
```

which works:

![screenshot - 14-03-13 - 02 28 21 pm](https://f.cloud.github.com/assets/47756/2415537/c657f4de-aaf6-11e3-9311-64d5e52b7110.png)

but it seems like there ought to be a better way? Is there a way to override the built in templates?

**Comment by CodeBrauer** [comment]
I just wanted to push that, this would be also a nice feature for upcoming bootstrap 4, because glyphicons got dropped & now you have to use something like fontawesome/icomoon or material-icons etc.

**Comment by mr-vaibh** [comment]
Right now they're using .fas class, which works really well with Font Awesome 6
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css
