### ISSUE TITLE
onDropdownShow and onDropdownHide not firing

### ISSUE THREAD

**Issue by daniebruwer** [davidstutz/bootstrap-multiselect#262]
I've pasted the example straight from the demo page and this event doesn't fire

$('.multiselect').multiselect({
        onDropdownShow: function (event)
        {
            alert('Show event invoked!');
        }
    });

$('.multiselect').multiselect({
      onDropdownHide: function(event) {
        alert('Hide event invoked!');
      }
    });

**Comment by Dacesilian** [comment]
For me event are not called when using http://behigh.github.io/bootstrap_dropdowns_enhancement/ . It works without dropdowns enhancement plugin.

**Comment by dhamaris** [comment]
@daniebruwer did you find out why it is not firing? I have the same problem.

**Comment by sunnyzhang66** [comment]
I have same issue, also can't fire onDropdownHide: function(event) {
alert('Hide event invoked!');
} 
in fact, onDropdownShow (), onDropdownHide(), onDropdownShown(), onDropdownHidden() all not get fired! , can you provide a sample can fire those events?

thanks!

**Comment by Hikyu** [comment]
I have the same problem...
