### ISSUE TITLE
Events are incompatible with 2.3.2 bootstrap

### ISSUE THREAD

**Issue by max-reznichenko** [davidstutz/bootstrap-multiselect#270]
Good day,

These events are not triggered in 2.3.2 bootstrap:
https://github.com/davidstutz/bootstrap-multiselect/blob/master/js/bootstrap-multiselect.js#L232-L233

Basically it means that there isn't any correct way to trigger functions on onDropdownShow / onDropdownHide actions.

I believe that there should be a sort of comment in README or workaround for this.

**Comment by istvanmadarasz** [comment]
For me the onDripdownShow is not working with Bootstrap 2.2
