### ISSUE TITLE
Add Uncheck all.

### ISSUE THREAD

**Issue by foxgenki** [davidstutz/bootstrap-multiselect#271]
Hi,
I wan't to know is there an option for "Uncheck all" ! and thanks.

**Comment by pgoldweic** [comment]
I know this item is now closed, but I wanted to suggest this feature once again. There's really no good reason to have an easy way to include a 'select all' feature - via options- but not include a 'deselect all' feature that works equivalently. While you explain that the 'select all' feature 'implicitly' includes a 'deselect all' feature, this only works if you *really want* to have a 'select all' button (what if you only want to have a 'deselect all' instead?)

**Comment by ashatp** [comment]
+1 
agree to @pgoldweic 's point

**Comment by davehorror** [comment]
I also agree with @pgoldweic.  I have been using the multiselects for a while and a spec has come in for a change. My product manager wants a 'none' option within the multiselect that deselects any options the user may have selected.  I am playing around with some js but may have to go with the reset button which is not as elegant.

**Comment by davehorror** [comment]
Actually the 'none' option has to be within the select box as this value needs to be collected by the back end team.  Does anyone have any ideas how to do this?

**Comment by thorst** [comment]
pseudo

onchange: function {
 if val=="none"
$("#myselect:option").attr(selected,false).multiselct(refresh)
}

**Comment by davehorror** [comment]
Thanks I will give this a go

**Comment by pgoldweic** [comment]
For the record, I was recently able to implement a 'deselect all' feature quickly via the following Javascript - which gets triggered when clicking on a new button I created- (not sure if this was available all along or not, I certainly hadn't seen it earlier):

$('#<yourMenuId>').multiselect('deselectAll', false);  

Still not as pretty as using a built-in 'deselect all' (an additional button was needed) but works fine, and it can be used in the meantime.

**Comment by davehorror** [comment]
Thanks for this but I need to have none as a value to be captured in a database. Tough requirements!

**Comment by lwnoble** [comment]
David... I have modal window that loads when a particular items is clicked on.  I load a form with many input fields and multi-select drop down menus.  But the data gets cached in the multiselect form and does not get updated.  I just can get it up update.  I've tried endless variations... Here is my current code:

    var HSElig = $('#inView').find('.HSElig').text().split(",");
    $('#example-deselectAll').multiselect('deselectAll', true);
    $('#highschollEligiable').multiselect('refresh');
    $.each(HSElig,function(i){
	   
	   $('#highschollEligiable option[value=' + HSElig[i] +']').attr("selected", "selected");
	   $('#highschollEligiable').multiselect('refresh');
	   $('#highschollEligiable').multiselect('updateButtonText');
    });
