### ISSUE TITLE
Trigger onChange after select/deselect options

### ISSUE THREAD

**Issue by naxxateux** [davidstutz/bootstrap-multiselect#288]
Hi all.

Sorry for the dumb question, but how can I trigger the onChange for my .multiselect after selecting/deselecting options (`.multiselect('select', value)` or `.multiselect('deselect', value)`)?

**Comment by proshuai** [comment]
this question i met, last week, it works well, but today is not work

**Comment by Giovancruz** [comment]
This `.trigger('change')` didn't work

**Comment by bewards** [comment]
@Giovancruz and @proshuai I believe the correct way of triggering this is with a 2nd parameter with the following method:

`$('#multiselect').multiselect('deselect', value, true)`

**Comment by HectorGP** [comment]
> @Giovancruz and @proshuai I believe the correct way of triggering this is with a 2nd parameter with the following method, which worked for me:
> 
> `$('#multiselect').multiselect('deselect', value, true)`

You save me!! <3 haha
