### ISSUE TITLE
Adding additional data to li item via templates?

### ISSUE THREAD

**Issue by ankitsam** [davidstutz/bootstrap-multiselect#293]
Hi, 
Thanks for wonderful extension.

I have one issue, I want to add image before the item.
Is there a way to read additional data from  select `<option data-image="image.png">`
using the data-image and add it to multiselect via templates?

```
templates: 
{
  li: '<li><a href="javascript:void(0);"><img src="data-image" /><label></label></a></li>'
}
```

Thanks

**Comment by juanmarinelli** [comment]
Hello! Thanks for the help, I am trying to use this example to insert images. But I'm not recognizing the label: in the function. If instead of label: I put optionLabel: it puts me as text in each option "<img ...>" that the function is good. How can I do to be recognized by the label: ?
Thanks

**Comment by devmi** [comment]
@juanmarinelli,  did you find the answer to your question?
