### ISSUE TITLE
Up/Down/Space/Enter Keys are not working in the multiselect dropdown

### ISSUE THREAD

**Issue by srkgupta** [davidstutz/bootstrap-multiselect#30]
Hi, 

If you check the jquery ui version of multiselect, we can navigate to different options using Up Arrow /Down Array Keys. We can also select a particular option using space or enter key. 

http://www.erichynds.com/examples/jquery-ui-multiselect-widget/demos/

This is not working in the bootstrap version of multiselect. Any idea how do we handle this here?

**Comment by ptijul** [comment]
Hello,

This should be great if, when we press down key from the textbox filter (enableFiltering: true), we could navigate to the first item matching the filter. 
And also, when we are on the first item AND it exists a filter textbox to focus on it. 

Is there any change you add this feature in a upcoming release ? 

Thanks and regards,
Julien

P:S: Keep doing this great job on this plugin, I really like it.
