### ISSUE TITLE
Display 'No results match' message when search doesn't render results

### ISSUE THREAD

**Issue by bmartin2305** [davidstutz/bootstrap-multiselect#317]
Hi, 
  I was wondering if it is possible to add in  'No results match' when searching and nothing comes up? What would be the best way to do this.

**Comment by Tushar412** [comment]
Will  I able to use this feature? Is latest code updated with changes? How can I use this?

**Comment by jstevenson** [comment]
@Tushar412 I added my solution to stackoverflow at http://stackoverflow.com/questions/32347336/bootstrap-multiselect-with-no-search-result-message/32956402

**Comment by shashiram** [comment]
This external code provides "no result match " with search key word   
$(document).on("keyup", ".multiselect-search", function (e) {
       
            var thisObj = this;

            setTimeout(function () {

                if ($(thisObj).parent().parent().parent().find("li.multi-no-results").length == 0)
                    $(thisObj).parent().parent().parent().append('<li style="display:none" class="multi-no-results cropin-multi-select-noresult-lable"><a  href="#">No results matched ""</a></li>');

                var totalOptions = $(thisObj).parent().parent().parent().parent().siblings().last().find("option").length;
                var totalFilteredOptins = totalOptions - $(thisObj).parent().parent().parent().find("li.filter-hidden").length;

                if (totalFilteredOptins <= 0) {
                    $(thisObj).parent().parent().parent().find("li.multi-no-results").find("a").text('No results matched "' + $(thisObj).val() + '"');
                    $(thisObj).parent().parent().parent().find("li.multi-no-results").show();
                }
                else {
                    $(thisObj).parent().parent().parent().find("li.multi-no-results").hide();
                }

            }, 300);
    
    });
