### ISSUE TITLE
How to grab value of multiselect in php

### ISSUE THREAD

**Issue by aaron4osu** [davidstutz/bootstrap-multiselect#323]
I have a form that uses the multiselect as well as other text input fields.  When I try to send to php using JQuery ajax request I'm only getting the last item in the multiselect.  I know the values are stored on the var options, because I tested it with an alert.  But how do I add it to the .home1 form to serialize and send over to php?  

```
var options = validator.getFieldElements('product').val();
 $.ajax({
   type: "POST",
   url: "process-step1.php",
   data: $('.home1').serialize(),
   success: function(msg){
       document.location.href = 'form.php';
    },
   error: function(){
     alert("error");
   } 
 });//close ajax              
```

**Comment by AstmDesign** [comment]
Please check the example : https://github.com/AstmDesign/BootstrapAjaxMultiselect
