### ISSUE TITLE
Radio input is not checked when there are multiple select boxes

### ISSUE THREAD

**Issue by ilyai** [davidstutz/bootstrap-multiselect#331]
I have found a small defect with radio inputs not being checked in every except one bootstrap-multiselect instances that preset on the page.
I guess it is due the fact that each radio input in all select boxes has the same name (multiselect) and handled as a group, therefore only one of them can be checked.

![multiselect_radio_bug](https://cloud.githubusercontent.com/assets/1911270/3339309/db288cd2-f869-11e3-88ad-bcbee9f534ef.png)

**Comment by andyg2** [comment]
When initiating multiple multiselect instances simultaneously I found this helped.

```
  checkboxName: function (option) {
    return (Math.random() + 1).toString(36).substring(10);
  },
```
