### ISSUE TITLE
Button active state when one or more items are selected

### ISSUE THREAD

**Issue by JesseWynants** [davidstutz/bootstrap-multiselect#332]
Is there a clean way of giving the button an active state when one or more items in the drop down are selected?

I know it's possible with a work-around, but would be cleaner if you could just pass the class to the multiselect.

We use the multiselect for filtering, these filters are persistent (stored in the user session) so it's good to be able to show clearly that some of the filters are active:
![screen shot 2014-06-20 at 14 48 45](https://cloud.githubusercontent.com/assets/1507462/3340134/416c7580-f879-11e3-9495-d6849f590804.png)

**Comment by BharatBhatiya** [comment]
For Version 2.0
you need to also specify option enableHTML: true, then @parisiam code will work fine.. :)

```
buttonText: function(options, select) {
                if (options.length === 0) {
                    return '<span class="color-gray">No option selected</span>';
                } else {
                     ...the rest of the example is in the documentation
                }
            }
```
