### ISSUE TITLE
How to load ajax option when type words in search input?

### ISSUE THREAD

**Issue by hisune** [davidstutz/bootstrap-multiselect#338]
How to load ajax option when type words in search input?
THX ^_^

**Comment by baladkb** [comment]
Hi @hisune,  do You have any demo for **load ajax option**, please share with us.

Thanks :octocat:

**Comment by hisune** [comment]
@baladkb I don't have demo, I just modify the source code https://hisune.com/view/1/bootstrap-multiselect-ajax-option 

if you can read Chinese.

**Comment by baladkb** [comment]
Ok @hisune, thanks.
