### ISSUE TITLE
How to get the menu to work without including the css bootstrap?

### ISSUE THREAD

**Issue by malhayek2014** [davidstutz/bootstrap-multiselect#344]
Hi,
I really like this plugin but the issue that I am having when adding the bootstrap css file it change manu things in my site.

If there a css file that has only the must have css code to get this menu to work without having to include the entire bookstrap css file?

Thanks

**Comment by delibes** [comment]
I needed the following from http://getbootstrap.com/customize/?id=ace73ef85785b529e643

Less files > Common Files : Forms
Less files > Common Files : Buttons
Less files > Components : Button groups
Less files > JavaScript components : Dropdown
jQuery plugins > Linked to components : Dropdowns

**Comment by r-a-y** [comment]
If you also need the Search filter icons, you also need:

Less files > Components : Input groups
Less files > Components : Glyphicons
