### ISSUE TITLE
JQuery Unobtrusive Validate Fix

### ISSUE THREAD

**Issue by elbro** [davidstutz/bootstrap-multiselect#347]
Unobtrusively validating using a 'required' rule or manually validating the select input using $.validate does not work as the plugin hides the raw select element, so jquery validate ignores it by default.

Fixed using the below code, would be helpful to notify users of this or include this somewhere in the plugin as an enhancement: 

var $form = $("#myForm");
var validator = $form.data('validator');
validator.settings.ignore = ':hidden:not(".multiselect")';

**Comment by mbunal** [comment]
is there any working exmaple? i cant success validating multiselect!

**Comment by mbunal** [comment]
i cant move help text under multiselect. plsease help! 
http://jsfiddle.net/5a3Labtp/

**Comment by marcelm1706** [comment]
There is an easier way to validate the multiselect checkbox:

just use this:

$('#form').validate({
        ignore: ':hidden:not("#select")',

**Comment by mbunal** [comment]
i solved what i want. working example is here: http://jsfiddle.net/5a3Labtp/6/

**Comment by harikrishna25** [comment]
How to use required tag for this

**Comment by mbunal** [comment]
**harikrishna25**: i dont know english verywell, i cant explain this. but check out following web address: [jsfiddle](http://jsfiddle.net/e0quLjqg/).

**Comment by cristianofmc** [comment]
it's return to me:

jquery.min.js:2 Uncaught TypeError: Cannot read property 'settings' of undefined at HTMLDocument. (alteracao_vinculo-ffb98a5fe2be506d764f7b3f24f76d25.js:100) at l (jquery.min.js:2) at c (jquery.min.js:2)
