### ISSUE TITLE
Tab, type, filter, move between options with arrow keys, tab-out to select

### ISSUE THREAD

**Issue by kdesigns** [davidstutz/bootstrap-multiselect#355]
I really like what Bootstrap Select (http://silviomoreto.github.io/bootstrap-select/) has done.
When you tab onto the select item, and start typing, the popup automatically opens, the focus jumps to the text input and starts filtering the options. Then you can move between options with the arrow keys without moving the focus off the text input (very handy), then when you have the desired option highlighted, you can tab-out (to the next tab option) and that option is then selected.

Tab, type, filter, move between options with arrow keys, tab-out to select.

**Comment by davidstutz** [comment]
This was working in the meantime, just fixed it to the current version. The search bar can be accessed as the first element using key up/down.
