### ISSUE TITLE
Search results while filtering are loading slow for the first time in chrome

### ISSUE THREAD

**Issue by mvenkat777** [davidstutz/bootstrap-multiselect#359]
When there are around 800 options and the following 
$('#form_pid').multiselect({
                            includeSelectAllOption: false,
                            nonSelectedText: "Select Residents",
                            enableFiltering: true,
                            enableCaseInsensitiveFiltering: true,
                            maxHeight: 350 ,
                            numberDisplayed: 0
                    });
First time , when I search for any text , it takes around a minute to get the results 
Hi david , 
  can you help me out improving performance ?

I was thinking like : can the buildFilter function in bootstrap-multiselect.js can be refined to improve performance.. 

It would be great if u can fix this..

**Comment by srikanthadepu557** [comment]
Search results while filtering are loading slow for the first time in all browsers ..
there are 9000 values in list now , below is my code snippet with multi select plugin 
Could you please suggest me a way to get faster results for my search operation in bootstrap multi select . 

------------------------------------------------------------------------------------------
$('#pid').multiselect({
        enableFiltering: true,
	enableFullValueFiltering:true,
	enableCaseInsensitiveFiltering: true,
	maxHeight: 200,
	buttonWidth: '225px',
	buttonText: function(options, select) {
	if (options.length === 0) {
	    return '-Select-';
         } else {
	     var labels = [];
              options.each(function() {
              if ($(this).attr('label') !== undefined) {
                  labels.push($(this).attr('label'));
              }
              else {
                   labels.push($(this).html());
               }
          });
          return labels.join(',') + '';
      }
  }
});
-----------------------------------------------------------------------------------------
