### ISSUE TITLE
Multiple options show active style in single select

### ISSUE THREAD

**Issue by cnanney** [davidstutz/bootstrap-multiselect#361]
Starting with a simple example:

``` html
<select id="e1">
    <option value="cheese">Cheese</option>
    <option value="tomatoes">Tomatoes</option>
    <option value="mozarella">Mozzarella</option>
    <option value="mushrooms">Mushrooms</option>
    <option value="pepperoni">Pepperoni</option>
    <option value="onions">Onions</option>
</select>
```

``` js
$('#e1').multiselect();
```

Upon initialization, Cheese is selected by default.

If I then select another via `$('#e1').multiselect('select', 'onions');`, Onions is selected with the proper background color and radio checked, but Cheese still has the background of being selected:

![image](https://cloud.githubusercontent.com/assets/195134/3850805/73f68a86-1e8a-11e4-9d82-273abd791e67.png)

JSFiddle: http://jsfiddle.net/cnanney/kpx2rvs3/

This is using the latest version 0.9.8. And by the way, can you please include the version numbers in your source files so we can easily verify what version we have, which will also help for more accurate bug reports.

Thanks.

**Comment by a13x3y** [comment]
```
 function removeFirstSelected(id){
 	var tmp = false;
 	var sel = "Choose";
 	$(id+' > option').each(function(){
 		if( $(this).attr("selected") == 'selected' )
 			tmp = true;
 	});
 	if(tmp == false){
 		if(id == "#audio")
 			sel = "";
 		$(id).next().find(".multiselect-selected-text").text(sel);
 		$(id).next().find("ul.multiselect-container li").eq(0).removeClass("active");
 	}
 }

```
Work for single select, not for multiple. 
Use: removeFirstSelected( '#your_select' );
