### ISSUE TITLE
Post Data Messed up Between Multiple Submission of Form

### ISSUE THREAD

**Issue by gudddu** [davidstutz/bootstrap-multiselect#376]
I am using Multi Select Plugin on a Form which has only one MultiSelect Input. I am seeing some random behaviour.

I am submitting the form using Ajax. For Some reason, the POSTed data does not contain all the Entries that were selected. 

Sometimes the widget indicates "4 Entries Selected" but none are received in the POST Data on the server side. 

Sometimes 3 entries are visibly seen to be selected but the widget indicates only one of them as selected. To reproduce this issue I submitted the form with two entries selected and then tried to select a third entry and I saw the issue. 

Please let me know what IC an do to overcome this problem

My form is http://dpaste.com/1WY7QD0

**Comment by VishwanathShankar** [comment]
Even I am facing the same issue..
This problem occurs after an Ajax update to the page.
I will try to create a plunker to reproduce the problem.

Thanks,
Vishwa
