### ISSUE TITLE
How to clear previously selected checkbox values in bootstrap multiselect list box

### ISSUE THREAD

**Issue by ajayvaineela** [davidstutz/bootstrap-multiselect#378]
Hi,
I am using bootstrap multiselect js for one of my requriement. It is working fine loading list box options , displaying seleted 3 options everything fine,But on the same page i have one radiobutton option. When user selects that radiobutton already selected bootstrapmulti selection will uncheck all the options and that above text what it is showing the selcted options also need to be clear and it should show nonselected. But for me i am able to unchek all previous selected listbox options, but that above text is not able to clear, still it shows the selected option names, this is my code, 
   $("#worldid").click(function() // radiobutton id
    {
    $(".multiselectboxclass").prop("checked",false); // added one class and unchekcing successfully
    $("#listboxA").html('<button data-toggle="dropdown" class="multiselect dropdown-toggle btn  btn-default" type="button">Select States <b class="caret"></b></button>');
   });

"listboxA" is the id of the div where multiselect options will load.

But here after check the radio button "nonselected" is displaying, but no listbox options or chekboxes.Every thing disappear , please help me in this regard.

Thanks in advance

**Comment by omar-faruk-sust** [comment]
i am also facing the same problem, anyone can help?
