### ISSUE TITLE
Using a button template that isn't an html button makes it impossible to update button text

### ISSUE THREAD

**Issue by RocketPuppy** [davidstutz/bootstrap-multiselect#389]
https://github.com/davidstutz/bootstrap-multiselect/blob/master/js/bootstrap-multiselect.js#L1084 requires an html button element, but the ability to configure the button template allows any element to be the "button". Using an element that isn't a button makes it impossible to update the text.

**Comment by davidstutz** [comment]
Should be fixed by now.
