### ISSUE TITLE
In Chrome the Tab out Works Incorrectly

### ISSUE THREAD

**Issue by ghost** [davidstutz/bootstrap-multiselect#403]
_Steps to Reproduce_
- Open  http://jsfiddle.net/TR49m/205/,
- Click on the first bootstrap-multiselect (Retailer = Edwin Watts),
- Press Tab,
- Press Space.

You can see that the second select is active now. In Firefox on the 4-th step the original select is still active and being opened.

_Browsers Checked_
- Firefox (win 32.0.1, OpenSUSE 31.1.0) ,  
- Chrome(win 37.0.2062.120 m, OpenSUSE 38.0.2125.101 (64-bit)). 

_Conclusion_
I believe the Firefox behaviour is correct, as this is how the native selects work in both browsers. They are at the bottom of the demo http://jsfiddle.net/TR49m/205/.
So, at least an inconsistency between the browsers is there.

**Comment by davidstutz** [comment]
I think this is obsolete, with the current version the behavior seems to be consistent across Chrome and Firefox.
