### ISSUE TITLE
Bootstrap multiselect does not work on bootstrap modal popup

### ISSUE THREAD

**Issue by dsinghrs** [davidstutz/bootstrap-multiselect#404]
Hi,
I am facing problem with the multiselectnot working on bootstrap popup. Actually this multiselect I am building as part of ajax response and then showing this response in the bootstrap modal popup. While the same multiselectworks pretty well if it is embedded in the page and getting constructed with document.ready with code something like $('#multiselect_id').multiselect(). But the same arrangement is not working with above described scenario in case of ajax. I think multiselect is not binding in cases of ajax as it binds and initializes with document ready. Any help is well appreciated.

**Comment by JoelDerrick** [comment]
I have the following issue when i put the "select" tag inside knockout "with" binding the select option doesn't properly work....i think the reason for this is the jquery function is not working inside knockout "with" binding

**Comment by IMM0rtalis** [comment]
Hey :)

following situation:
Ajaxloaded modal-content with select.

The following is working (does not matter if you type this in the console or have it in a script):
- jQuery("[name='your_select_name']").multiselect();
- jQuery(".classname").multiselect();

The following is NOT working:
- jQuery("#Id_of_select").multiselect();

I does absolutely not know why this is so...  Spend hours of finding the workaround...

Best regards from Berlin,
Florian

**Comment by kunaivi** [comment]
Hello IMM0rtalis , thanks a lot you save my three days.
it also works on my situation.

**Comment by marcellopato** [comment]
Doesn't work at all!

**Comment by vohrahul** [comment]
@IMM0rtalis Doesn't work for me. Tried both, class wise and name wise. not sure why it still doesn't work inside a modal popup when it is opened by jquery and data is loaded by ajax.

**Comment by markdalpozzo** [comment]
Most likely there is a duplicate element (i.e. the select element in the modal has the same name as an element in the parent page).
