### ISSUE TITLE
CSS change for search button glyphicon!

### ISSUE THREAD

**Issue by NidhiArien** [davidstutz/bootstrap-multiselect#409]
![test12](https://cloud.githubusercontent.com/assets/5737337/4740979/4c10570e-5a12-11e4-86ae-316c2d383efd.jpg)

Hi, 
I am using the standard example for bootstrap multiselect. My search option glyphicon's height is less than of the search text bar. I can write customized css for it, but was wondering if I have to turn on any configuration option. Also, is there a setting where I can show the drop down by default? Thank you in advance :)

**Comment by Manukam** [comment]
I have a similar issue, I'm using Jquery UI and bootstrap multi-select together. In the search bar the icon for the erase button is not showing up.
