### ISSUE TITLE
Support <options> inside and outside <optgroup> simultaneously.

### ISSUE THREAD

**Issue by ses4j** [davidstutz/bootstrap-multiselect#41]
```
<select>
<option>A</option>
<optgroup label='Group'>
<option>B</option>
</optgroup>
</select>
```

A will disappear in the above select list, because multiselect is not expecting it.

**Comment by muskokatech** [comment]
This problem still exists when using   enableCollapsibleOptGroups: true
`<script type="text/javascript">
    $(document).ready(function() {
        $('#example-enableCollapsibleOptGroups').multiselect({
            enableCollapsibleOptGroups: true
        });
    });
</script>
<select id="example-enableCollapsibleOptGroups" multiple="multiple">
   <option value="1" >Option 1</option>
    <optgroup  value="2" label="Group 1">
        <option value="2-1" >Option 2.1</option>
        <option value="2-2" selected="selected">Option 2.2</option>
    </optgroup>
    <optgroup value="3" label="Group 2">
        <option value="3-1">Option 3.1</option>
        <option value="3-2">Option 3.2</option>
        <option value="3-3">Option 3.3</option>
    </optgroup>
</select>
`
