### ISSUE TITLE
Question - Select all by default

### ISSUE THREAD

**Issue by rozatarra** [davidstutz/bootstrap-multiselect#410]
hello, it is possible to have select all checked by default and if another option/group is selected to uncheck select all? thx.

**Comment by jeffdoan** [comment]
Here is the solution:  
 $(document).ready(function() {
            $('#dropdown1).multiselect({
                includeSelectAllOption: true,
                allSelectedText: 'All Selected'
            });

            $("#dropdown1").multiselect('selectAll', false);
            $("#dropdown1").multiselect('updateButtonText');
         });

**Comment by bradhansen** [comment]
@jeffdoan Thanks, this worked perfectly.

**Comment by davidstutz** [comment]
Ok, seems to be solved, will add this to the FAQ.

**Comment by Abhilashpatnaik90** [comment]
@jeffdoan it working fine, The options are getting checked on the page load. But facing one issue where the value in the dropdown box showing "None Selected" on the page load. but when you open dropdown all will be selected then just toggle select all its start showing all selected. Can you provide a solution if any

**Comment by pcapozzi** [comment]
None of these solutions worked.

I need to build some jquery to solve this

    $(".csTsContentType").find(".multiselect-selected-text").html("All");
            $(".csTsContentType").find("input").each(function () {
                $(this).prop('checked', true)
            });

**Comment by Dav1nx1** [comment]
i solved this 

` $('#courts option').prop 'selected', true
        $('#courts').multiselect 'refresh'`

*coffee*

**Comment by NDDC** [comment]
$('#ddlColumn').multiselect('selectAll', true);
           $('#ddlColumn').multiselect('updateButtonText');

this is working perfectly in ondropdownshow method or any method but by default it didnt work

**Comment by NDDC** [comment]
since i have dynamically populated the multi select the only working solution is below
        
           var results = response;
            if (results.length > 0) {
                var columnsIn = results[0];

                for (var key in columnsIn) {
                    var col = new Object();

                    col.data = key;
                    col.title = key;
                    col.value = key;
                    col.label = key;
                    var htm = '';
                    htm += '<option selected>' + col.value + '</option>';

                    $('#dropdownname').append(htm);
                }

                $('#dropdownname').multiselect("rebuild");

**Comment by Uttam95yadav** [comment]
this one is not working for me

**Comment by NDDC** [comment]
> this one is not working for me

what is not working?

**Comment by chiko123** [comment]
> 
> 
> since i have dynamically populated the multi select the only working solution is below
> 
> ```
>        var results = response;
>         if (results.length > 0) {
>             var columnsIn = results[0];
> 
>             for (var key in columnsIn) {
>                 var col = new Object();
> 
>                 col.data = key;
>                 col.title = key;
>                 col.value = key;
>                 col.label = key;
>                 var htm = '';
>                 htm += '<option selected>' + col.value + '</option>';
> 
>                 $('#dropdownname').append(htm);
>             }
> 
>             $('#dropdownname').multiselect("rebuild");
> ```

Rebuild worked. I used it along with dataprovider options
```
$("#xyz").multiselect('dataprovider', options);
$("#xyz").multiselect('selectAll', false);
$("#xyz").multiselect("rebuild");
```
