### ISSUE TITLE
how to retain selected checkboxes on postback

### ISSUE THREAD

**Issue by dscsoft** [davidstutz/bootstrap-multiselect#418]
Hi, in serverside processing, when i submit the page, all selected checkboxes are lost. How to retain the selected checkboxex after postback? 

Thanks

**Comment by RamkiPalaniyappan** [comment]
Hi @davidstutz, @Tyf0x and @dscsoft, please check this [issue](https://github.com/davidstutz/bootstrap-multiselect/issues/835).

Thanks.
