### ISSUE TITLE
Knockout binding seems bugged

### ISSUE THREAD

**Issue by Tyf0x** [davidstutz/bootstrap-multiselect#424]
I was going through a jsfiddle (http://jsfiddle.net/TQ7eY/59/) sent in an other ticket when something got my attention: when the bound array values are overlapping (ie. [2, 3, 4, 5, 6] and [5, 6, 7, 8, 9, 10] => [5, 6]) the overlapping values are not selected, only if they are at a different position in the array.

I think the problem comes from https://github.com/davidstutz/bootstrap-multiselect/blob/master/dist/js/bootstrap-multiselect.js#L28-47

Every time the binding is changed, a list of added and deleted values is created in bootstrap-multiselect. If the knockout array of bound values contains values that moved position, the "changes" parameter will contain both a "deleted" entry AND an "added" entry. 

Because of that, the element that got moved is now in both the addedArray and deletedArray and therefore deselected (since the deselection for the deletedArray element occurs after the selection of the addedArray).

Since my knowledge of knockout is extremely limited, maybe someone using the knockout binding can confirm?

If it is confirmed, a proposed fix would be to ignore values that are moved in the array by inserting the following code between https://github.com/davidstutz/bootstrap-multiselect/blob/master/dist/js/bootstrap-multiselect.js#L29 and https://github.com/davidstutz/bootstrap-multiselect/blob/master/dist/js/bootstrap-multiselect.js#L30:
```javascript
if(typeof (change.moved) !== 'undefined'){
    return;
 }
````

Working JSFiddle: http://jsfiddle.net/TQ7eY/64/

**Comment by davidstutz** [comment]
I have merged #447. So have another try - I will not get into this any furtherthe next few weeks.
