### ISSUE TITLE
Expose $('#MyMultiSelect').multiselect('allSelectedText', response.CustomLabel);

### ISSUE THREAD

**Issue by kayday** [davidstutz/bootstrap-multiselect#427]
Can we please expose allSelectedText property to be changed like so?
$('#MyMultiSelect').multiselect('allSelectedText', response.NewCustomLabel);

I have a requirement to change this label based on another selection.  While the MyMultiSelect is not showing the dropdown, i can change it dynamically.  But once I open up the downdown, unselect all, then select all again, the old label is displayed.

**Comment by davidstutz** [comment]
FIxed in
