### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by nchafai** [davidstutz/bootstrap-multiselect#428]
Hello,

I would like to integrate i18n mechanism for the multiselect elements of a site. Your plugin offers the possibility to customize texts (setting nonSelectedText option for instance), but that's not a i18n mechanism per se ; and we have to specify this option as many times as we call `$('#my_select').multiselect()`. 

As alixaxel mentioned in #45, something similar to select2 would be great : 

> you would just have to include the file corresponding to your language and get on with it

or the possibility to override globally the options.

**Comment by davidstutz** [comment]
You areright, sooner or later this would definitely be necessary! I will think about the easiest wayt to do this.

**Comment by sangar82** [comment]
+1

**Comment by rjgamer** [comment]
Any status?

**Comment by baladkb** [comment]
Hi @davidstutz do You have any update on this [issue](https://github.com/davidstutz/bootstrap-multiselect/issues/428)?

**Comment by dalenguyen** [comment]
One of my workaround solutions is to use condition in JavaScript. 

```
var currentLang = $('html').attr('lang');

   if( currentLang === 'fr-FR' ){
        var selectOptionLang = "sélectionnés";
    }else{
        selectOptionLang = "selected";
    }

$('#your-element-id').multiselect({
        nSelectedText: selectOptionLang,
});
```

You can also apply with **nonSelectedText** and **selectAllText**.
