### ISSUE TITLE
Summarize based on text width, not hard-coded limit of 4 choices

### ISSUE THREAD

**Issue by MelGrubb** [davidstutz/bootstrap-multiselect#429]
It seems that as soon as you select 4 items, the title turns into a summary. It would be nice if this were dynamic based on the width of the text instead. I have a drop-down list of Ohio counties, and only an md-2 column to display it in. Since some counties names can be rather long (e.g. Ashtabula, Champaign, Columbiana), just selecting three of them causes the text to wrap outside of the control.

I would like to see two things.
1) The text becomes abbreviated based on whether or not it would wrap. (e.g. "3 selected")
2) A choice to simply cut off the text rather than switching to a summary (e.g. "Ashtabula, Champai...")

Since the tooltip already shows all the selected items, I think the second choice would look nice in most cases.

**Comment by davidstutz** [comment]
Would definitely be great options, I will have a look at @Tyf0x's pull request. Thanks in advance, @Tyf0x!
