### ISSUE TITLE
Unable to select multiple items using shift-key in Firefox

### ISSUE THREAD

**Issue by ddundua** [davidstutz/bootstrap-multiselect#431]
I am using FF 33.1.1 and bootstrap-multiselect 0.9.10.  When I select an item in the list, and then hold shift to select the following few items FF pops up a blank page.  I can reproduce this on an of the mutliselect examples. However, this functions fine in Chrome.

**Comment by davidstutz** [comment]
Will check this, thanks @Tyf0x.
