### ISSUE TITLE
Selected Option should be first

### ISSUE THREAD

**Issue by rushbhshah1110** [davidstutz/bootstrap-multiselect#436]
Is there any way by which i am able to make user selected option to come at top place in drop down.
Because if i have lots of values in drop down, and user will select any of these.
After that he might not able to remember that which options he had selected.
So if anyway i am able to put selected options on top of list,user will easily uncheck those.

**Comment by ckrack** [comment]
+1

add two options:
- one to run at init only (moving selected=selected up)
- one to run at runtime. to keep this fast, only when this is enabled the storage for the initial position is used.
the storage could be a selector for use with ``$.insertAfter()``, but this will fail when the sibling is moved, too.
so, option-elements need to store: ``selectorAfter`` and ``moved``.
if the sibling is moved, look for the siblings stored selector..

**Comment by ajeethkumar** [comment]
Hi,

I am trying to use   moveSelectedToTop: true and it does not seem to be working? what could be wrong?

**Comment by fgourdeau** [comment]
+1

**Comment by maimaranmurugesan** [comment]
Hi,
I want to customize the checkbox, Is there any option to add <label> or <span> after the check box ?

**Comment by sivaganeshic** [comment]
Can I get solution for this problem. Now I am facing the same problem. Someone please assist me

**Comment by 28pankaj** [comment]
I am also facing the same problem. please, guys, you have solutions for this.

**Comment by Organizer21** [comment]
+1 is this really not formally support 5 years on?

**Comment by FSGCorp** [comment]
I take it this never made it to the official multiselect repository since "moveSelectedToTop: true" doesn't work?

**Comment by jorgelf** [comment]
In case anyone is still interested in this functionality, I made a small and easy to use plugin that could fit your needs. It shows the selected items in an additional _optgroup_ listed first upon opening the dropdown. It's reloaded only when opening the dropdown, so the end user shouldn't be much confused when using it. You can check it here: https://github.com/jorgelf/bootstrap-multiselect-showselected

If people find it useful, maybe its functionality could be integrated with _bootstrap-multiselect_ itself at some point.

**Comment by davidstutz** [comment]
Thanks everyone for providing fixes and plugins to achieve the requested functionality. I considered implementign this multiple times and everytime I was facing issues with arranging this functionality with all the other features (filtering, option groups etc.). So, I decided not to officially integrate this and instead refer to @jorgelf plugin in the documentation.
