### ISSUE TITLE
Scrollbar not working in firefox 28.0 Ubuntu

### ISSUE THREAD

**Issue by dieuit07** [davidstutz/bootstrap-multiselect#445]
Scroll mouse is work fine
But can not click hold and scrap 
HOver scroll still highlight, but can not scrap

**Comment by davidstutz** [comment]
What do you mean by "click hold and scrap"? Can you give a more detailed description?

**Comment by dieuit07** [comment]
sr :) , I mean click hold and drag mouse.
Only scroll down by wheel mouse

**Comment by davidstutz** [comment]
Ok, as I understand it, I do not see how this is related to Bootstrap Multiselect ...
