### ISSUE TITLE
Incorrect bootstrap markup used with the `.checkbox` and `.radio`

### ISSUE THREAD

**Issue by M3lkior** [davidstutz/bootstrap-multiselect#451]
Hello,

I'm using bootstrap-multiselect on my projects and it seems that bootstrap-multiselect generates wrongs HTML markups for multi-select, according to bootstrap specs (and bootlint parsing ...)
Here is the result of bootlint execution on http://davidstutz.github.io/bootstrap-multiselect/#further-examples :
![image](https://cloud.githubusercontent.com/assets/5501911/5299243/7c7d5840-7bc5-11e4-8587-cbf4aa382935.png)

**Comment by davidstutz** [comment]
So in the end, sooner or later, an upgrade to the current bootstrap version will be necessary.
