### ISSUE TITLE
checkboxes displaying in random order

### ISSUE THREAD

**Issue by thienedits** [davidstutz/bootstrap-multiselect#452]
So I have an array of strings ["one", "two", "three", etc] and I loop through array creating new array with datasource of 
````
DataSource.push({ label: array[i], title: array[i], value:i+1 });
````
Then I create the multiselect dropdown, however, the checkboxes are not in the order of the datasource. I can't discern any logical order. Doesn't seem to be in alphabetical order or order of the value. I want it to be in the order of value attr.

![checkbox-order](https://cloud.githubusercontent.com/assets/2762906/5334071/c4b63246-7e3e-11e4-8338-71d99658f90b.png)

**Comment by davidstutz** [comment]
Had some problems with your fix, but now it should be working. Thanks!
