### ISSUE TITLE
Multiselect list won't appear over BOOTSTRAP Modal

### ISSUE THREAD

**Issue by OscarCrewHu** [davidstutz/bootstrap-multiselect#455]
Hi!

I'm using multiselect with bootstrap 2.3.2 inside of a MODAL.

The list won't appear over the modal, as in the picture.
![image](https://cloud.githubusercontent.com/assets/5520258/5395747/55b37eb0-8133-11e4-9b68-b686d736df55.png)

I already tried to add huge z-index to ul class="multiselect-container dropdown-menu", but it doesn't work.

Could you guys help me with that?

Thanks,

Oscar

**Comment by vigel1990** [comment]
$("button.multiselect").on("click",function(){
			$(this).parent().addClass("open");
		})
this  maybe can help you

**Comment by pablov0119** [comment]
ty
