### ISSUE TITLE
Reset button only clear the content of the select but not the title

### ISSUE THREAD

**Issue by lanner** [davidstutz/bootstrap-multiselect#456]
Hello
i have put the code to reset but the content of the names selected in the title don't refresh, only in the select is ok, the names in list stay in blue color and in the title
I use this bootstrap multiselect in 2 chained list
The first select is reset, i have put the name of the second select but nothing more
if someone have an idea
Another something strange, to make bootstrap multiselect to work i have to put the javascript code after the <select>
Thanks

Edit : 
I have found a solution here but it's for all the form, but if i just want the second select what can i have to put ?
http://stackoverflow.com/questions/26003607/bootstrap-multiselect-issue-with-form-reset-and-checkboxes-repopulating

**Comment by davidstutz** [comment]
If I understand your problem correctly, then it will be sufficient to add only the second multiselect ot the suggested event binding on `reset`.
