### ISSUE TITLE
Filter button CSS

### ISSUE THREAD

**Issue by derikb** [davidstutz/bootstrap-multiselect#458]
It looks like an oversight that the stylesheet has:

`.filter .btn{padding:6px 3px}`

instead of:

`.multiselect-container .filter .btn{padding:6px 3px}`

since all the other css rules are descendants of that container class. (I happen to be using .filter elsewhere in my page and this is causing some of my buttons to appear unusual.)

**Comment by davidstutz** [comment]
Will have a look at this. Thanks for pointing out.
