### ISSUE TITLE
Populate list if multiple option is enabled

### ISSUE THREAD

**Issue by researchlocal** [davidstutz/bootstrap-multiselect#460]
I have a problem to fill dropdown when multiselect option is enabled. Everithing is fine when I fill dropdown by calling web api if multiselect option is disabled, otherwise, there are no data.

I checked what's going on in the background.
If multiselect option is disabled, service return data and bind select element. It's work perfectly.
If multiselect option is enabled, service return data regular, but binding of select element doesn't work.

![image](https://cloud.githubusercontent.com/assets/10267975/5522988/858d83f0-89c2-11e4-8fe3-56e5c31e780f.png)

**Comment by davidstutz** [comment]
I cannot say a lot without having a closer look on your specific case. A bit more background as well as your code might help!
