### ISSUE TITLE
Multiselect data loading will slow in chrome and ie

### ISSUE THREAD

**Issue by Manivannanmani** [davidstutz/bootstrap-multiselect#461]
I have a array to load the data to multiselect. the array have an 500 data it slowly loaded.the whole application will struck some time . any idea pls share

**Comment by davidstutz** [comment]
You are loading the data using the dataprovider? I will see about that, maybe add an example. But with performance issues you are currently not alone.

**Comment by davidstutz** [comment]
It is true that using the data provider with a large number of options may be slow - I added an example but do not see an obvious solution for this issue.
