### ISSUE TITLE
.multiselect('enable') is not enable options in UC Browser

### ISSUE THREAD

**Issue by ebuster** [davidstutz/bootstrap-multiselect#462]
Calling method .multiselect('enable') enable button, but options inside drop list staying disabled.
Tested on Android UC Browser 3.4.3.532, reproduced with provided example on http://davidstutz.github.io/bootstrap-multiselect/#methods

**Comment by davidstutz** [comment]
I will try to reproduce this and figure out the error. Thanks for the report!

**Comment by davidstutz** [comment]
I could not reproduce the error on my smartphone, so I couldnot find a fix for this.
