### ISSUE TITLE
Use a custom search filter logic to handle a possible "infinite" numbers of rows inside my select.

### ISSUE THREAD

**Issue by JoMas971** [davidstutz/bootstrap-multiselect#465]
Hello and Happy New Year,

I was wondering if it is possible to use a custom search filter logic with your plugin ?

My problem is that for some reasons, it is possible that i have more than a million rows options ! It is a lot ! And i can't display all of them inside an HTML select...
So i've limited my query to 40 rows MAX, but that way, the others rows never show up then... :'-(

My idea is to use your wonderful plugin with search filter and make an ajax call with the query string to my search engine (server side) instead of searching inside the select box only, and then populate (or repopulate) my select with the new rows.

I don't know how to do it without changing your source code... So if you have an idea, i'm open to it.

Thanks in advance.

Regards .

**Comment by davidstutz** [comment]
I am afraid this will not be possible without having a close look at the source code. However, feel free to fork and make changes. Pull requests and a solution to your problem are welcome - I am sure there is someone out there having a similar issue!

**Comment by ciber0010** [comment]
Hi im trying to do same. And i need catch up when user press enter in the search field and run a query against the server.
Any idea?

**Comment by sahilchopra** [comment]
+1
