### ISSUE TITLE
Button Text overflowing in Firefox

### ISSUE THREAD

**Issue by derikb** [davidstutz/bootstrap-multiselect#467]
The text in the dropdown button (button.multiselect.dropdown-toggle) overflows the button in Firefox (I'm in v34.0), rather then getting cut off, if the text is longer than the button. Looks fine in Chrome. Looks kind of okay if you add: "overflow: hidden" to the button but the padding on the left is still off.

Appears to only be a problem if you have set the "buttonWidth" configuration option (either percentage or pixels).

**Comment by geonewlitho** [comment]
Dup' of #434 ?

**Comment by derikb** [comment]
Blah, sorry, thought I had looked but must have forgotten.
