### ISSUE TITLE
Internet Explorer 8 (IE8) getSelection Error

### ISSUE THREAD

**Issue by landreww** [davidstutz/bootstrap-multiselect#468]
Hi,
IE8 does not support getSelection() which is used in Bootstrap Multiselect v0.9.8 at line 459.  I modified the line to allow IE8 to work.

Here is the original line:
```
if (document.getSelection().type === 'Range') {
````

Here is the replacement line:
``
if ( (typeof window.getSelection != "undefined" && document.getSelection().type === 'Range') || (typeof document.selection != "undefined" && document.selection.type === "Range") ) {
``

I tested this with a mobile phone using Safari and Chrome.  Also tested with desktop IE8, IE11 and Firefox 34.  There may be a better solution but this appears allows IE8 to run without JavaScript errors.

Please consider this for future updates.

**Comment by davidstutz** [comment]
See #433. Will have a look at the proposed solution.
