### ISSUE TITLE
First One Still Selected After Using multiselect('select', 'value')

### ISSUE THREAD

**Issue by teken** [davidstutz/bootstrap-multiselect#471]
Here is an example of the problem,
![image](https://cloud.githubusercontent.com/assets/1248314/5773844/2f2cb2dc-9d5f-11e4-97a0-c4bdd4c5c1fc.png)

I have created the list from a normal select list and and used
```
.multiselect('select', 'value');
```
to select the correct value. No matter what i have tried to un-select the list item before selecting it correct one, it results in two ends either it doesn't work or it just wipes the entire list of items.

**Comment by kayday** [comment]
You need to add size="2"

<select id="myMultiSelect" size="2"></select>

**Comment by davidstutz** [comment]
Yes, definitely have a look at #129.
