### ISSUE TITLE
how to change "none selected" text

### ISSUE THREAD

**Issue by SaeedSoltoon** [davidstutz/bootstrap-multiselect#474]
hi
could you please tell me how to change "none selected" text?
i can't find it from the issues.

**Comment by davidstutz** [comment]
The option is `nonSelectedText`.

**Comment by intsfanatic** [comment]
Hi, is it possible to have the text of the first child as the nonSelectedText for each corresponding multiselect? For example here you would have a none selected text as Apple
`<select>`
`<option>Apple</option>`
`<option>Pear</option>`
`<option>Banana</option>`
`</select>`

**Comment by Sabarinathan90** [comment]
$(document).ready(function() {
        $('#id').multiselect({ nonSelectedText:'Your options heading'});
    });
