### ISSUE TITLE
how to add icon for edit and delet to the items?

### ISSUE THREAD

**Issue by SaeedSoltoon** [davidstutz/bootstrap-multiselect#475]
hi
could you please tel me how to add icon for edit and delete to the options?
i use the "i" tag inside each "option" tag. but nothings added.

**Comment by davidstutz** [comment]
I will have a look, this should be possible!

**Comment by davidstutz** [comment]
You can adapt the `optionLabel` function as follows (added to FAQ):

    optionLabel: function(element){
        return $(element).attr('label') || $(element).html();
    },

**Comment by bertdewit** [comment]
Hi,
I don't get this working. How can I get a bootstrap glyphicon in the options?

**Comment by devmi** [comment]
@bertdewit,  did you find the answer to your question?

**Comment by devmi** [comment]
Perhaps you may also set the [enableHTML](http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-enableHTML) config  to `true`
