### ISSUE TITLE
Support for option disabled property?

### ISSUE THREAD

**Issue by NetbearSoftware** [davidstutz/bootstrap-multiselect#476]
Hello,

Firstly, brilliant plugin! Thank-you.

I'm trying to programatically disable/enable options in the multiselect but it doesn't seem to support the multi select disabled option.

```
<option value="Mo" disabled="disabled">Monday</option>
```

It also doesn't appear to support it via the dataprovider object

```
  {label: 'Option 1', title: 'Option 1', value: '1', disabled: true},
  {label: 'Option 2', title: 'Option 2', value: '2'},
```

Could I be missing something or is this currently not possible?

Tim

**Comment by SaeedSoltoon** [comment]
Hi Tim.
you can simply add a css class to the option "li" tag.

var Options = $('#example-limit option').filter(function () {
                return !$(this).is(':selected');
            });
            
            Options.each(function () {
                var input = $('input[value="' + $(this).val() + '"]');
                input.prop('disabled', true);
                input.parent('li').addClass('disabled');
            });

**Comment by davidstutz** [comment]
For the dataprovider, the enabled or disabled options do currently not exist. But I will have a look at the dataprovider anyway (see #469).

**Comment by dashracer** [comment]
Is this feature added?

**Comment by davidstutz** [comment]
This was added.
