### ISSUE TITLE
add input checkbox for the optiongroups

### ISSUE THREAD

**Issue by SaeedSoltoon** [davidstutz/bootstrap-multiselect#479]
how to add input checkbox for the optiongroups when enableClickableOptGroups is true?
is it possible?
it would be so handy.

**Comment by davidstutz** [comment]
You mean adding a checkbox in front of the optgroup? This is currently not possible, however, might be helpful for users.

**Comment by RandyInVictoria** [comment]
+1 on this. Clickable optgroups are a great idea, but that functionality isn't obvious to users. A multi-state checkbox on the optgroup would clear that up.

**Comment by davidstutz** [comment]
Should be provided by the latest version.
