### ISSUE TITLE
HTML5 W3C validation failing on resulting HTML code

### ISSUE THREAD

**Issue by cosmicdust73** [davidstutz/bootstrap-multiselect#480]
The resulting HTML code includes a 'label' tag and an 'input' tag inside of an 'anchor' tag.  Both of these occurrences are reported as invalid by the W3C validation tool.  Is there any way to resolve this?  How do others handle it?  I know you can write a custom template for the output, however, I'm not sure what functionality will be lost by removing the anchor tag wrapper.

**Comment by davidstutz** [comment]
I will have a look. Originally, I intended to keep them in order to be as compatible with bootstrapas possible. But as there are new bootstrap versions out there, I might have a new look.

**Comment by davidstutz** [comment]
Closing, will think about update to Bootstrap 4 first.
