### ISSUE TITLE
Select All Checkbox

### ISSUE THREAD

**Issue by polizinha** [davidstutz/bootstrap-multiselect#481]
Hello!
I'm using includeSelectAllOption: true, but when I post multiselect with all options selected, multiselect-all option is posted too. How can I fix it without fix in every post code cause I have it in several places.

**Comment by OfficialBAMM** [comment]
Remove 'selectAllName' from your conf list.

**Comment by davidstutz** [comment]
Yes, you can adapt this using `selectAllName`.
