### ISSUE TITLE
Native browser Android (4.4.2) first item stays selected issue

### ISSUE THREAD

**Issue by nilokadnedzar** [davidstutz/bootstrap-multiselect#482]
I found an issue concerning the native brower on the Samsung Galaxy S4, Android 4.4.2.
If you take the first example on:
http://davidstutz.github.io/bootstrap-multiselect/#getting-started
... and select some items and deselect them then the first one will stay selected ( although no checker is set ) >>> see attachement

On the Chrome browser on the same device it works just fine.
On the Samsung Galaxy S3's native Browser with Anroid 4.3 it works

![stays-selected-galaxy-s4-4 4 2-native-browser-bug](https://cloud.githubusercontent.com/assets/966334/6129904/c8a8c28e-b141-11e4-874d-5b4a661822b6.jpg)

**Comment by davidstutz** [comment]
Thanks for the report. Unfortunately, thiswill be hard for me to fix, but I will have a look.

**Comment by nilokadnedzar** [comment]
... let me know if you can fix it ... otherwiese I could make a fork and go ahead  ( I have a couple of devices to test on )

**Comment by davidstutz** [comment]
Yeah, feel free to fix it yourself - haven't tried it yet, but I am currently a bit busy anyway...

**Comment by nilokadnedzar** [comment]
ok, I will take a look at the next weeks

**Comment by vincenzo34** [comment]
Hello, do you have find a solution ?

**Comment by nilokadnedzar** [comment]
I just forked the project started today the debug-ing.

**Comment by nilokadnedzar** [comment]
So far I know that it is not a representational issue but an internal one. If you look into "getSelected" and print out the length:

$('option', this.$select).filter(":selected").length

... it shows that as soon as you de-select an option in the frontend one additional is somehow added ( "option.selected" set to true ).

A phantom "$option.prop('selected', true)" might be fired somewhere or Andoid 4.4.2 has some issues concerning "prop('selected', true)" ... but I have not found something about that on stackoverflow etc.

Any suggestions?

**Comment by alessiodecastro** [comment]
I had the same bug just on Android 4.4.2 and I fixed it using .removeProp() method removes properties set by the .prop() method.
With some built-in properties of a DOM element or window object, browsers may generate an error if an attempt is made to remove the property. jQuery first assigns the value undefined to the property and ignores any error the browser generates. In general, it is only necessary to remove custom properties that have been set on an object, and not built-in (native) properties.
...
 if (checked) {
                    $option.prop('selected', true);

                    if (this.options.multiple) {
                        // Simply select additional option.
                        $option.prop('selected', true);
                    }
                    else {
                        // Unselect all other options and corresponding checkboxes.
                        if (this.options.selectedClass) {
                            $($checkboxesNotThis).parents('li').removeClass(this.options.selectedClass);
                        }

                        $($checkboxesNotThis).prop('checked', false);
                        $optionsNotThis.prop('selected', false);

                        // It's a single selection, so close.
                        this.$button.click();
                    }

                    if (this.options.selectedClass == "active") {
                        $optionsNotThis.parents("a").css("outline", "");
                    }
                }
                else {
                    // Unselect option.
                    //instead of $option.prop('selected', false); use .removeProp()
                    $option.removeProp('selected');
                }
...

@davidstutz @nilokadnedzar @vincenzo34  Let me know if for you is right, thanks.

**Comment by ccshine** [comment]
Sadly this isn't working for me.  The optgroup in question has 120 items.  When I click the header for that group it still takes 5-6 seconds for it to select all of them.  It's really quick when I "Select All" from the top of the items outside the optgroups.  Any other suggestions would be greatly appreciated!

**Comment by alessiodecastro** [comment]
@ccshine I don't think your bug is related to the issue (Android 4.4.2) in object

**Comment by ccshine** [comment]
It's not.  This was posted on the wrong thread.

**Comment by nilokadnedzar** [comment]
@alessiodecastro on the android 4.4.2 it resets the label-ing but internally still the first one stays selected.
On the other side your solution will cause problems: the last selected label stays ... on the latest versions of FF and Chrome (Mac, 10.9.5) on the desktop, see screenshot:


![bildschirmfoto 2015-06-18 um 15 13 05](https://cloud.githubusercontent.com/assets/966334/8232096/58827b9e-15cd-11e5-9957-3d0a61174529.png)

**Comment by alessiodecastro** [comment]
Hi @nilokadnedzar, I tested your considerations but luckily in my project the multiselect still works fine also on FF and Chrome (Windows), moreover on the server side the array of objects selected that I get from the selection is always correct. It's very strano, probably because I am using the boostrap multiselect version 2.0 something change????
'''
/**
 * bootstrap-multiselect.js
 * https://github.com/davidstutz/bootstrap-multiselect
 * Copyright 2012, 2013 David Stutz
 * Dual licensed under the BSD-3-Clause and the Apache License, Version 2.0.
 */
'''

![image](https://cloud.githubusercontent.com/assets/10231253/8233088/47bb96b6-15cc-11e5-9aa7-c244f559213e.png)

**Comment by davidstutz** [comment]
Closing (but adding to FAQ), open a new ticket if problem persists.
