### ISSUE TITLE
Select all when disabled by code.

### ISSUE THREAD

**Issue by OfficialBAMM** [davidstutz/bootstrap-multiselect#484]
When you use the following code:
var dropdown = $('#example-limit').siblings('.multiselect-container');
                    nonSelectedOptions.each(function() {
                        var input = $('input[value="' + $(this).val() + '"]');
                        input.prop('disabled', true);
                        input.parent('li').addClass('disabled');

You will not disable the LI which is a problem when you have select all enabled. I made a StackOverflow question and have a sort of solution for it. Though I'd share it with you guys..
http://stackoverflow.com/questions/28435253/disable-a-specific-option-boostrap-multiselect/28436118#28436118

**Comment by davidstutz** [comment]
I will think about it and add an example.

**Comment by davidstutz** [comment]
Will clarify this on the referenced StackOverflow question, and added an example (see next commits).
