### ISSUE TITLE
Minor bug in docs for reset example

### ISSUE THREAD

**Issue by scd8418** [davidstutz/bootstrap-multiselect#485]
On line 4, the statement below

$('#example-reset').on('reset', function() {

should be

$('#example-reset-form').on('reset', function() {

The example itself is correct, but the documentation code is wrong. Copying the example from the docs fails without changing the line specified.

**Comment by davidstutz** [comment]
I will have a look, thanks!

**Comment by scd8418** [comment]
Nice product. Well done, btw.

**Comment by davidstutz** [comment]
Thanks ;)
