### ISSUE TITLE
Does not work with parsely

### ISSUE THREAD

**Issue by yadongwen** [davidstutz/bootstrap-multiselect#489]
Got this error "Uncaught RangeError: Maximum call stack size exceeded"

Demo here - http://jsfiddle.net/4m3Lcm6k/3/

Please take a look. Thanks!

Best regards,
Ralph

**Comment by Tyf0x** [comment]
From the parsley doc:

>Do not add data-parsley-validate to your forms
>Please be aware that Parsley looks at all data-parsley-validate occurrences in DOM on document load and automatically binds them if valid.
>Once a form or field instance is bound by Parsley, default instantiation options cannot be easily updated, only the ones defined in the DOM would work. Which means that if this DOM validation attribute is present, doing $('#form').parsley(options); would just return the automatically bound instance, and not the one you would expect with the options you wanted to set.

see [this link](http://parsleyjs.org/doc/#psly-installation-javascript)

And [jsfiddle](http://jsfiddle.net/4m3Lcm6k/5/)

**Comment by yadongwen** [comment]
I see. Thanks very much for taking a look!
