### ISSUE TITLE
onSelectAll how to get all checkboxes value

### ISSUE THREAD

**Issue by ezekel** [davidstutz/bootstrap-multiselect#490]
HI, can I ask some help I have this configuration, How can I get all the values of checkboxes if we 
check the "select all" checkbox.

Thank you in advance.
```javascript
 $('#myselect').multiselect({
        includeSelectAllOption: true,
        enableFiltering: true,
        maxHeight: 400,
        buttonClass: 'btn btn-primary',
        buttonWidth: '150px',
        onSelectAll:function(){
             //how to get all the values of checkboxes. 
        }
		
 });		
```

**Comment by VishwanathShankar** [comment]
You can get the values by this line of code:
$('#myselect').val();

**Comment by ezekel** [comment]
@VishwanathShankar , It did not work I tried

console.log($('#myselect').val()); it returns js script
