### ISSUE TITLE
Use more than one multiselect in one page

### ISSUE THREAD

**Issue by velizarsv** [davidstutz/bootstrap-multiselect#492]
sorry, i should read more carefully ;)
<script type="text/javascript">
    $(document).ready(function() {
        $('#example-nonSelectedText').multiselect({
            nonSelectedText: 'Check an option!'
        });
    });
</script>

Verry good plugin, thanks

**Comment by davidstutz** [comment]
As you should have noticed by now, it is possible, e.g. see the documentation.
