### ISSUE TITLE
Set to enabled on rebuild when options is not empty and disableIfEmpty is true

### ISSUE THREAD

**Issue by ludo6577** [davidstutz/bootstrap-multiselect#494]
I have created an empty list with the "disabledIfEmpty" option to true. Then i append some options in the list and rebuild it as in this example:

```javascript
$.each(data, function (i, item) {
   selectControl.append('<option value="' + item.value + '" parentKey="' + item.parentKey + '">' + item.label + '</option>');
});
selectControl.multiselect('rebuild');
```

but the list stay disabled. Am i doing it wrong or is this a bug?
If it is really a bug see pull request: https://github.com/davidstutz/bootstrap-multiselect/pull/495

**Comment by davidstutz** [comment]
Tahks, merged #495.
