### ISSUE TITLE
How to use without knockout?

### ISSUE THREAD

**Issue by fdurden** [davidstutz/bootstrap-multiselect#496]
How can i use this without KnockoutJS? There's an AMD dependency on knockout but the docs don't say that it's a dependency, only talks about jquery. Didn't use to be.

Edit: To clarify, I'm using requirejs and it tries to download knockout. I don't know how to disable this or if it's even possible.

**Comment by fdurden** [comment]
To clarify, I'm using requirejs and it tries to download knockout. I don't know how to disable this or if it's even possible.

**Comment by vonnieda** [comment]
+1
0.9.11 seems to require knockout in it's definition but does not include it as a dependency. This is a breaking change for what should be a patch release and it breaks app that don't include knockout.

**Comment by fdurden** [comment]
As a workaround I solved it by doing this before the **requirejs.config(config)**:
```javascript
define('knockout', [], function(){ return undefined; });
```
This cannot be a final solution though.

**Comment by davidstutz** [comment]
I am sorry. Apparently, I did not check this - however, personally I am neither using Knckout nor Bower in practice, so always a bit hard to check ;)

Will fix this.

**Comment by davidstutz** [comment]
For now I removed require.js support. I am not using require.js or knockout.js and I prefer to wait for someone who can get both working at the same time.
