### ISSUE TITLE
BootStrap MultiSelect Issue

### ISSUE THREAD

**Issue by Prashants7945** [davidstutz/bootstrap-multiselect#499]
Hi,

I have found one issue in Bootstrap-MultiSelect listbox.

Issue:
If user has mentioned the selectAllValue: 'All' or 0 or any default value then in this case "Select All" functionality is not working properly.

For details please refer to below details:
Issue with BootStrap-Multiselect when using selectAllValue.
Steps to replicate the issue:

Step 1: Set selectAllValue property as below-

 $("#" + controlid).multiselect({
          maxHeight: 400,
          enableFiltering: true,
          enableCaseInsensitiveFiltering: true,
          filterPlaceholder: 'Search company...',
          buttonWidth: controlwidth + 'px',
          allSelectedText: 'No option left ...',
          includeSelectAllOption: true,
          selectAllValue:'0',
          filterBehavior: 'text'
        });

Step 2: Check Select All option

Step3: Uncheck any one item now:

Notice, if we uncheck anyone item then “Select All” does not get unchecked in this case.

Please let me know if we have a workaround for this. My email id is - prashants7945@gmail.com

**Comment by davidstutz** [comment]
Actually, this seems to be a bug in general, independent of the value you provide as `selectAllValue`. I will look into this.

**Comment by kayhadrin** [comment]
I just found about this issue this week. Thanks for fixing this already.

Could I suggest publishing a new release on bower for this so that everyone can benefit from it?

Currently, as a workaround, I have to reference a special git commit from bower.
