### ISSUE TITLE
XSS injection problem

### ISSUE THREAD

**Issue by briedis** [davidstutz/bootstrap-multiselect#500]
There still persists an xss injection.

Just try to edit tests, and alerts are being thrown. You can see there is added an ESCAPED string, but it is unescaped and placed in DOM as HTML:

```js
    beforeEach(function() {
        [..]
        for (var i = 1; i < 100; i++) {
            var $option = $('<option value="' + i + '">&lt;script&gt;alert(1);&lt;/script&gt;</option>');
			[..]
		}
		[..]
	});
```

**Comment by davidstutz** [comment]
Well, as I see it, this is a result of using `.html` instead of `.text` within the code. Do you have any suggestions of how to get it XSS save while being as flexible as before, i.e. stil being able to provide HTML code within an `option`?

**Comment by programcsharp** [comment]
I'd make .html vs. .text an option. Use .text by default so as to be XSS safe.

If somebody turns on .html mode, then it's their responsibility to sanitize the input to ensure it's simple markup only and no XSS is possibile.

**Comment by davidstutz** [comment]
Sounds like a really good option, thanks! Did some research and `.text` [seems to be XSS safe](http://stackoverflow.com/questions/9735045/is-jquery-text-method-xss-safe).
