### ISSUE TITLE
Various failures with HTML special characters in option values

### ISSUE THREAD

**Issue by dornstein** [davidstutz/bootstrap-multiselect#503]
Love bootstrap-multiselect.  However, it seems to have a variety of bug in how it deal with html special characters in option values.  

I tried this:

```
<select multiple="multiple">
<option>hello</option>
<option>sss &lt;this</option>
<option>&lt;this &quot; &lt; ' thato</option>
</select>
```

When I use this without the plugin, the special character all render correctly.  With bootstrap-multiselect, the displayed values are mangled (i.e., some characters aren't displayed, some items are trimmed completely, etc.).

![image](https://cloud.githubusercontent.com/assets/8538095/6806560/a7ff78ee-d206-11e4-8c62-922b08d6f907.png)

**Comment by davidstutz** [comment]
This should definitly work. Seems to be related to #500, as well.

**Comment by dornstein** [comment]
A little confused by that comment.  When you say "should definitely work" do you mean "It should work correctly but I see it doesn't and there appears to be a bug" or "It should work correctly and I can't reproduce the problem you're having so I'm not sure there's a bug"?

**Comment by davidstutz** [comment]
Sorry for the confusion. It should work, but it does not. So I realized that this is a bug. I added the `enableHTML` option which may already fix part of this problem.
