### ISSUE TITLE
Overflow in FireFox removes all text

### ISSUE THREAD

**Issue by er1c** [davidstutz/bootstrap-multiselect#508]
http://jsbin.com/livequruni/4/edit

This works fine in Chrome, but not in Firefox

**Comment by davidstutz** [comment]
So, where does this case occur in practice? I see the difference between Chrome and Firefox here, however, I do not understand why this difference does matter. Can you give a real case where this is a problem?

Btw: When I remove your CSS, then it looks as expected ...

**Comment by er1c** [comment]
I'm thinking this is probably an edge-case and more of a CSS/firefox bug rather than multiselect specific issue.  I'll close it for now, unless you have any ideas.

Here's a "mostly fixed" but the padding is still wrong change I did...not sure if its universally applicable or not (the main thing is the .caret and the width 100%):

![google chrome](https://cloud.githubusercontent.com/assets/64685/7102894/b4ab42d8-e045-11e4-9a73-296061d3db1f.png)
