### ISSUE TITLE
.multiselect('rebuild')

### ISSUE THREAD

**Issue by ianscarroll** [davidstutz/bootstrap-multiselect#509]
Hi, 

Awesome control, thank you!

We are trying to load roughly 1000 items via ajax based upon other control options the user has set on our form.  The data coming back from the server is extremely fast and clearing and adding new items to the basic select element via jquery is also fast.

Unless I've missed something, it appears I need to call .multiselect('rebuild').  This seems to be terribly slow when dealing with larger option lists; I'm assuming there is a lot of DOM manipulation going on....

What is the best (fastest) way to "re-populate" the options on a page when loading via ajax, no full page post back?  Another thing to bear in mind is that the user can go back to and change other options which will reload the select list values; again, all without a full page post back.

Thanks!

**Comment by davidstutz** [comment]
Concerning DOM manipulation, rebuilding is essentially the same as creating a multiselect from scratch - if you have a look at the code, you will notice that the constructor and the `rebuild` method are quite similar. I will add an example to the documentation and see how it works.
