### ISSUE TITLE
nonSelectedText option can no longer contain HTML

### ISSUE THREAD

**Issue by Styxxy** [davidstutz/bootstrap-multiselect#510]
Since "Merge pull request #440" (https://github.com/davidstutz/bootstrap-multiselect/commit/778c55c043ccca8e17e7e5f72826c68be42fb38d) the nonSelectedText option can no longer contain HTML formatting.

Suggestion: change the `text()` (jQuery function) back to `html()` as it was before.

**Comment by davidstutz** [comment]
Need to revise `.html` vs `.text` in the course of #500, anyway. Thanks for the note.
