### ISSUE TITLE
Q: Unable to select

### ISSUE THREAD

**Issue by bgauvey** [davidstutz/bootstrap-multiselect#511]
I have a very simple select; the checkbox is not changing state regardless of the browser.  Once I select or unselect the option, I cant change it again.  Any ideas where I went astray?

```
<script type="text/javascript">
    $(document).ready(function () {
        $('#order-state').multiselect();
    });
</script>

<select class="form-control" id="order-state" multiple="multiple">
     <option value="0" selected="selected">IN SCHEDULING (MTO)</option>
     <option value="1" selected="selected">NEW (MTO)</option>
     <option value="5" selected="selected">RUNNING</option>
    <option value="2" selected="selected">SUBMITTED (MTO)</option>
     <option value="3" selected="selected">READY TO PACK)</option>
    <option value="4">COMPLETE</option>
     <option value="6" selected="selected">AWAITING PICK ORDER</option>
</select>
```
*Note:* I have jquery v2.1.3 and bootstrap v3.3.4

**Comment by davidstutz** [comment]
For me it works perfectly with the lates version. What do you mean by "not changing state" exactly?

**Comment by bgauvey** [comment]
When I attempt yo select an item nothing gets checked, it will uncheck, but
not check

**Comment by bgauvey** [comment]
here is a small screencast.  http://screencast.com/t/4kb3ygt1iXS

Any ideas on what I may have missed?

**Comment by davidstutz** [comment]
This really looks strange, but your code looks fine and I cannot reproduce this behavior. Some information on your setup might help (version, jQuery and Bootstrap version, browser etc.).

**Comment by bgauvey** [comment]
here is the contents of my bower.json, the code is really simple.  a copy of your example.
{
  "name": "profab-orders",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.3.15",
    "bootstrap": "^3.2.0",
    "angular-animate": "^1.3.15",
    "angular-resource": "^1.3.15",
    "angular-route": "^1.3.15",
    "bootstrap-multiselect": "~0.9.12"
  },
  "devDependencies": {
    "angular-mocks": "^1.3.0"
  },
  "appPath": "app",
  "moduleName": "profabOrdersApp"
}

**Comment by avishayhajbi** [comment]
+1

**Comment by dtelaroli** [comment]
+1

**Comment by dtelaroli** [comment]
If I put onload event twice or setTimeout works.

```
$(document).ready(function() {
   $(document).ready(function() {
      $('#id').multiselect();
   });
});

$(document).ready(function() {
  setTimeout(function() {
      $('#id').multiselect();
   }, 500);
});
```

jQuery: 1.8.3
Bootstrap: 3.0.3
Multiselect: 0.9.13
