### ISSUE TITLE
Ignoring the HTML5 'required' attribute

### ISSUE THREAD

**Issue by mayeenulislam** [davidstutz/bootstrap-multiselect#515]
First of all, I appreciate the plugin, it's wonderful! :+1: 

I have a `<select>` field where I mentioned HTML5 `required` attribute: `<select required multiple="multiple">...</select>`. But when the plugin is activated it's not there. Because none of the `<input>` fields is holding the sign `required`.
### Suggestion

I can share my idea, you can implement another `hidden` input field with the `required` attribute in place, and can validate the form. But I know, you know better than me. :)

**Comment by davidstutz** [comment]
This would definitely be handy. Will think about it.

**Comment by davidstutz** [comment]
This is working now.
