### ISSUE TITLE
Overylay issue while another dropdown open

### ISSUE THREAD

**Issue by mukeshs-times** [davidstutz/bootstrap-multiselect#516]
When user click on dropdown and without choosing any option, trying to open another dropdown it should close automatically.

![overlay-issue](https://cloud.githubusercontent.com/assets/10266828/7086414/520f9f54-df9e-11e4-8972-8df5780d24e7.png)

**Comment by davidstutz** [comment]
This may actually be browser, dependent. For example, in Chrome it works within the documentation.

**Comment by mukeshs-times** [comment]
the same exist in chrome as well. For now i just removing "open" class while another dropdown gonna open, but that should not be a good way to deal with it.

**Comment by davidstutz** [comment]
Which version of chrome are you using? For me it works when opening the multiselect using mouse clicks.

**Comment by mukeshs-times** [comment]
I am using 39.0.2171.95 (64-bit) version of chrome. The issue was not related to open. It was related to auto close while another dropdown going to open. As i observed my code it might be issue related to custom js written to handle another events. This plugin works fine isolatly. So i'm going to close this bug. Thanks for your reply. Keep doing greate work :-)
