### ISSUE TITLE
ajax request

### ISSUE THREAD

**Issue by brenodp88** [davidstutz/bootstrap-multiselect#522]
Hi, I have two selects. The second select is feeded with the content of the first select using an ajax request. But I only can do this one time. If the user change the value of the first select , the second select is not changed. 

<!DOCTYPE html>
<html lang="pt-BR">
	<head>
		<meta charset="UTF-8">
		<title>Estrutura básica</title>
    
    <link rel="stylesheet" href="css/bootstrap-3.3.2.min.css" type="text/css"/>
    <script type="text/javascript" src="js/jquery-2.1.3.min.js"></script>
    <script type="text/javascript" src="js/bootstrap-3.3.2.min.js"></script>
     
    
    <script type="text/javascript" src="js/bootstrap-multiselect.js"></script>
    <link rel="stylesheet" href="css/bootstrap-multiselect.css" type="text/css"/>
		
	</head>
	<body>
    <form method="POST" action="form.php" >
      
      <select id="categorias">
        <option>Selecione</option>
        <option value="1">Categoria 1</option>
        <option value="2">Categoria 2</option>
      </select><br>
      
      <select id="example-getting-started" name="subcategorias" multiple="multiple">
      </select>
      <input type="submit" value="Enviar" />
    </form> 
	</body>
  <script>

    $(window).load(function() {
      $(document).ready(function(){
        
      $('#categorias').change(function(){
        
         var categoria_val =  $('#categorias').val();
         
         $.post('categorias.php',{'categoria':categoria_val},function(data) {
            $('#example-getting-started').html(data);
            $('#example-getting-started').multiselect();
          });      
        
      });  
      
       //
      });
    });    
  </script>
</html>

**Comment by martijnbastiaan** [comment]
Did you call `rebuild` after populating subcategorias? Could you include your AJAX-request logic?

**Comment by davidstutz** [comment]
Hard to tell without looking at your JavaScript code. As mentioned by @martijnbastiaan, `rebuild` or `refresh` might be an issue, but there might also be some problems with the AJAX.
