### ISSUE TITLE
XSS vulnerability in newest release

### ISSUE THREAD

**Issue by martijnbastiaan** [davidstutz/bootstrap-multiselect#524]
This has already been reported before as issue #500 (replicated over [here](https://hmbastiaan.nl/martijn/downloads/xss/index.html)) and has been fixed in 47110d7ec0450b2d7f8a523440680379ee4822a0. Unfortunately, this problem still persist for users of bower - which will pull a version of bootstrap-multiselect with the vulnerability.

Could you release a new version thereby allowing bower users to receive the update also?

**Comment by davidstutz** [comment]
Yes, a new release including the fix sounds good.

**Comment by martijnbastiaan** [comment]
Excellent, thanks!
