### ISSUE TITLE
Doc website is bugged out a bit.

### ISSUE THREAD

**Issue by OfficialBAMM** [davidstutz/bootstrap-multiselect#527]
Not that it's that big of a problem, but thought I'd mention it :+1:. Atleast for me i can scroll to right, which overlaps the content with the sidebar. 
http://davidstutz.github.io/bootstrap-multiselect/

**Comment by davidstutz** [comment]
Yes, noticed the same a couple of months ago but did not find a quick fix. As it is working and this is only a minor issue (that is, the documentation is still readable), it is OK for now. But if you have a quick fix, feel free to issue a pull request ;)
