### ISSUE TITLE
triggerOnChange option in select works on one element only

### ISSUE THREAD

**Issue by artyhedgehog** [davidstutz/bootstrap-multiselect#528]
When calling `.multiselect('select', values, true)` to trigger `onChange` for selected elements, it works only if value is a single element:

```
if (triggerOnChange && selectValues.length === 1) {
    this.options.onChange($option, true);
}
```

It does not seem critical to me, but it is confusing as there is no information about this singularity in documentation:

> In addition, the method provides an additional parameter: `.multiselect('select', value, triggerOnChange)`. If the second parameter is set to true, the method will manually trigger the onChange option. 

I would suggest to mention this singularity to prevent such confusion.

**Comment by davidstutz** [comment]
You are totally right. I will either mention it or fix it, thanks.

**Comment by davidstutz** [comment]
Should work by now.
