### ISSUE TITLE
multiselect onchange or onDropdownHide event code disables search in the multiselect menu

### ISSUE THREAD

**Issue by ramkisuni** [davidstutz/bootstrap-multiselect#529]
Hi,
 A very nice plugin and I am using it extensively. Thank you

Need help in one use case, I have a multiselect with "enableFiltering: true". When I add onchange or onDropdownHide event to this multiselect like below the search option in the multiselect goes away and I see only options (I am able to select and use them though).

$('#selectMyList').multiselect({
        onDropdownHide: function(event) {
        	alert("multiselect plugin");
        }
}); (or)

$('#selectMyList').multiselect({
        onChange: function(option, checked, select) {
               alert("multiselect plugin");
        }
}); 

if I add the above code, search gets removed in #selectMyList multiselect.

 For other button click events, I am able to use the multiselect with search and no issues.

my jquery version : 2.1.3
bootstrap : 3.3.4

Can you please look into this?

Thank you

with warm regards
ramki

**Comment by davidstutz** [comment]
Thanks for the report. I will have a look and at least create a demonstration. These options should not break the filtering.
