### ISSUE TITLE
Search event?

### ISSUE THREAD

**Issue by OfficialBAMM** [davidstutz/bootstrap-multiselect#530]
Is there a search event? If not, no need to reply just close it.

**Comment by davidstutz** [comment]
There is not a search event, but the option might be interesting.

**Comment by wwymak** [comment]
OfficialBAMM not sure if this will be useful for you but I use
`$(multiselectObj.siblings().find('.multiselect-search')).on('focus', function(){ stuffIwantToDoOnSearch});` for when the user clicks on the search box (and presumably start searching...)

**Comment by OfficialBAMM** [comment]
Hm, didn't work for me, although you brought me in the right direction !:)

	$(document).ready(function(){
		$($("#selEti").next(".btn-group").find('.multiselect-search')).on('input', function(){ 
			console.log('obj');
		});
	})

#selEti being my id from my multiselect.

**Comment by Rahim12345** [comment]
Hi, I use infinity scroll and append options,But I have problem when i search something then scrollbar moved and removed word in search box.How I stop it?
