### ISSUE TITLE
Is there a way to change the separator?

### ISSUE THREAD

**Issue by APM3** [davidstutz/bootstrap-multiselect#531]
I am showing a list of names...last name first.  Which means having a comma separator between each selection confuses things.  I'd like to be able to change it to a semicolon.

**Comment by APM3** [comment]
Solved this using the "buttonText" callback.  A new option for "separator" might be a handy thing to have so that you dont have to deal with all the other things that the buttonText callback has to.

Thanks for the plugin!

**Comment by davidstutz** [comment]
I will think about it, however adding even more options just parameterizing the `buttonText` option seems suboptimal.

**Comment by davidstutz** [comment]
I will see whether this option makes sense, thanks!

**Comment by davidstutz** [comment]
Reference: #539.

**Comment by APM3** [comment]
Thank you!
