### ISSUE TITLE
I can not use "[]" in the name of the element

### ISSUE THREAD

**Issue by ryznajir** [davidstutz/bootstrap-multiselect#533]
Code:

    <select name="myMultiselect[]">
        ...
    </select>

Error in web browser:

    Uncaught Error: Syntax error, unrecognized expression: #myCollapsible__repeat[]

**Comment by ryznajir** [comment]
I am sorry. It was my fault.

**Comment by ibnyusuf** [comment]
What was the issue? I seem to be facing the same problem, so am probably making the same mistake!
