### ISSUE TITLE
element.multiselect('select',value) not working in angular js

### ISSUE THREAD

**Issue by gautampaliwal** [davidstutz/bootstrap-multiselect#534]

**Comment by gautampaliwal** [comment]
![error](https://cloud.githubusercontent.com/assets/4645639/7469618/730068e4-f333-11e4-9cfa-c8dbac026054.PNG)

i am using directive of this control in my project, direct option for select is not working while i am applying this function into scope.watch(ngModel), Thanks in advance

**Comment by davidstutz** [comment]
I am not familiar with Angular JS, so I will leave this to the community. If you found a solution, please share it, and I will add it to the FAQ.
