### ISSUE TITLE
Caret stays at the center when nonSelectedText is set to empty

### ISSUE THREAD

**Issue by ghost** [davidstutz/bootstrap-multiselect#538]
Issue 1
We have a requirement where we don't want anything to be displayed in the drop down list when user doesn't select any item. So i set nonSelectedText = '' However, doing so moves the caret at the center of the drop down list. All standard drop down lists have Caret on right side.
Is there any way to set the Caret's position to the right?

I tried changing Caret class but that didn't work. I'm using 
jquery-1.11.2.js
bootstrap.js v3.0.0

Issue 2
<span class="multiselect-selected-text"></span>
the generated span element has class "multiselect-selected-text" however that class is not available in "bootstrap.css" or in "bootstrap-multiselect.css"

**Comment by davidstutz** [comment]
Have a look at the `buttonText` option. You can remove the caret in there.

Well, it may be unused, but it is included in order to allow users to apply custom styling.
