### ISSUE TITLE
Long select option bug in Chrome

### ISSUE THREAD

**Issue by ekctpemict** [davidstutz/bootstrap-multiselect#541]
Description: if i have enough long value in option of bootstrap multiselect inside small container.
It looks great in Firefox. But have a problem with Internet Explorer (v. 10) and Chrome. Text inside button does **not** overflows by "..." so we cant use it iin narrow columns

Here is my code to display problem: https://jsfiddle.net/du8b4uxr

![Looks good](https://cloud.githubusercontent.com/assets/5549570/7684960/e890725c-fd92-11e4-9fbb-64402d391be6.png)

![Bugs in IE](https://cloud.githubusercontent.com/assets/5549570/7684980/12d00b86-fd93-11e4-8f38-b931320f3950.png)

![Same bug in Chrome](https://cloud.githubusercontent.com/assets/5549570/7685001/38eb5578-fd93-11e4-84c0-35855369d764.png)

**Comment by davidstutz** [comment]
I will check this, thanks for the report.

**Comment by davidstutz** [comment]
I will add another example, however, cannot reproduce your error on Chrome or Internet Explorer 10.
