### ISSUE TITLE
Issue in Appending the Drop Down

### ISSUE THREAD

**Issue by wajahat85** [davidstutz/bootstrap-multiselect#542]
Hi,
     I have an issue relating to dropdown list. I need to append my options in the select tag of the drop down. On first attempt ,when list is appended in the select tag. The list shows up. When I try to append the options in the second time in the select tag. The list get appended in select tag but do not show up on browser. The dropdown options shows old options.

**Comment by jmccormack138** [comment]
Have you tried  $('#' + dropDownList).multiselect('rebuild');    (dropDownList being the ID of your multiselect?

**Comment by davidstutz** [comment]
According to your short description, it is hard to tell what the problem is. Could you provide some more details (code etc.)?
