### ISSUE TITLE
Enhancement request: add hook for initialization

### ISSUE THREAD

**Issue by webakimbo** [davidstutz/bootstrap-multiselect#543]
Pretty simple. Would be nice to be able to hook into an initialization event, to manipulate the widget once you know it's ready.

**Comment by davidstutz** [comment]
You mean like an `onInitialized` option? Sounds interesting. I will think about it.

**Comment by webakimbo** [comment]
Yes, exactly. Thanks for considering.

**Comment by starplanet** [comment]
I see onInitialized in master source code, but it's not in latest release version 0.9.13。I want to know when to release the feature which I see in docs.

**Comment by davidstutz** [comment]
So `onInitialized` is available in master.
