### ISSUE TITLE
Select All Value incorrectly being posted when using filter

### ISSUE THREAD

**Issue by bradleyuk** [davidstutz/bootstrap-multiselect#544]
When filtering a multiselect, if you select all of the filtered results it incorrectly includes the selectallvalue defined.

E.g. multiselect of countries, if you type 'ire' in the filter you get 'Select All' plus 'Ireland' if i then select ireland it automatically checks 'Select All' - which is find since its based on the filter. However when you post the form it includes the 'All' value i've defined for SelectAllValue. So the server thinks they chose all countries, not all of their ire filter e.g. ireland.

Anyone else had this? i checked other issues and couldn't see it.

**Comment by davidstutz** [comment]
The select all option alwys mirrors the behavior of all visible option. In addition, the select all value always get posted. Asyou already noticed, using the select all value on server side isnot reliable and not recommended.

**Comment by bradleyuk** [comment]
Ok, thanks for explaining.
