### ISSUE TITLE
Bootstrap Multiselect filter does not show close image

### ISSUE THREAD

**Issue by theraghu** [davidstutz/bootstrap-multiselect#549]
The search bar does not show the clear icon . The issue seems to be a conflict with jquery UI.
![image](https://cloud.githubusercontent.com/assets/12653550/7876099/f06c3bf4-058b-11e5-81a5-feed7afb3f19.png)

**Comment by theraghu** [comment]
![image](https://cloud.githubusercontent.com/assets/12653550/7876112/39550148-058c-11e5-886d-c40c6b5df865.png)
The fix does not use a bootstrap image. I did some css manipulation, which seems to be a workaround.
$('.multiselect-clear-filter').html("").append('<span class="ui-button-icon-primary ui-icon ui-icon-closethick"></span>');

**Comment by dinomycle** [comment]
any fix for the same,

**Comment by davidstutz** [comment]
Should not be an issue anymore.
