### ISSUE TITLE
Option to disable multi, so that only one option can be selected.

### ISSUE THREAD

**Issue by geoidesic** [davidstutz/bootstrap-multiselect#557]
I know it's supposed to be a "multi" select but I quite like the idea of using this select element throughout my site, including for normal, non-multi, select boxes.

Is this currently possible? If not then this is a feature request!

**Comment by davidstutz** [comment]
It is possible! have a look at the `multiple` option in the documentation - when omitting the multiple attribute, the multiselect switches to single select mode suign radio buttons
