### ISSUE TITLE
If their is only one option to select and it is selected it shows as all selected. 

### ISSUE THREAD

**Issue by sateeshkulla** [davidstutz/bootstrap-multiselect#558]
If their is only one option to select and when its selected it should show the selected item instead of displaying allSelectedText.
![untitled](https://cloud.githubusercontent.com/assets/1179089/8074754/1d932b3e-0eeb-11e5-9042-883d33202540.jpg)

**Comment by davidstutz** [comment]
When using the default `buttonText` option, this should already be handled. I will add an example with the next commit.
