### ISSUE TITLE
Selected values aren't interpreted correctly by Java Servlet API

### ISSUE THREAD

**Issue by stephanrauh** [davidstutz/bootstrap-multiselect#562]
I'd like to use bootstrap-multiselect in our BootsFaces project, but ran into an issue with the way you submit the selected values. The Servlet API, Tomcat or JSF don't expect multiple values with the same key in a request, so they show only one.

I solved the problem by giving each checkbox an individual name (the name of the multiselect widget plus the index number), as you can see in this [blame](https://github.com/TheCoder4eu/BootsFaces-OSP/blame/master/BootsFaces/js/bootstrap-multiselect.js). I only changed a handful of line, so expect a lot of scrolling :).

BTW, we mention you work and your license model [on our showcase](http://127.0.0.1:8080/BootsFacesWeb/forms/selectMultiMenu.jsf). Don't hesitate to tell me if there's something wrong. The showcase itself is an early developer preview, so chances are the text is a bit weird (I just copied it from another showcase page, but didn't start the final editing yet).

**Comment by davidstutz** [comment]
Just for reference, changing the names of checkboxes can also be done using the checkboxName option.
