### ISSUE TITLE
image on nonSelectedText, nSelectedText and allSelectedText

### ISSUE THREAD

**Issue by jvcunha** [davidstutz/bootstrap-multiselect#566]
You can put a picture in the text?
I tried to put a font awesome icon but could not.
Example:
   nSelectedText: 'i class="fa fa-building fa-fw"> (1)',
   allSelectedText: 'i class="fa fa-building fa-fw">',
   nonSelectedText: 'i class="fa fa-building fa-fw">',
see image:
![image](https://cloud.githubusercontent.com/assets/7241754/8195779/a2a2d6ec-145b-11e5-871b-da5f2ee70377.png)

**Comment by davidstutz** [comment]
You can always define your own buttonText in which you could programmatically add/change these elements. Using, e.g., nSelectedText for that will not work AFAIK.
