### ISSUE TITLE
onDropdownHidden , onDropdownHide is not working in bootstrap.js 2.3 version

### ISSUE THREAD

**Issue by alsh12** [davidstutz/bootstrap-multiselect#567]
Both onDropdownHidden and onDropdownHide event is not firing when using bootstrap.js 2.3 version. Is this version problem or something else?

**Comment by davidstutz** [comment]
As the documentation says, these options are not available in Bootstrap 2.3 as they are not supported by the Bootstrap Dropdown plugin.
