### ISSUE TITLE
how can i  scroll the dropdown options

### ISSUE THREAD

**Issue by raja15792** [davidstutz/bootstrap-multiselect#568]
on opening a dropdown, if there are lot of options ,, then it will usefull to have a scroller in options list,,
how can i do that ?

**Comment by rrudduck** [comment]
Something like this:

.open > .dropdown-menu {
    display: block;
    overflow-y: scroll;
    height: 400px;
}

works for me.

**Comment by davidstutz** [comment]
This should already be covered by the `maxHeight` option - have a look at the appropriate section in the documentation.
