### ISSUE TITLE
multiselect remove selected options and limit selected

### ISSUE THREAD

**Issue by Muhahe** [davidstutz/bootstrap-multiselect#574]
Hello i would like to ask if there is posibility to programaticaly trigger event that will unselect all items on select, and also if there is posibility to set how many selected options will apear in button text? Or even better if selected items will be under or showed only as number.

**Comment by davidstutz** [comment]
You can have a look at the following options and methods:

* `.multiselect('selectAll')` and `.multiselect('deselectAll')`;
* `numberDisplayed`.
