### ISSUE TITLE
Undefineds fired in onChange when (de-)selecting selectAll option.

### ISSUE THREAD

**Issue by pindab0ter** [davidstutz/bootstrap-multiselect#575]
When I click the 'Select All' option enabled with 'includeSelectAllOption: true' and catch the event with 'onChange' I get undefined on the first parameter. The second (checked) does function correctly.

**Comment by davidstutz** [comment]
I will change the behavior to not trigger `onChange` at all when selecting/deselecting the selectAll option. Only the `onSelectAll` option will be triggered.
