### ISSUE TITLE
Option to limit multiple in optgroups

### ISSUE THREAD

**Issue by jesperavot** [davidstutz/bootstrap-multiselect#579]
Hi,

Awesome plugin! However, one question occurred when I started using the plugin. Is there any option to limit multiple in optgroups?

I have a multiple select with several optgroup, users can select multiple options, but I would like to limit a specific optgroup to single select only. Basically meaning users can still select multiple options, but within this optgroup they can only select 1 option.

Thanks in advance for your answer!

Best Wishes,
Jesper

**Comment by runtim** [comment]
I have the same question for using this with optgroups and recording the order the options are selected.
I want to limit the # in each group.

**Comment by davidstutz** [comment]
I am afraid that currently this is not possible. I will think about an example ...

**Comment by davidstutz** [comment]
I added an example to the documentation that works, you might want to build on the example, see section Further Examples.
