### ISSUE TITLE
Different checkbox name for the same dropdown

### ISSUE THREAD

**Issue by hiralbalar** [davidstutz/bootstrap-multiselect#581]
Hi there,
Can you please tell me whether it is possible to change the checkbox name according to the group of data???

For example,
I have select options like below - 
Category :
Cat 1
Cat 2

Status : 
Active
Pending
Inactive

I need both in the same multiselect & I need the name of the checkboxes like
'category[]' for 'Category' group & 'status[]' for 'Status' group.

**Comment by davidstutz** [comment]
It is possible using the `checkboxName` option, see documentation (also the "Server-Side Processing" section for a good example).
