### ISSUE TITLE
Options and populating select syntax

### ISSUE THREAD

**Issue by lpredova** [davidstutz/bootstrap-multiselect#583]
### Hi

I haven't found guide anywhere but is this the best way to add options and add select values to input ?

	  $('#agency_locations').multiselect({
                    enableFiltering: true,
                    enableCaseInsensitiveFiltering: true,
                    filterPlaceholder: 'Search values...'
                }).multiselect('select', cities).multiselect('rebuild');

If it is maybe it would me good to include this in documentation ?

**Comment by davidstutz** [comment]
You do not need the `rebuild` call after selecting values.
