### ISSUE TITLE
Problem on Binding value to ListBox dynamical 

### ISSUE THREAD

**Issue by gopal0430** [davidstutz/bootstrap-multiselect#591]
Hi,
I am  trying  to bind data in ListBox dynamically but ListBox  appears normally without any check box ..is their any problem in my code?? i have followed your instruction SelectionMode="Multiple"..

my code....

<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Multiselect.aspx.cs" Inherits="Jquery_Multiselect_DropdownBox.Multiselect" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/css/bootstrap.min.css"
    rel="stylesheet" type="text/css" />
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
<link href="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
<script src="http://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js" type="text/javascript"></script>    

    <script type="text/javascript">
        $(document).ready(function () {
            BindMultiselect();
        });

        function BindMultiselect() {
            $('#lstFruits').multiselect({
                includeSelectAllOption: true
            });
        }
                    </script>

  
 
        $(document).ready(function () {

            $("#ddlSample").change(function () {
                var selectedText = $(this).val();
                $.ajax({
                    url: 'Multiselect.aspx/saveorganization',
                    data: "{ 'id': '" + selectedText + "' }",
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {
                        $('#lstFruits').show();
                        $.each(result.d, function (val, text) {
                            //$("#lstFruits").append($("<option></option>").val(value.OrgId).html(value.OrgName));
                            $('#lstFruits').append('<option value="5">item 5</option>');
                            $('#lstFruits').append('<option value="6">item 6</option>');
                            //$('#lstFruits').append($('<option>').text(value.OrgName).val(value.OrgId));
                          
                        });
                    
                    },
                    error: function (data, status, jqXHR) { alert(jqXHR); }
                });
            });

        });

    </script>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:ListBox ID="lstFruits" runat="server" SelectionMode="Multiple"></asp:ListBox>
          
    </div>
   
    </form>
</body>
</html>

---image

![jquery dynamic](https://cloud.githubusercontent.com/assets/7500782/8995123/248b18ce-372d-11e5-8bc9-bcf286c4b00d.png)

**Comment by davidstutz** [comment]
I am afraid I can't help you with that and nobody else seemed to be willing to do so ...
