### ISSUE TITLE
multiselect can not dropup automatically

### ISSUE THREAD

**Issue by mdshohelrana** [davidstutz/bootstrap-multiselect#594]
I have a simple question: a normal select toggles automatically from a dropdown list to a "dropup" list if there is room up or down the select element on the page.
For example, if a select widget is at the bottom of a page, where the browser window ends, the list is rendered up.
Is there a way to tell to boostrap-multiselect to beahave the same way?
Thank you!

**Comment by Aidurber** [comment]
Currently the only modification to how the dropdown "drops" is the dropRight option. So I'm afraid the answer is no. I might have a look tonight and see if I can find a solution for you. I might have to paste the solution here if I'm successful since I'm not sure that this repository is still being maintained.

**Comment by Aidurber** [comment]
I've developed one hack, it's buggy and it doesn't detect whether or not it should render upwards. I've added an option: flowUp (default: false)

Here is a Gist:

https://gist.github.com/Aidurber/88e63a857f4c996c8139

You will need to replace the "buildDropdown" function with the top one. 

Add the flowUp:false option at around line 320, you will see a list of options. 

It works by taking maxHeight  + 34 (height of default button) and adding a negative margin-top with the result. Must have maxHeight set. 

As I said, buggy. 

![flowup](https://cloud.githubusercontent.com/assets/5732291/9080922/fac3f4ee-3b4f-11e5-8199-b398c67c7f16.JPG)

**Comment by mdshohelrana** [comment]
@Aidurber , Thanks to your reply.

**Comment by davidstutz** [comment]
@Aidurber thanks for the solution - will integrate it with the next commits.

**Comment by pedrodgcouto** [comment]
Still having some issues with this one... :(

**Comment by Aidurber** [comment]
Hi Pedro, 

Have you gotten the latest version?

You need to use the option `dropup: true` when you initialise your multiselect. 

Full documentation here: http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-dropUp

**Comment by pedrodgcouto** [comment]
Yes, @Aidurber, got it right from the npm repository...

I've also added the option dropUp: true, but it still opens at the bottom...

**Comment by vjanssens** [comment]
@pedrodgcouto I had the same problem, the dropup option has only been committed to master and has not been released yet on the [release page](https://github.com/davidstutz/bootstrap-multiselect/releases).
@davidstutz is it possible to create a new release?

**Comment by Aidurber** [comment]
@pedrodgcouto You could always clone the repository and grab the JS file from master if it's urgent.

**Comment by pedrodgcouto** [comment]
Thanks for the suggestion. Did that and it's working fine now.

**Comment by ciber0010** [comment]
Hello, I have the same issue, anyone knows one workaround for this?

Thanks

**Comment by timdev** [comment]
I'd love this feature.  Any plans for a release that includes it?

**Comment by shijinmk2006** [comment]
when the dropdown toggle automatically to up (dropUp) and after that if collapse the groups (dropdown with multiple groups and options like tree structure) there is a blank space comes in between container and the control


![image](https://user-images.githubusercontent.com/4848814/202880174-cfa88077-e7bd-4483-ba1c-b0efe193546c.png)
