### ISSUE TITLE
issues with collapsibleOptGroups

### ISSUE THREAD

**Issue by vikasgowdaks** [davidstutz/bootstrap-multiselect#595]
whenever you select all the option under option group, the collapsible checkbox remains unchecke, and when you check on it, the options under that optGroups goes unchecked.
![collapsable](https://cloud.githubusercontent.com/assets/13660272/9086260/02fa0292-3ba1-11e5-8b50-0e1c98637590.jpg)

**Comment by Aidurber** [comment]
Do you have the latest version? 

Can you please provide me a hyperlink to that page? I can't seem to find it on the hosted page.

**Comment by vikasgowdaks** [comment]
Hosted page does not include the option "enableCollapsibleOptGroups", i could see it in the demo page present in the downloaded zip.

**Comment by Aidurber** [comment]
I can confirm this. 

Error: Uncaught TypeError: Cannot read property 'prop' of undefined Line 382
Error: Uncaught TypeError: Cannot read property 'prop' of undefined Line 357

**Comment by vikasgowdaks** [comment]
will it get fixed in the later version, could you please notify once its done? or is there a way i can work on it?

**Comment by Aidurber** [comment]
Well it looks like the repo is dead. There haven't been any updates or pull requests pulled in. I might have a look if I have time. But yes, if you fork the repo and clone it to desktop you can work on it.

**Comment by rbsevilla** [comment]
Hi Guys, is this fixed?

**Comment by Aidurber** [comment]
Doesn't seem to be, you might be better trying to fix it yourself.

**Comment by rbsevilla** [comment]
Okay, Thanks

**Comment by davidstutz** [comment]
Yes, the optgroups do not get updated appropriately. Will try to fix this with the next commits.
