### ISSUE TITLE
Add icon (Font awesome) with the text of checkbox

### ISSUE THREAD

**Issue by alibenmessaoud** [davidstutz/bootstrap-multiselect#602]
Hello, 

I am want to add font awesome icon with text of checkbox.

With the inspection tool, I arrived to add an icon : 

![image](https://cloud.githubusercontent.com/assets/760141/9254438/c84bdd70-41e3-11e5-8143-e99e0d08d8e0.png)

In my coe, I populate the select with a json array, When tried to add icon html code to the value, I got the encoded html like this  `&lt;i class=&quot;fa fa-user&quot;&gt;&lt;/i&gt;` for  `<i class="fa fa-user"></i>`
Is there any way to deal with this? Also, I want to change the background.

Thanks.

Ali

**Comment by programcsharp** [comment]
By default, items are encoded to defeat XSS injection vulnerabilities.

If you're validating the input elsewhere, you can turn on the enableHTML config setting: http://davidstutz.github.io/bootstrap-multiselect/#configuration-options.

**Comment by alibenmessaoud** [comment]
Well, thanks for the quick response, I added the option and I didn't work

var multiselect_options = [];     
            multiselect_options.push(**{'enableHTML':true}**);
            $.getJSON('http://localhost:8084/ws/available', {})
                .done(function (data) {
                    var len = data.calendars.length;                                
                    for (var i = 0; i < len; i++) {                                    
                        //'<i class="fa-exchange"></i>'
                        multiselect_options.push({
                            "label": '<i class="fa-users"></i>'+ data.calendars[i],
                            "value": data.calendars[i]
                        });
                    }
                    console.log(multiselect_options)
                    $("#available-calendars").multiselect('dataprovider', multiselect_options);

                var default_calendars = calendar.options.requested_calendars;
                var i = 0, size = default_calendars.length;
                for (i; i < size; i++)  
                    $('#available-calendars').multiselect('select', default_calendars[i]);

                    calendar.view();
                })
                .fail(function (jqxhr, textStatus, error) {
                    var err = textStatus + ", " + error;
                    console.log("Request Failed: " + err);
                });


Thanks again :)

**Comment by gekannt** [comment]
I used this approach:

            $('.filters #storage').multiselect({
                nonSelectedText: 'Тип',
                includeSelectAllOption: true,
                selectAllText: 'Все типы заказов',
                allSelectedText: 'Все типы заказов',
                enableHTML: true

            }).next().children('button').addClass('fa fa-car fa-1x');

**Comment by gekannt** [comment]
this is how the result looks: http://kagda.ru/i/e901223e951_19-04-2017-19:43:36_e901.png
