### ISSUE TITLE
Close on blur (lose focus)

### ISSUE THREAD

**Issue by emergingdzns** [davidstutz/bootstrap-multiselect#605]
Ok so we have an instance where there are two multiselects on page, one right under the other. The only way to close the multiselect it seems is to click the drop down again. But what we want is to be able to click on anything behind the drop-down to make it go away. Right now the two fields stay open.See the attached image for an example. I could not find an option for background clicking to close.

https://cloud.githubusercontent.com/assets/1017880/9319433/41f36478-4503-11e5-9d6a-23b0821bb2d9.png

**Comment by surinderrawat1987** [comment]
Any update on this ??

**Comment by davidstutz** [comment]
This is the default behavior now.
