### ISSUE TITLE
How to display the optgroup name in the textbox if the whole optgroup is selected?

### ISSUE THREAD

**Issue by hamble** [davidstutz/bootstrap-multiselect#606]
If a whole optgroup is selected, then rather than show all the individual entries in the collapsed drop-down, I'd like to see the name of the group instead. Is that possible?

So for example:

[x] Fruit
   [x] Apple
   [x] Orange
[ ] Cake
  [x] Battenburg
  [ ] Sponge

Would show "Fruit, Battenburg" in the list of selected items.

**Comment by davidstutz** [comment]
I added an example to the Further Examples section. It is not tested against all setups or use cases, but it should be the right direction:

    $('#example-optgroup-buttonText').multiselect({
        buttonText: function(options, select) {
        
            // First consider the simple cases, i.e. disabled and empty.
            if (this.disabledText.length > 0 
                    && (this.disableIfEmpty || select.prop('disabled')) 
                    && options.length == 0) {

                return this.disabledText;
            }
            else if (options.length === 0) {
                return this.nonSelectedText;
            }
                         
            var $select = $(select);
            var $optgroups = $('optgroup', $select);
            var delimiter = this.delimiterText;
            var text = '';
                                        
            // Go through groups.
            $optgroups.each(function() {
                var $selectedOptions = $('option:selected', this);
                var $options = $('option', this);
                                            
                if ($selectedOptions.length == $options.length) {
                    text += $(this).attr('label') + delimiter;
                }
                else {
                    $selectedOptions.each(function() {
                        text += $(this).text() + delimiter;
                    });
                }
            });
            
            var $remainingOptions = $('option:selected', $select).not('optgroup option');
            $remainingOptions.each(function() {
                text += $(this).text() + delimiter;
            });
                                        
            return text.substr(0, text.length - 2);
        }
    });
