### ISSUE TITLE
option like appendWidgetTo:"body"

### ISSUE THREAD

**Issue by ssjogus** [davidstutz/bootstrap-multiselect#608]
hi,

really beautiful  and useful plugin.. thanks..

I am missing one thing.. Is there any way, by which i can for the set option like -

container:''body"
or 
appendWidgetTo:"body"

Somehow this option is needed, because the selectbox container has particular height  and the outer wrapper needs the overflow:scroll. So it is hiding the selectbox.

the new bootstrap-timepicker or datepicker are providing such options.. i am looking for similar feature for the select box.

is there any way to do this?

thanks..

shruti.

**Comment by adayforgotten** [comment]
Any update here? Really need this option.

**Comment by ssjogus** [comment]
hi @adayforgotten ,

i used this script.. this works well atleast with for bootstrap dropdowns. you can try this:

```
 // DROPDOWN MENU WITH APPEND-TO-BODY
    // hold onto the drop down menu
    var dropdownMenu;
    // and when you show it, move it to the body
    $(window).on('show.bs.dropdown', function (e) {
        // grab the menu
        dropdownMenu = $(e.target).find('.dropdown-appendToBody.dropdown-menu');
        // detach it and append it to the body
        $('body').append(dropdownMenu.detach());
        // grab the new offset position
        var eOffset = $(e.target).offset();
        // make sure to place it where it would normally go (this could be improved)
        dropdownMenu.css({
            'display': 'block',
                'top': eOffset.top + $(e.target).outerHeight(),
                'left': eOffset.left
        });
    });
    // and when you hide it, reattach the drop down, and hide it normally
    $(window).on('hide.bs.dropdown', function (e) {
        $(e.target).append(dropdownMenu.detach());
        dropdownMenu.hide();
    });
//--------------------------------------------------------
```
