### ISSUE TITLE
Multiple change events firing with a value being selected/unselected (multiple select)

### ISSUE THREAD

**Issue by ismael-gonzalez** [davidstutz/bootstrap-multiselect#609]
Here is the options being passed in to the latest version:
{disableIfEmpty: true,
    buttonWidth: '100%',
    includeSelectAllOption: true,
    selectAllValue: 'all',
    enableFiltering: true,
    enableCaseInsensitiveFiltering: true}

**Comment by davidstutz** [comment]
Are you using `enableClickableOptGroups` as well? Then this might be related to #506. Otherwise, I need to check this.

**Comment by ismael-gonzalez** [comment]
it was related to #506.
