### ISSUE TITLE
Close Button

### ISSUE THREAD

**Issue by slayer1ss** [davidstutz/bootstrap-multiselect#610]
Hi, sorry to bother you... I use this at a website and some of the users complained about ul.multiselect-container not closing even they click outside, so site owner asked me to put a close button preferably something being always visible as long as ul list is visible, how can i do this? I dont mind editing core files since i wont be updating that site anymore...

**Comment by davidstutz** [comment]
Related: #605.

**Comment by davidstutz** [comment]
Closing, see #605 instead.
