### ISSUE TITLE
.multiselect('select', value) not working on dynamically added fields

### ISSUE THREAD

**Issue by omriman12** [davidstutz/bootstrap-multiselect#611]
I have my select: <select id="fields_u" multiple="multiple"></select>

I appended the fields dynamically: $('#fields_u').append(fields_html);

Start the plugin: $('#fields_u').multiselect();

Trying to select: $('#fields_u').multiselect('select', ['1', '2', '4']);

Not working... 

This worked for me when the fields where on the DOM.

Is it a known issue?

**Comment by Poky85** [comment]
I confirm this behaviour. Calling of method .multiselect('select') do nothing after <select> HTML changed. This makes plugin useless in dynamic views like those rendered by React.

You have to call .multiselect('refresh') after HTML changed which is pretty slow.

**Comment by sashtur** [comment]
I am experiencing similar issue. Is there a fix provided for the same?

**Comment by nhamnv** [comment]
I having the same problem. and i resolved by using .multiselect('dataprovider', options )

Here is my code block , it runs well
// -----------------------------------------------------------
<script type="text/javascript">
    $('#example-dataprovider').multiselect();
 
    var options = [
        {label: 'Option 1', title: 'Option 1', value: '1', selected: true},
        {label: 'Option 2', title: 'Option 2', value: '2'},
        {label: 'Option 3', title: 'Option 3', value: '3', selected: true},
        {label: 'Option 4', title: 'Option 4', value: '4'},
        {label: 'Option 5', title: 'Option 5', value: '5'},
        {label: 'Option 6', title: 'Option 6', value: '6', disabled: true}
    ];
    $('#example-dataprovider').multiselect('dataprovider', options);
</script>
<select id="example-dataprovider" multiple="multiple"></select>
// -----------------------------------------------------------

you can refer this article http://davidstutz.de/bootstrap-multiselect/index.html#methods
with on page search keyword: .multiselect('dataprovider', data)

Hope this will help you.

**Comment by McSam94** [comment]
Hi, is this problem resolved? I'm having the same issues. @nhamnv solutions can't apply to my problem because my generate multiselect and select value are on separate method.

**Comment by ravishukla007** [comment]
@nhamnv Your solution works great but it has a problem it lost the search value

**Comment by KarthiKalai7784** [comment]
1....After loading the value you need to initialize the plugin 
$('#fields_u').multiselect();
2....you already initialized the plugin before load the value you need to rebuild it
$('#fields_u').multiselect('rebuild');`
3....After the plugin intialized or rebuild it.
4.....After that select value
 $.each(array, function (i, e) {
  $("#fields_u option[value='" + e + "']").prop("selected", true);
 });
5...Finally you need to refresh after selecting the value
$('#fields_u').multiselect('refresh');

**Comment by davidstutz** [comment]
Can't fully follow anymore what the problem originally was. But this is possible with the rebuild function (see docs):

    <script type="text/javascript">
        $(document).ready(function() {
            $('#fields_u').append('<option value="2">Option 2</option><option value="3">Option 3</option>');
            $('#fields_u').multiselect();
            $('#fields_u').multiselect('select', ['3']);
            $('#fields_u_add').on('click', function() {
                $('#fields_u').append('<option value="4">Option 4</option>');
                console.log('added');
                $('#fields_u').multiselect('rebuild');
                $('#fields_u').multiselect('select', ['4']);
            });
        });
    </script>
    <select id ="fields_u" multiple>
        <option vlaue="1">Option 1</option>
    </select>
    <button id="fields_u_add">Add</button>
