### ISSUE TITLE
issue with dynamic data coming from AngularJS controller

### ISSUE THREAD

**Issue by asimnzr** [davidstutz/bootstrap-multiselect#613]
Hi David,

I have successfully used this awesome utility with static data coming from AngularJS controller, like below code, but it doest not work when data is coming from a service :
This works: Controller:
$scope.finIndsUpper = JSON.parse('[{"Key":"AverageTrueRangeIndicator","Value":"Average True Range Indicator"}]');

UI:
<select id="UIndicators" multiple="multiple" ng-options="template.Key as template.Value for template in finIndsUpper" ng-model="finIndUpper" ng-change="selectedFinIndUpper(finIndUpper)"></select>

$('#UIndicators').multiselect({
                nonSelectedText: 'None selected',
                inheritClass: true,
                numberDisplayed: 20
            });
But the issue I am facing is: When I set $scope.finIndsUpper  from a dynamic JSON object then multiselect box stays empty and says "None selected".

Can you please help me in in working around this issue?

**Comment by sanaalauddin** [comment]
I am having the same issue. Did you get any solution?

**Comment by Webinator2129** [comment]
same here, will look for alternative because is does not work in this scenario

**Comment by sanaalauddin** [comment]
I had not loaded the bootstrap.js. once I did, it was working fine.

**Comment by Webinator2129** [comment]
are you using AngularJS ng-options to populate the values? which versions if so?

**Comment by Webinator2129** [comment]
I tried using including bootstrap.min.js (Bootstrap v3.3.1) and jquery.min.js  (jQuery v1.11.2) and AngularJS  angular.min.js ( AngularJS v1.3.9) . can you attach a screenshot just out of curiosity

**Comment by sanaalauddin** [comment]
oh sorry im not using angularJS

On Sun, Sep 27, 2015 at 3:14 PM, Webinator2129 <notifications@github.com>
wrote:

> I tried using including bootstrap.min.js (Bootstrap v3.3.1) and
> jquery.min.js (jQuery v1.11.2) and AngularJS angular.min.js ( AngularJS
> v1.3.9) . can you attach a screenshot just out of curiosity
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidstutz/bootstrap-multiselect/issues/613#issuecomment-143588353>
> .
>



-- 
ثناء خان

**Comment by Webinator2129** [comment]
ok, the title of this issue refers to AngularJS,

**Comment by asimnzr** [comment]
Finally, I went for https://github.com/isteven

**Comment by Webinator2129** [comment]
can we get a definitive answer that this library does not support bootstrap multi-select options built with AngularJS **ng-options**?

**Comment by agoulart72** [comment]
Found a way to achieve this :

Set a watch on the options variable on angular that you are using as ngOption, call a refresh inside it, like this :

		$scope.$watch('myOptions', function(newValue, oldValue, scope) {
			console.log("O: ", newValue, oldValue, scope);
			// Attributes
			if (newValue.length > 0) {
				$scope.$evalAsync(function() { $('#myMutiSelect1').multiSelect(); });
				// Or : $('#myMutiSelect1').multiSelect('refresh');
			}
		});
