### ISSUE TITLE
Add option to focus search input on dropdown open

### ISSUE THREAD

**Issue by Dacesilian** [davidstutz/bootstrap-multiselect#615]
I suggest to add an option to focus search input on dropdown open. Working workaround is:

    onDropdownShown : function(event) {
    	$('#select').parent().find("button.multiselect-clear-filter").click();
    	$('#select').parent().find("input[type='text'].multiselect-search").focus();
    }

**Comment by rkhayat** [comment]
:+1:

**Comment by styfle** [comment]
:+1:

**Comment by davidstutz** [comment]
Duplicate of #615. In the meantime, added the workaround to the FAQ.

**Comment by Imekhan** [comment]
@Dacesilian great work, but if there are multiple dropdown on page then do like below:

               onDropdownShown : function(event) {
			this.$select.parent().find("button.multiselect-clear-filter").click();
			this.$select.parent().find("input[type='text'].multiselect-search").focus();
		}

**Comment by baladkb** [comment]
Hi folks, below code works for me, please check. 
```
onDropdownShown : function(event) {
setTimeout(function(){
$('#select').parent().find("button.multiselect-clear-filter").click();
$('#select').parent().find("input[type='text'].multiselect-search").focus();
}, 100);
}
```
thanks!

**Comment by UseMuse** [comment]
@baladkb thx, its work for me
