### ISSUE TITLE
Two multi select options - hide/show issue

### ISSUE THREAD

**Issue by manishamsathe** [davidstutz/bootstrap-multiselect#619]
I have converted 2 select boxes as multiselect using above plug-in. everything works fine except one part. If I open dropdown for first select box then automatically 2nd dropdown is closed (if already opened) and vise-versa.

1) I want to keep both dropdowns open and it should not affect each others.
2) An alternative solution i tried:  added 'open' for 'buttonContainer class' (btn-group open) which gives me both drop downs opened at the beginning,  but then I still need to disable dropdown hide action as otherwise above behavior crops up.

Any help is greatly appreciated.

Thanks
Manisha

**Comment by davidstutz** [comment]
You tried it in the documentation? Did you consider any collisions or problems with other libraries? Hard to tell what the problem is without some details.
