### ISSUE TITLE
Multiselect does not open/dropdown when clicked but opens with down cursor site has masterpage

### ISSUE THREAD

**Issue by kterrell32707** [davidstutz/bootstrap-multiselect#624]
I have a very simple asp.net page that was created using VS express 2015 for web. The only thing on the page is the multiselect list box and a button. If you click on the dropdown list box it does not open. If you cursor down it opens and functions properly. Checking and unchecking checkboxes work correctly. Once open, if you click on the listbox it does not close. Dropdownlist on other pages work fine. I added a Dropdownlist to the page with the multiselect listbox. The dropdownlist opens when clicked.

I am using a MasterPageFile, but there are no controls on the master page. I have bootstrap.css, bootstrap-min.css, bootstrap-theme.css, bootstrap-theme.min.css, bootstrap-multiselect.css and site.css.

When I remove the MasterPageFile hooks and just use body and Form tags in place of the Content tags, the multiselect works correctly. The multiselect list is not on the masterpagefile.

Any suggestions to resolve?
Thanks KT

**Comment by davidstutz** [comment]
I am not familiar with the technologies you use, so I am afraid I can't help you.

**Comment by Mahender999** [comment]
@davidstutz  I have used dropdownlistFor instead of Select when i clicked on the button "none Selected" it does not open the dropdown.
