### ISSUE TITLE
CDN availability of this library

### ISSUE THREAD

**Issue by settysreekanth** [davidstutz/bootstrap-multiselect#630]
Hi, Could you please add this project to any CDN's like JSDelivr or cloudfare or any other cdns?

**Comment by davidstutz** [comment]
Related: #369

**Comment by jefffriesen** [comment]
@davidstutz I think this ticket and #369 can be closed.

https://cdnjs.com/libraries/bootstrap-multiselect contains several versions, including the latest 0.9.13.
