### ISSUE TITLE
NuGet package incomplete

### ISSUE THREAD

**Issue by patrickracicot** [davidstutz/bootstrap-multiselect#634]
I don't know if this is actually wanted, but the NuGet package for bootstrap-multiselect does not "install" itself inside a solution.  So when I added it to my project the sources where correctly pulled in the packages folder but the sources (.css, .js) where not "installed" (placed in the respective folders) inside my project.  This is not a major issue since I actually have the sources in the package folder, but this will mean that for each update that I will pull with NuGet, I will have to manually replace the source files in my project.

**Comment by tiesont** [comment]
It looks like the last two packages were updated incorrectly (unless there's something I'm missing in the nuspec file). The most recent version that will work with the default MVC templates is https://www.nuget.org/packages/Bootstrap.Multiselect/0.9.10 - not sure if that helps at all.

**Comment by patrickracicot** [comment]
No problem, I currently use the latest version 0.9.13 and manually added.  Will this get fixed on the next package release?

**Comment by nbelley** [comment]
Should we consider the nuget way not supported anymore and add it manually?

**Comment by davidstutz** [comment]
OK, did not notice this. Could someone tell me the right way of setting up the NuGet package? Personally, I am not using it myself.

**Comment by tiesont** [comment]
It looks like you left out the top-level Content directory, which needs to be there in order for the path into the web project to work. If you want the Css and Less directories to be placed into the web project's Content folder, you need

Content > Content

Or, in other words, a second level Content directory. The top-level is just there to hold the assets to be copied over.

I personally follow the Bootstrap project's lead, and place the CSS file directly in the web project's Content folder. So, the contents of the  package file are

Content > Content > mycssfile.css
Content > Scripts > myjavascriptfile.js

I use the [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer), which should warn you if you just try to drop the files directly into the package (and offer to create the top level Content).

**Comment by tiesont** [comment]
@davidstutz If you like, I can fix the package for you. I imagine you'd have to add me as a admin to the package. 

It *is* worth noting that Microsoft/Outercurve really wants NuGet to be reserved for binary packages; the idea is that scripts/plugins like this should live in Bower, npm, etc. I personally don't agree with that, but you could make the argument that the NuGet package needs to be retired.

**Comment by gradexpert** [comment]
Hi there can i add a second column in front of the item like this
![classesddl](https://cloud.githubusercontent.com/assets/25625867/24127969/d0a7fbae-0e2c-11e7-968a-150f7dde270b.png)

**Comment by tiesont** [comment]
@gradexpert Add a new issue. Your question has nothing to do with this issue.

**Comment by gradexpert** [comment]
My bad i actually wanted to know something relevant here.. I have uninstalled version 0.9.13 since it did not add .css and .js files to my solution..
now where can i get these files to add them manually in my project (i downloaded the project but it doesn't have bootstrap-multiselect.css or bootstrap-multiselect.js)
i cannot go for older version like 0.9.10 since i am using latest versions of bootstrap and jquery

**Comment by tiesont** [comment]
Look a little harder, then. The files are in the dist folder.

**Comment by gradexpert** [comment]
yes i found them thanks :)

**Comment by winterlude** [comment]
Why such an easy bug to fix has not already been solved? This issue was opened 3 years ago!
Do we have to consider the NuGet plugin dead?

**Comment by davidstutz** [comment]
Current version will be available on NuGet after NuGet finishes indexing.
