### ISSUE TITLE
Fire event only after all selections/deselections are done in multiselect optgroup dropdown

### ISSUE THREAD

**Issue by khushirathi** [davidstutz/bootstrap-multiselect#635]
Is there a method or event in this plugin which will be fired only after I completed selecting/deseleting my options in a multiselect dropdown with optgroup setup.
I cannot use 'onChange' as it's getting fired after every selection and deselection and calling server methods everytime.
Basically, I want to fire an event or call a method when drop down collapses once user clicks outside the dropdown. (Multiselect dropdown will be hidden only after user click outside of that).
I read about method 'ondropdownhide' but I cannot use it as I'm not using bootstrap 3.
Any suggestions how to achieve this?

**Comment by davidstutz** [comment]
Related: #506

**Comment by davidstutz** [comment]
Do you mean an event fired after selecting deselecting ALL options within an optgroup? Or rather when the optgroup's input is selected/deselected?
