### ISSUE TITLE
Arbitrary text in select + filtering

### ISSUE THREAD

**Issue by alshopov** [davidstutz/bootstrap-multiselect#636]
This is a great plugin. Thank you for providing it!
My question/request for enhancement is somewhat similar to #465 - is it possible to enter free style text when the plugin is filtering?
As the plugin tries to model the select/option input - one can only select one or more predefined options. This works very well for referential types however sometimes one wants to be able to also include arbitrary values in case no predefined value is exactly what needed. Is there any way to achieve that?

Kind regards:
al_shopov

**Comment by davidstutz** [comment]
I think the plugin is not intended for this kind of use-case. But I guess you are able to find other plugins for doing this ;)
