### ISSUE TITLE
Retain checkbox selection after loading different parts of webapp

### ISSUE THREAD

**Issue by nicolecvaldez** [davidstutz/bootstrap-multiselect#641]
Hi,

I am very new to bootstrap and flask and this may come across as a very simple question. I just need help on how I can retain the selections I have made with the multiselect(located in a sidebar) even if I am going through different parts of the page.

I apologise if this is not the right venue to ask this. Any information or direction as to where I should be looking for answers is greatly appreciated.

Thanks,
Nicole

**Comment by davidstutz** [comment]
I am not familiar with flask, so I can't really help you.
