### ISSUE TITLE
Why do you use an `a` element if the action is attached to `label`?

### ISSUE THREAD

**Issue by FezVrasta** [davidstutz/bootstrap-multiselect#648]
This is insane, why do you use the `a` element and put inside it the `label` element?

The action is on `label`, so the `a` is just useless and creates confusion.

**Comment by programcsharp** [comment]
Bootstrap standard: http://getbootstrap.com/components/#btn-dropdowns

**Comment by FezVrasta** [comment]
Bootstrap doesn't put a label inside the anchor, anchors without any meaning are useless and can lead to a lot of problems when one uses a modified CSS.

**Comment by programcsharp** [comment]
Sure it does: http://getbootstrap.com/css/#checkboxes-and-radios

**Comment by FezVrasta** [comment]
No way, bs doesn't put checkboxes in dropdowns

**Comment by FezVrasta** [comment]
I'm sharing with you something happened on our project:

We styled the anchors of the dropdowns (all the bootstrap dropdowns) to have some padding, in this way the clickable area is larger (it was the requirement).

The problem is that doing that, added a padding between the `<a>` and your `<label>`. People clicking on the gap experienced a bug: the click event wasn't lost (this because they were clicking on the anchor and not on the label.

I'm sure this is a very common case.

**Comment by FezVrasta** [comment]
Looking in the issues list I have found this:
https://github.com/davidstutz/bootstrap-multiselect/issues/626
which is exactly the same problem, there's even a PR open to fix it, but I think it would be much better to get rid of the `a` or the `label`

**Comment by davidstutz** [comment]
I mostly agree with @programcsharp. The current construction stems from exactly the fact mentioned: dropdown needs a `li > a` structure, and checkboxes need a `label > input` structure, the combination of which is currently implemented in Boostrap Multiselect. However, I also see that this is probably not the best way to do it.

I will have a look at the PR to fix #626, but I do not see a reason to change the structure as it is not the most urgent issue. @FezVrasta You are however welcome to suggest a change after which the plugin still works as expected.

**Comment by FezVrasta** [comment]
Just to add something else wrong with your implementation.

`label` and `input` are not allowed to be child of `a` elements by W3C standards.

**Comment by davidstutz** [comment]
Yes, that's correct. Still, I would follow the Bootstrap way. Maybe this can be avoided with Bootstrap 4.
