### ISSUE TITLE
onSelectAll Fires Event on Load

### ISSUE THREAD

**Issue by redwall007** [davidstutz/bootstrap-multiselect#650]
The `onSelectAll` event fires when the multiselect component is first initialized which is causing me a headache. It should only fire when toggling the select all checkbox.

Is there a quick fix for this available?
```
onSelectAll: function() {
// this fires when component is initialized, should only fire when toggling the select all checkbox
}
```
Thanks Red

**Comment by furukama** [comment]
Agree, some option would be great to exclude running onSelectAll on initializing.

A quick fix is to use a initializing variable:

$(document).ready(function() {
var initialized = 0;
...
onSelectAll: function() {
   if (initialized) {
      // normal code for the select all action here
   }
   initialized = 1;
}
}

This way, the select all code doesn't get executed the first time.

**Comment by mbeara** [comment]
I have even weirder behaviour, onSelectAll fires on every initialization only after I click all options for the first time... And I really need refresh after onSelectAll so I get infinite refresh.. :dart:

**Comment by davidstutz** [comment]
Ok, I will look into it. This behavior should be avoided or at least documented.

**Comment by philwig** [comment]
Dealing with the same issue here, can work around it. If you have "select all" ticked, the event fires always. If it is not checked to start with, behaviour is as you'd expect.

**Comment by mmattdugan** [comment]
For me onSelectAll is fired when I click the 'clear search' button.. It does not fire when I click the 'Select All' option. I have a group of multiselects on the same page.

**Comment by lokjaiswal12** [comment]
Now onSelectAll is not working anymore.

**Comment by dorian07s** [comment]
I have a solution for this issue :
Add line 638 : 
this.updateSelectAll();
this.options.onChange($option, checked);

After this, the refresh is OK.

**Comment by dorian07s** [comment]
After adding my solution, i have a bit problem with multiselect.
When i select 'Select All' option, in a multiselect, the work is good, but all my 'Select All' in all multiselect are checked (just the chekbox, not all options, and 'Select All' is not blue). 
It's a strange problem.

**Comment by davidstutz** [comment]
Now, neither `onSelectAll` nor `onDeselectAll` should be triggered on initialization/page load (both if some or all options are selected and when no option is selected). Also added tests.
