### ISSUE TITLE
Sort the options in Ascending or descending manner

### ISSUE THREAD

**Issue by alaksandarjesus** [davidstutz/bootstrap-multiselect#654]
Hi,

How do i sort the populated data in ascending or descending order.

**Comment by alaksandarjesus** [comment]
,I used this in multiselect() and my console.log output is sorted. But the dropdown is remains the same.
					 onDropdownShow: function(event) {
						 	
						 dropdownListItems = $($($(event.target)[0].innerHTML)[1].innerHTML);
			              
			                for(var j = 0; j < dropdownListItems.length; j++){
			               for(var i = 0; i < dropdownListItems.length-1; i++){
			    
			                	if($(dropdownListItems[i]).text() > $(dropdownListItems[i+1]).text()){
			                		temp = dropdownListItems[i];
			                		dropdownListItems[i] = dropdownListItems[i+1];
			                		dropdownListItems[i+1]=temp;
			                	}
			                	
			                }
			                }
			              
			               for(var i = 0; i < dropdownListItems.length; i++){
			                	
			                	console.log($(dropdownListItems[i]).text());
			                }
			              
			            }

**Comment by davidstutz** [comment]
Where exactly did you add this code? After calling `.multiselect`?

**Comment by alaksandarjesus** [comment]
I solved the issue by javascript sort before passing to multiselect. Thanks for the response.
