### ISSUE TITLE
Missing proxy for onSelectAll trigger

### ISSUE THREAD

**Issue by naomap** [davidstutz/bootstrap-multiselect#657]
When defining an 'onChange' trigger function, <this> is set up as the Muliselect object which is handy. However when defining a trigger for 'onSelectAll', <this> is set up as the options used to create the Multiselect - which is much less handy ;-)

It seems that the following line is missing in the Multiselect constructor :
this.options.onSelectAll = $.proxy(this.options.onSelectAll, this);

Regards,
Antoine.

**Comment by davidstutz** [comment]
Will have a look and integrate fix, thanks for noticing.

**Comment by davidstutz** [comment]
Fixed.
