### ISSUE TITLE
Creating an option that does not have a checkbox and acts as a link?

### ISSUE THREAD

**Issue by mattloniero** [davidstutz/bootstrap-multiselect#658]
I'm creating a multiselect dropdown that has multiple options for topics of a post, but want to add an option to add a new topic that would act as a link to another page rather than as a checkbox.

**Comment by davidstutz** [comment]
Will try to add a simple example to the docs and see how to solve this.

**Comment by mroeling** [comment]
I have used the onChange option for that:

>         onChange: function(option, checked, select) {
>             location.href = '/?p=' + option[0].value;
>         },
