### ISSUE TITLE
How to pass parameters correctly using 'dataprovider' 

### ISSUE THREAD

**Issue by rliibke** [davidstutz/bootstrap-multiselect#661]
Hi Guys,

I'm trying to pass the option parameter 'maxHeight' to multiselect using 'dataprovider'.

When using the 'normal' select field works fine, example:

 $('#select_field').multiselect({
        includeSelectAllOption: true,
        enableFiltering: true,
        enableCaseInsensitiveFiltering: true,
        maxHeight: 200
    });

But other field i'm using groups. then i do like the example in 'http://davidstutz.github.io/bootstrap-multiselect/'

`var optgroups = [ { label: 'Group 1', children: [{label: 'Option 1.1', value: '1-1', selected: true}, {label: 'Option 1.2', value: '1-2'}, {label: 'Option 1.3', value: '1-3'} ] }, { label: 'Group 2', children: [{label: 'Option 2.1', value: '1'},{label: 'Option 2.2', value: '2'},{label: 'Option 2.3', value: '3', disabled: true}]}];`

`$('#select-group-field').multiselect('dataprovider', optgroups);`

So how i pass options parameters to multiselect ?

I'm try many different things like:

`var opt = { maxHeight: 200 };`

`$('#select-group-field').multiselect('setOptions', opt);`

or 

` var opt = { maxHeight: 200 };`
` $('#select-group-field').multiselect(opt);`
`$('#select-group-field').multiselect('dataprovider', optgroups);`

**Comment by davidstutz** [comment]
maxHeight cannot be passed using the data provider. The data provider does only support the options mentioned in the documentation.

**Comment by GianpietroColosio1971** [comment]
I try to pass options   through an hidden field where in codebehind I created the array of options.
 <script type="text/javascript">
        function GaugesOptions() {
            $('#gaugeoptions').multiselect({
                buttonWidth: '400px',
                enableFiltering: true,
                enableClickableOptGroups: true,
                enableCollapsibleOptGroups: true,
                collapseOptGroupsByDefault: true
            });
            var gaugelist = document.getElementById('<%= hfgaugeoptions.ClientID %>').value;
 $('#gaugeoptions').multiselect('dataprovider', gaugelist);
                       
        }
But I always get a noone selected and an empty multiselect.
It seem it doresn't recognize my data as an array object even if it has been built exactley with the described format.
In console I get this error: SCRIPT5007: SCRIPT5007: Invalid operand to 'in': Object expected
jquery-3.4.1.js (502,2)
Could you help?

Could you help me in understand the problem?

**Comment by KBRajeshMCA** [comment]
Hi @rliibke , 

Please Refer this Below URL.

https://stackoverflow.com/questions/29176558/cant-define-options-on-bootstrap-multiselect-inputs-when-using-dataprovider-m?answertab=votes#tab-top.

var options = [
  {label: 'Option 1', title: 'Option 1', value: '1'},
  {label: 'Option 2', title: 'Option 2', value: '2'},
  {label: 'Option 3', title: 'Option 3', value: '3'},
  {label: 'Option 4', title: 'Option 4', value: '4'},
  {label: 'Option 5', title: 'Option 5', value: '5'},
  {label: 'Option 6', title: 'Option 6', value: '6'}
];

$('#example-dataprovider').multiselect('dataprovider', options);
var selectconfig = {
    enableFiltering: true,
    includeSelectAllOption: true
};
$('#example-dataprovider').multiselect('setOptions', selectconfig);
$('#example-dataprovider').multiselect('rebuild');
