### ISSUE TITLE
IE8 : Expected identifier, string or number

### ISSUE THREAD

**Issue by rafs250** [davidstutz/bootstrap-multiselect#669]
Hi, I'm using IE8 (with jQuery 1.11.1) and I'm having this error : 

Expected identifier, string or number (on line 1430).  Seem that for IE8 'class' is a reserve word.  I'm right ?

Thanks

**Comment by rafs250** [comment]
No answer ???

**Comment by Darrel-Viegas** [comment]
I commented that line (line no 1430) and it worked in my case.

**Comment by davidstutz** [comment]
merged #713.
