### ISSUE TITLE
Searching the same query twice doesn't work

### ISSUE THREAD

**Issue by EoinGriffin-AI** [davidstutz/bootstrap-multiselect#670]
In a typeahead, enter a search term (It's super effective!).
Close the dropdown and open it again.
Enter the same search term (No effect!)

**Comment by davidstutz** [comment]
For me (in Google Chrome and Firefox), the search term stays inside the filter after closing and reopening the multiselect (and the corresponding options are filtered correclty). So to re-enter the same search term you have to remove and re-add at least one character which will re-filter the options correctly.

Can you give more precise instructions on reproducing this issue?

**Comment by EoinGriffin-AI** [comment]
I see. You're right that it does as you describe. I think the issue is happening because we're doing something non-standard with this library by re-sorting the options.
In our case we're using the multi-select feature, and when we close the dropdown the options get re-sorted (using `element.multiselect('dataprovider', sortedOptions);`) so that the selected options are at the top. The 'dataprovider' method clears the search term.

Our solution for re-sorting the options is a total hack. It would be ideal have a better way to sort that would (a) preserve the search term, (b) preserve which options are selected, and (c) minimize the re-creation of DOM elements for better performance.
As it is now I'll need another hack to re-enter the search term programatically.

This technically isn't a bug though since sorting the options isn't a supported feature.

**Comment by davidstutz** [comment]
Thanks for the update. If you come up with a solution, feel free to share an example. I am suresorting the options might be interesting for other users.
