### ISSUE TITLE
Allow to search remote content (AJAX)

### ISSUE THREAD

**Issue by antonini** [davidstutz/bootstrap-multiselect#671]
Hi,

I was trying to use this component in a way that when user types any character it filter the content remotely (AJAX) and show the filtered result on the dropdown.
This behaviour is supported on [select2 component](https://github.com/select2/select2) but IMHO your component have a better look and feel and other functions that I'm going to use.

Is it possible?

**Comment by davidstutz** [comment]
I am currently not considering to add this feature. However, feel free to add a pull request if you come up with a working solution.

**Comment by jimmyyujy** [comment]
Hi @davidstutz , seems like there was a pull request
https://github.com/davidstutz/bootstrap-multiselect/pull/122/files
Do you know the reason why it wasn't merged in?
Thanks

**Comment by davidstutz** [comment]
I guess it couldn't be merged automatically, will add it the the FAQ.
