### ISSUE TITLE
Why does onSelectAll function is triggered when nothing is selected?

### ISSUE THREAD

**Issue by kbokdia** [davidstutz/bootstrap-multiselect#673]
I have list of options. When I click select all, it triggers onSelectAll function. How do i check if all options were selected or deselected?

**Comment by davidstutz** [comment]
Oh, the documentation seems to miss this detail (although the example already implements it):


    $(document).ready(function() {
        $('#example-onSelectAll').multiselect({
                includeSelectAllOption: true,
                onSelectAll: function(checked) {
                alert('onSelectAll triggered: ' + (checked ? 'selected all' : 'deselected all') + '!');
            }
        });
    });
