### ISSUE TITLE
Jinja2 + AngularJS + bootstrap-multiselect integration issue

### ISSUE THREAD

**Issue by Webinator2129** [davidstutz/bootstrap-multiselect#676]
Jinja2 and AngularJS uses same syntax for templates *{{ }}* therefore in order to avoid this conflict would changing AngularJS template syntax as following 

```
 myapp.config(['$interpolateProvider', function($interpolateProvider) {
     $interpolateProvider.startSymbol('{[');
         $interpolateProvider.endSymbol(']}');
   }]);
```

now AngularJS alone works fine as shown in this [Plunker example](http://plnkr.co/edit/zA4XhEUt17ZoQOSHGYNK?p=preview)

I got the feeling as if the integration with AngularJS is expecting the **{{}}** if though the app have been configured to **{[]}** therefore the multiselect is not working 

<img width="472" alt="screen shot 2015-12-19 at 23 43 53" src="https://cloud.githubusercontent.com/assets/1534356/11916569/71d4f630-a6aa-11e5-8975-59431133b230.png">

**Comment by davidstutz** [comment]
I am not familiar with Jinja2 and AngularJS, but I will leave this open for others.
