### ISSUE TITLE
3000 Records - Building Multiselect is slow!

### ISSUE THREAD

**Issue by rkhayat** [davidstutz/bootstrap-multiselect#677]
Hello, 
First off, I LOVE your component, it fits every need I throw at it. I have an edge case of a drop down with 3000 records, building the drop down takes about ~6-11s, any recommendations?

**Comment by Aidurber** [comment]
There is a pull request #399 which replaces the default way of binding (on load) to when the dropdown is opened. 

If you wanted to implement this, just fork this repository and pull in that Pull Request into your own fork. 

That might help page performance, you will still face issues when you open the drop down. From my experience there isn't much you can do here, @davidstutz  might have some better suggestions. But you will have issues binding 3000 elements to anything.

**Comment by davidstutz** [comment]
Related to #672.
