### ISSUE TITLE
enableCollapsibleOptGroups prevents onChange behaviour change, so it still runs multiple times for the group

### ISSUE THREAD

**Issue by ant-s** [davidstutz/bootstrap-multiselect#679]
When enableClickableOptGrops is enabled it changes the behaviour of onChange from firing once for each element in the group to firing once for the whole group, with all affected options passed as the first parameter. This is good and documented behaviour (see third example here: http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-enableClickableOptGroups).

Enabling enableCollapsibleOptGroups breaks this behaviour, causing onChange to fire once for each item in the optgroup. An example of this can be seen in this fiddle: http://jsfiddle.net/L4nrh2bz/. Removing the 'enableCollapsibleOptGroups: true' restores the correct behaviour. 

Thank you David for creating such a great and flexible plugin. I wish I had the js skills to fix this!

**Comment by davidstutz** [comment]
I will look into this, this should be fixed or at least documented.

**Comment by ant-s** [comment]
Thanks David!

**Comment by davidstutz** [comment]
Added tests, should be fixed.
