### ISSUE TITLE
Unable to customize the checkbox

### ISSUE THREAD

**Issue by maimaranmurugesan** [davidstutz/bootstrap-multiselect#681]
Hi, 
I want to customize the checkbox, Is there any option to add < label > or < span > after the check box ?
Please let me know if any other option.

Thanks,
Manimaran

**Comment by davidstutz** [comment]
Have a look at the templates:

    templates: {
        button: '<button type="button" class="multiselect dropdown-toggle" data-toggle="dropdown"><span class="multiselect-selected-text"></span> <b class="caret"></b></button>',
        ul: '<ul class="multiselect-container dropdown-menu"></ul>',
        filter: '<li class="multiselect-item filter"><div class="input-group"><span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span><input class="form-control multiselect-search" type="text"></div></li>',
        filterClearBtn: '<span class="input-group-btn"><button class="btn btn-default multiselect-clear-filter" type="button"><i class="glyphicon glyphicon-remove-circle"></i></button></span>',
        li: '<li><a tabindex="0"><label></label></a></li>',
        divider: '<li class="multiselect-item divider"></li>',
        liGroup: '<li class="multiselect-item multiselect-group"><label></label></li>'
    }

You can adapt the `templates.li` template (the checkbox input is added to the `label` of `templates.li` uisng jQuery's prepend)..

**Comment by seever123** [comment]
Can we get a better explanation please? I'm trying to customize the checkboxes also. @maimaranmurugesan understood right away but I've been tinkering with the templates but its not working.
