### ISSUE TITLE
buttonTitle & buttonText ignore delimiter length

### ISSUE THREAD

**Issue by mabgfounder** [davidstutz/bootstrap-multiselect#683]
I had a problem where the last character was being dropped off the displayed button text/title after users selected an option in the multiselect. The problem turned out to be that when the `delimiterText` option was set to "," (string containing a single coma) the last character was being dropped off. For example:

    <html>
    <head>
        <link rel="stylesheet" type="text/css" href="/Content/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="/Content/bootstrap-multiselect.css" />
    </head>
    <body>
        <form>
            <select class="form-control form-control-multi" id="Foos" multiple="multiple" name="Foos">
                <option value="101">ABC0015/101</option> 
                <option value="103">ABC0016/102 </option> 
                <option value="106">BC0017/103</option> 
            </select>
        </form>
    
        <script type="text/javascript" src="/Scripts/jquery-2.1.4.min.js"></script>
        <script type="text/javascript" src="/Scripts/bootstrap.min.js"></script>
        <script type="text/javascript" src="/Scripts/bootstrap-multiselect.js"></script>
    
        <script type="text/javascript">
        $('#Foos').multiselect({
            delimiterText: ',', // changing this to a string with length = 2 works around the problem
        });
        </script>
    </body>
    </html>

I believe the proper fix is to have the multiselect's buttonTitle and buttonText use the delimiter.length instead of a hard coded 2. Here is a patch that I think will correct the problem.

    Index: bootstrap-multiselect.js
    ===================================================================
    --- bootstrap-multiselect.js	(revision 191)
    +++ bootstrap-multiselect.js	(working copy)
    @@ -263,7 +263,7 @@
                             selected += label + delimiter;
                         });
                         
    -                    return selected.substr(0, selected.length - 2);
    +                    return selected.substr(0, selected.length - delimiter.length);
                     }
                 },
                 /**
    @@ -285,7 +285,7 @@
                             var label = ($(this).attr('label') !== undefined) ? $(this).attr('label') : $(this).text();
                             selected += label + delimiter;
                         });
    -                    return selected.substr(0, selected.length - 2);
    +                    return selected.substr(0, selected.length - delimiter.length);
                     }
                 },
                 /**
    

This is my first issue report on GitHub. I apologize if formatting is messed up.

**Comment by mabgfounder** [comment]
I just noticed the revision numbers in the patch. Those are for the project I am planning to use multiselect in. They have no relation to the multiselect repository.

**Comment by davidstutz** [comment]
Thanks for the note,will add the fix!

**Comment by davidstutz** [comment]
Fixed.

**Comment by TexasSwede** [comment]
I am having that same problem now, a year later. The last character of the last selected item is cut off, both in the button itself and if I hover over it.
![multiselectmissingcharacter](https://cloud.githubusercontent.com/assets/3178455/26233355/61a49c0c-3c22-11e7-8b31-c5228f3d0aec.png)

I am using the example code straight off the page: 
```
$('#example-getting-started').multiselect({
       buttonClass:"btn btn-link",
       includeSelectAllOption: true,
       delimiterText: ';'
});
```
I also tried using  **delimiterText: "\n"** and getting the same result.

**Comment by shuhratjan** [comment]
@TexasSwede Have you solved this problem? if yes, could you share with solution way?
