### ISSUE TITLE
disabled multiselect

### ISSUE THREAD

**Issue by lucasgoiaba** [davidstutz/bootstrap-multiselect#684]
How i can enabled multiselect?
I try:
$('#combo_pecas').prop('disabled',false);
$('#combo_pecas').removeAttr('disabled');
document.getElementById("combo_pecas").disabled = false;

tanks

**Comment by davidstutz** [comment]
Have a look at the [`.multiselect('enable')`](http://davidstutz.github.io/bootstrap-multiselect/#methods) method.
