### ISSUE TITLE
Knockout binding update method

### ISSUE THREAD

**Issue by mvelasco83** [davidstutz/bootstrap-multiselect#685]
Hi, 

Im no expert, but after looking around for a bug that would not take in the options defined in the multiselect binding when using the knockout binding i found that on line 154 which says:

var config = ko.toJS(valueAccessor());

it should be:

var config = ko.toJS(allBindings());

This fixed the issue i mentioned for me, which was that i could not set the options such as dropRight etc...

Thanks!

**Comment by Aaron-P** [comment]
Do you have an example of your usage of the binding? There shouldn't be any need for it to access the entire knockout model if it's being use properly.
