### ISSUE TITLE
Select only single whole group

### ISSUE THREAD

**Issue by eckimchi** [davidstutz/bootstrap-multiselect#687]
I would like to have an optgroup which only allows the selection of one entire group. User's cannot unselect any options in that group, individual options cannot be selected, and only one group can be selected.

Is this possible?

**Comment by davidstutz** [comment]
I will try to create an example, but I am not sure if this is possible that easily.

**Comment by davidstutz** [comment]
I guess it is easier to not have groups but list the sub-options in the groups label. I will look into allowing HTML in the options value/text, see #602 and #668.
