### ISSUE TITLE
Issue with IE8 and making a mouse selection

### ISSUE THREAD

**Issue by u01jmg3** [davidstutz/bootstrap-multiselect#696]
- I believe there is a problem with IE8 and the ability to select a dropdown value with the mouse. In the GIF below I attempt to make a selection with the mouse but my clicks are not registered. I then have to use the keyboard keys and the <kbd>Enter</kbd> key to make a successful selection.

--

- Sourced the issue to be within the following handler.
  - I have included a simplistic solution which could be expanded on.

```js
$('li a', this.$ul).on('touchstart click', $.proxy(function(event) {
    //...
    if($('.ie8').length > 0){
        event.preventDefault();
        $target = $target.find("input");
        $target.prop("checked", !$target.prop("checked"));
        $target.click();
    }
    //...
}, this));
```

--

- IE8 Demo

![demo](https://cloud.githubusercontent.com/assets/1266205/12746667/c2b6cc1c-c997-11e5-9369-f2c0f0d2a8dc.gif)

**Comment by davidstutz** [comment]
I will have a look, thanks for the report and fix.

**Comment by davidstutz** [comment]
merged #713.

**Comment by u01jmg3** [comment]
@davidstutz: will you releasing a new version (`v0.9.14`) any time soon so I can pull in this change and others via bower?

**Comment by u01jmg3** [comment]
@davidstutz: 2b9a5fd does not fix the issue I reported - in IE8 option dropdowns are still not selectable. Furthermore, the use of `option.class` causes a compilation error in IE8.
