### ISSUE TITLE
cannot disable 'clickable' option groups when using collapsible option groups?

### ISSUE THREAD

**Issue by pgoldweic** [davidstutz/bootstrap-multiselect#699]
When using 'enableCollapsibleOptionGroups', I can't seem to disable 'enableClickableOptionGroups'. In other words, the option groups are always clickable, contrary to the behavior that I'd like to achieve. Thanks in advance for looking into this.

**Comment by davidstutz** [comment]
Will look into this, but i might be intended that way as far as I remember the corresponding PRs.

**Comment by pgoldweic** [comment]
Thanks!
