### ISSUE TITLE
bootstrap-multiselect add css to parent of selected checkbox?

### ISSUE THREAD

**Issue by curvedb** [davidstutz/bootstrap-multiselect#700]
The only way I found is to edit the plugin like that:

`if (this.options.selectedClass) {
    if (checked) {
        $target.closest('li').addClass(this.options.selectedClass);
        $target.closest('li label').addClass('label-selected'); //ADDED THIS LINE
    }
    else {
        $target.closest('li').removeClass(this.options.selectedClass);
        $target.closest('li label').removeClass('label-selected'); //ADDED THIS LINE
    }
}`

**Comment by davidstutz** [comment]
Yes, this is not possible using the plugin options. I will add this to the FAQ, though.
