### ISSUE TITLE
Validation with Angular JS not working

### ISSUE THREAD

**Issue by aravindantapmobi** [davidstutz/bootstrap-multiselect#701]
I'm using this plugin and angular js in my application, but i'm not able to do my angular js validations in the multi select dropdown. Any idea how it can be done ? 
This is my code.
`<select id="subrole" class="inversed dropdown multiCheckbx triggerTab" multiple="multiple"  multiselect-dropdown required>
    <option value="Singer" class="singer" id="singer" href="singer"> Singer </option>
</select>
<input type="text" name="subrole" class="inversed " ng-model="subrole" required/>
<div ng-messages="contact.subrole.$touched && contact.subrole.$error">
<div ng-message="required" class="hgtinpu errormessage">This field is required</div></div>`

**Comment by davidstutz** [comment]
I am not familiar with Angular JS, but I will leave this open for others.

**Comment by homer2** [comment]
@aravindantapmobi how did you get this to work with Angular?
