### ISSUE TITLE
<pre>tag is closed unexpected at index.html Line 450

### ISSUE THREAD

**Issue by YouthLin** [davidstutz/bootstrap-multiselect#703]
https://github.com/davidstutz/bootstrap-multiselect/blob/gh-pages/index.html#L450  

![qq 20160215211912](https://cloud.githubusercontent.com/assets/6056413/13049745/06ea6cbc-d42a-11e5-83e3-459c2f84ee15.png)
  
  
![qq 20160215212333](https://cloud.githubusercontent.com/assets/6056413/13049925/2f435cfe-d42b-11e5-887a-6baa30dfbc11.png)

**Comment by davidstutz** [comment]
Will include the referenced fix.
