### ISSUE TITLE
Destroying multiselect w/prop disabledIfEmpty does not remove disabled attribute from select

### ISSUE THREAD

**Issue by jazanne** [davidstutz/bootstrap-multiselect#705]
I'm having an issue that my multiselect gets destroyed/re-initiated depending on another form element. 

Scenario:
disabledIfEmpty: true and a multiselect is in fact empty and disabled
-User changes input, thus the above multiselect is desultory, the select/option list is rewritten, and a new multiselect is initiated, even though the new select list is NOT empty, the dropdown continues to be disabled.

I worked around this in my code by doing

$('#myMultiselect').('destroy').removeAttr('disabled');

However, it seems like when a multiselect is destroyed that maybe it should automatically re-enable the select.

**Comment by jmvtrinidad** [comment]
Can you provide a test case?

**Comment by davidstutz** [comment]
Will look into it.
