### ISSUE TITLE
Uncaught SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by tomaskikutis** [davidstutz/bootstrap-multiselect#706]
https://github.com/davidstutz/bootstrap-multiselect/blob/master/dist/js/bootstrap-multiselect.js#L1430

$tag = $('<option/>').attr({
	value: option.value,
	label: option.label || option.value,
	title: option.title,
	class: option.class, // <--- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
	selected: !!option.selected,
	disabled: !!option.disabled
});

**Comment by davidstutz** [comment]
Duplicate of #669. Will look into it.

**Comment by davidstutz** [comment]
Merged #713.
