### ISSUE TITLE
selectAllJustVisible is not Deselecting everything

### ISSUE THREAD

**Issue by Sithugo** [davidstutz/bootstrap-multiselect#707]
Hey, 
i set the following options:
enableFiltering: true,
includeSelectAllOption: true,
selectAllJustVisible: false

If you search for something from the list, you can select and deselect every element from the whole list.(not just the visible ones).
The Problem is: If you search for a word, which isn't  contained in the list, it is possible to select everything, but you can't deselect anything. 

Is this a bug, or am i doing something wrong?

**Comment by davidstutz** [comment]
Will create an example to check.

**Comment by vedicsociety** [comment]
We have faced this bug here:

http://sanskritdictionary.com/frequency/

It would be wonderful if it could be resolved. Thank you!

**Comment by davidstutz** [comment]
Added tests for this case, but it still seems to be working. Can you detail setup and browser etc.?

**Comment by davidstutz** [comment]
Can someone confirm that this issue still exists?

**Comment by Sithugo** [comment]
As i do not have access to the server where i implemented the multiselect tool, i cannot test it there, but i visited the website of vedisociety and it seems to be fixed there. Thank you :)
