### ISSUE TITLE
deselect/select doesn't work with search when value is typed in search

### ISSUE THREAD

**Issue by Abhilash3** [davidstutz/bootstrap-multiselect#711]
Hello,

        select.multiselect('deselect', 'foo');

fails when we have search enabled and searched 'foo', relevant code:

        getInputByValue: function (value) {

            var checkboxes = $('li input', this.$ul);
            var valueToCompare = value.toString();

            for (var i = 0; i < checkboxes.length; i = i + 1) {
                var checkbox = checkboxes[i];
                if (checkbox.value === valueToCompare) {
                    return $(checkbox);
                }
            }
        },

This method, gets the first checkbox (actually first input, even search), and when an option's value is equal to the text written in search then the above method returns the search box instead of the actual checkbox.

Thank you.

**Comment by davidstutz** [comment]
I will check this, this should not happen, Thanks for reporting.

**Comment by Abhilash3** [comment]
Probable fix:
          var checkboxes = $('li input:not(.filter)', this.$ul);
tested it on my environment, seems to be working :)
