### ISSUE TITLE
nonSelectedText is ignored when disableIfEmpty is true

### ISSUE THREAD

**Issue by cwalv** [davidstutz/bootstrap-multiselect#714]
Using these options:
```javascript
$el.multiselect({
    disableIfEmpty: true,
    disabledText: 'Loading ...',
    nonSelectedText: 'None Selected'
})
```

I would expect `buttonText` to be `'Loading ...'` iff the multiselect is disabled, and `nonSelectedText` to be used if it's not disabled and no items are selected.  Currently, if `disabledText` and `disableIfEmpty` are set, `nonSelectedText` is ignored.

**Comment by davidstutz** [comment]
Will look into it and the corresponding PR, thanks!

**Comment by davidstutz** [comment]
Merged #715.

**Comment by mustafasalahuldin** [comment]
Why new implementation still has the conflict (v0.9.16)?

**Comment by tiesont** [comment]
The latest release is v1.1.1 - https://github.com/davidstutz/bootstrap-multiselect/releases/tag/v1.1.1.

**Comment by mustafasalahuldin** [comment]
Thanks @tiesont, but I guess this releas doesn't support bs < 4, does it?
