### ISSUE TITLE
angular 2 ngFor loop for options not working

### ISSUE THREAD

**Issue by smgjreinieren** [davidstutz/bootstrap-multiselect#716]
Iam trying to loop trough an array i created to set the options it is working until i am calling the .multiselect() method. Is there anyone with the same problem and a solution? 

```
 <select id="test" multiple="multiple">
        <option *ngFor="#test of checks">{{test}}</option>
    </select>
```

This is my html template to test it. It is conflicting i don't know why please help me out!

**Comment by davidstutz** [comment]
I am not familiar with Angular JS, but I will leave it open for others.

**Comment by danishin** [comment]
@smgjreinieren you should call `$("#test").multiselect()` inside `AfterViewInit` so that options are done populated by angular
