### ISSUE TITLE
Question about code sample for limiting # of selected options

### ISSUE THREAD

**Issue by pwinant** [davidstutz/bootstrap-multiselect#717]
In your code sample with the description "Limit the number of selected options using the onChange option.", you have the following line of code:

`var dropdown = $('#example-limit').siblings('.multiselect-container');`

But you never do anything with that "dropdown" variable. Was it intended to be used to filter the jQuery selector on the next line?

**Comment by davidstutz** [comment]
I will have a look - not sure what I was thinking when I wrote this line.
