### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by legshooter** [davidstutz/bootstrap-multiselect#719]
Hi,

Approx. half a year with no updates, I was wondering - is this still being maintained?

Thanks

**Comment by istrau3** [comment]
+1

**Comment by davidstutz** [comment]
Yes and no. I try to have a look at least once a semester (i.e. once each 6 month), but I am pretty busy with my studies. So if anyone is interested in maintaining this project more actively, help is very welcome.
