### ISSUE TITLE
Wrong path for main file in package.json

### ISSUE THREAD

**Issue by istrau3** [davidstutz/bootstrap-multiselect#721]
There is an entry:
```javascript
"main": "dist/bootstrap-multiselect.js"
```
where it should be:

```javascript
"main": "dist/js/bootstrap-multiselect.js"
```

**Comment by davidstutz** [comment]
Will fix it.

**Comment by sharang-d** [comment]
Seems to be fixed https://github.com/davidstutz/bootstrap-multiselect/blob/master/package.json#L5
Am I looking at the correct place @istrau3 ?

cc: @davidstutz

**Comment by istrau3** [comment]
@sharang-d Yeah, that is the right place. Is that version up on npm?

**Comment by sharang-d** [comment]
No idea. I just checked the source, sorry!

**Comment by sharang-d** [comment]
> @sharang-d Yeah, that is the right place. Is that version up on npm?

If it is not then only @davidstutz can fix(publish) it 😄 
I thought it was a simple text change in which case I would've taken it up!

**Comment by davidstutz** [comment]
No the current master is not up on npm, will do this with the next release.
Also in: #667
