### ISSUE TITLE
Many large but equal multiselects - a way to avoid unnecessary set up. 

### ISSUE THREAD

**Issue by UrKr** [davidstutz/bootstrap-multiselect#722]
I'm working on a page with many multiselects which have one of three sets of options. It turns out the bottleneck to loading the page is all the .multiselect() calls. Is there a way to pass an existing element, which has already been converted to bootstrap-multiselect and just copy it instead of re-computing everything?

That would be the most convenient due to the way the page was made when I started on it, but other alternatives are welcome too.

Thanks!

**Comment by davidstutz** [comment]
I will have a look whether this is easy to accomplish.

**Comment by UrKr** [comment]
Thank you - it is still relevant for me.

**Comment by davidstutz** [comment]
Will probably not follow up on this.
