### ISSUE TITLE
Using grouping features with knockout

### ISSUE THREAD

**Issue by razaali20** [davidstutz/bootstrap-multiselect#728]
(Updating my initial question) I am able to see the groups in multiselect with the following code, however, only if I place a breakpoint in the custom-binding init, apparently after the data has been loaded and rendered. I am sure there is a more proper way of getting groups working.

```
 <select class="multiselect" multiple="multiple" data-bind="selectedOptions: selectedModels, foreach: models, multiselect: multiSelectInitOptions2">

    <optgroup data-bind="attr:{label: Model}">

        <option data-bind="value: value, text: Model"></option>

    </optgroup>

</select>
```

Please advise. Thanks

**Comment by razaali20** [comment]
This is where I am so far:

`    ko.bindingHandlers.multiselect2 = {

        init: function (element, valueAccessor, allBindingsAccessor, viewModel, context) {
            var bindings = valueAccessor();
            var optionsObservableArray = bindings.options;
            optionsObservableArray.subscribe(function (newObservableArray) {

                if (newObservableArray && newObservableArray.length > 0) {

                    if (element.comboBoxInitialised) {
                        return;
                    }

                    element.innerHTML = "<optgroup data-bind='attr: {label: $data.label}, foreach: $data.items'><option data-bind='value: " + bindings.optionsValue + ", text: " + bindings.optionsText + "'></option></optgroup>";

                    ko.applyBindingsToNode(element, { foreach: bindings.options });

                    $(element).multiselect(bindings.multiSelectInitOptions);
                    element.comboBoxInitialised = true;
                }
            });
        }
    };`

Now I need to take care of updates. Note that the expected data structure is [{label: 'groupname', items:[{....}]}]

**Comment by davidstutz** [comment]
I am not familiar with knockout, but will leave this open for a while to discuss.
