### ISSUE TITLE
enableFilter aren't match for first letter

### ISSUE THREAD

**Issue by ans-4175** [davidstutz/bootstrap-multiselect#729]
Hey I'm following your documentation and trying to use `enableFilter` but looks like it won't works for first letter

```
<select id="example-getting-started" multiple="multiple">
                            <option value="cheese">Cheese</option>
                            <option value="tomatoes">Tomatoes</option>
                            <option value="mozarella">Mozzarella</option>
                            <option value="mushrooms">Mushrooms</option>
                            <option value="pepperoni">Pepperoni</option>
                            <option value="onions">Onions</option>
                        </select>
```

```
$('#example-getting-started').multiselect({
                includeSelectAllOption: true,
                selectAllText: 'Check all!',
                enableFiltering: true
            });
````

I try to find `tomatoes` it wasn't found, but when I type `omatoes` it was found.
So I guess, first letter weren't checked.

**Comment by baladkb** [comment]
Hi @ans-4175, please use below code

$('#example-getting-started').multiselect({
            includeSelectAllOption: true,
            selectAllText: 'Check all!',
            enableCaseInsensitiveFiltering: true,
            enableFiltering: true
        });

**Comment by ans-4175** [comment]
Okay, will do. Thanks @baladkb
