### ISSUE TITLE
Collapsible options not working even on the api documentation examples page

### ISSUE THREAD

**Issue by razaali20** [davidstutz/bootstrap-multiselect#730]
I tried on Firefox and Chrome to click on the collapsible groups in the examples, but they don't collapse.

I mean the following:
http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-enableCollapsibleOptGroups

How can I get this to work?

By the way, thanks for the great library.

**Comment by razaali20** [comment]
I added the following to my stylesheet and it's working now:

       .multiselect-collapsible-hidden {
         display: none
      }

**Comment by davidstutz** [comment]
Yes, sorry, my fault - was changing a lot on clickable/collapsible optgroups and was too eager with the commits. Is fixed now.
