### ISSUE TITLE
Select All can not tagger the onChange function

### ISSUE THREAD

**Issue by gclinux** [davidstutz/bootstrap-multiselect#731]
$("#slt_car").multiselect({
            buttonClass: 'btn btn-default btn-no-left',
            buttonContainer: '<div class="btn-group" />',
            enableFiltering: true,
            buttonWidth :'100%',
            includeSelectAllOption: true,
            selectAllText: "Select All",
            onChange:function(element, checked){
                console.log(element, checked);
            })
//.....

when i click select all ,the function  onChange do not run

**Comment by dericeira** [comment]
#733 Check this out.

**Comment by Leo-lion** [comment]
Hi derceira, can  you please help me out why select all option is not showing in dropdown list.. Is it known issue?? Thank you for your help.

**Comment by davidstutz** [comment]
You should use `onSelectAll` in this case.
