### ISSUE TITLE
onSelectAll is firing when I click the 'clear search' button

### ISSUE THREAD

**Issue by doganmeh** [davidstutz/bootstrap-multiselect#732]
onSelectAll is firing when I click the 'clear search' button (ironically).. It does not fire when I click the 'Select All' option. I have a group of multiselects on the same page.

    <div id="filter-div" class="text-center" style="display:none;">
        <select id="set" class="multiselect" multiple="multiple"></select>
        <select id="subject" class="multiselect" multiple="multiple"></select>
        <select id="demographic" class="multiselect" multiple="multiple"></select>
        <select id="grade" class="multiselect" multiple="multiple"></select>
        <select id="level" class="multiselect" multiple="multiple"></select>
    </div>

    <script>
    $('#filter-div')
            .find('select')
            .each(function (index, value) {
                $(this).multiselect({
                    includeSelectAllOption: true,
                    selectAllValue: 'select-all-value-' + index,
                    disableIfEmpty: true,
                    nonSelectedText: 'Filter ' + this.id + 's',
                    numberDisplayed: 1,
                    enableFiltering: true,
                    enableCaseInsensitiveFiltering: true,
                    enableFullValueFiltering: false, // searched term might be in the middle of word
                    onChange: function (option, checked, select) {
                        console.log('Changed : ' + $(option).val())
                    },
                    onSelectAll: function () {
                        console.log('onSelectAll triggered.')
                    }
                })

                $(this).multiselect('dataprovider', options[this.id])
            })
    </script>

**Comment by davidstutz** [comment]
Will try to reproduce and fix it.

**Comment by davidstutz** [comment]
Can you confirm that this issue still exists? Added a test case but cannot reproduce the problem.

**Comment by doganmeh** [comment]
I will, please give me some time. Thanks,

**Comment by davidstutz** [comment]
Thanks.

**Comment by doganmeh** [comment]
Nope. I downloaded the latest version from github and everything worked fine. Thanks!
