### ISSUE TITLE
Have any options for fixed Search box(filter) ? 

### ISSUE THREAD

**Issue by baladkb** [davidstutz/bootstrap-multiselect#734]
Hi,
I have used the [bootstrap-multiselect](https://github.com/davidstutz/bootstrap-multiselect/) Library, it's use full for me thanks :+1:  and if do You have any options for fixed Search box(filter) when drop-down options scrolling.

**Comment by baladkb** [comment]
Hi @davidstutz, Did You had a chance to see this issue?

**Comment by OfficialBAMM** [comment]
See issue: #396

**Comment by baladkb** [comment]
Okay thanks @OfficialBAMM

**Comment by baladkb** [comment]
@davidstutz any updates for fixed Search box(filter)?

**Comment by davidstutz** [comment]
Closing, see #396 instead.
