### ISSUE TITLE
Dropdown in modal z-index issue

### ISSUE THREAD

**Issue by aliusa** [davidstutz/bootstrap-multiselect#743]
Dropdown shows behind modal shadow.

![screenshot_96](https://cloud.githubusercontent.com/assets/9768908/15447089/9e3fa150-1f3d-11e6-90ac-d8854a3026af.png)

**Comment by aliusa** [comment]
Managed to find temporaty solution

`.jBox-content {
    overflow: visible!important;
}`

**Comment by aliusa** [comment]
How it look after CSS change.

![screenshot_97](https://cloud.githubusercontent.com/assets/9768908/15447448/61885366-1f4b-11e6-8036-681c5423078b.png)

**Comment by Flekyno** [comment]
Hi where did you get the class "jBox-content". I tried to applay the style init but it does not work.

**Comment by aliusa** [comment]
I'm using jBox, jQuery plugin for modals.
https://github.com/StephanWagner/jBox
