### ISSUE TITLE
Undocumented feature!  Disable allSelectedText by setting it to false.  Please document

### ISSUE THREAD

**Issue by brucejo75** [davidstutz/bootstrap-multiselect#746]
Love this package!

I was trying to get rid of the `allSelectedText` because I want all the selections to be the button text even when they are all chosen.  I think this will meet the needs of [https://github.com/davidstutz/bootstrap-multiselect/issues/466](https://github.com/davidstutz/bootstrap-multiselect/issues/466)

So I set it to false in the configuration options:
```
{
  'allSelectedText': false,
...
}
```
now `allSelectedText` is disabled and the label is the list of all selected options!
### Suggested change for the docs
Change first sentence [here](http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-allSelectedText):
from:
> 	The text displayed if all options are selected.

to:
>	`allSelectedText` is the text displayed if all options are selected.  You can disable displaying the `allSelectedText` by setting it to `false`.

Maybe add an example?

**Comment by davidstutz** [comment]
Sounds good, will add this.
