### ISSUE TITLE
Multi Dropdown selectAll option issue

### ISSUE THREAD

**Issue by bhumiradixweb** [davidstutz/bootstrap-multiselect#751]
Hello,

If use multiple select box in a page with select all true, when tick one selectall option of dropdown ,it ticks all the drop-down selectall checkbox.

And this bug on line:

`$('li input[value="' + this.options.selectAllValue + '"]').prop('checked', true);`

which selects all dropdown values. change it to

`$('li input[value="' + this.options.selectAllValue + '"]', allLis).prop('checked', true);`

Same for Deselect too.

Thanks
Bhumi Shah

**Comment by dorian07s** [comment]
Thanks for this correction.
For more information, it's at line 1339 and 1384.

**Comment by oafd86** [comment]
not working for me still having the same problem after fix

**Comment by lmcarreiro** [comment]
There are two pull requests for it: #742 #753

**Comment by gedarius** [comment]
Hello, i solved it with the line below:

$('div.btn-group.open li input[value="' + this.options.selectAllValue + '"]').prop('checked', false);

**Comment by davidstutz** [comment]
Thanks, will merge.
