### ISSUE TITLE
Natural required attribute not working.

### ISSUE THREAD

**Issue by marcelgruber** [davidstutz/bootstrap-multiselect#755]
Hi friends,

Can anyone think of a reason why this functionality wouldn't be working?

The error message is "An invalid form control with name='location_preference[]' is not focusable."

Using the latest version of Chrome.

Much appreciated,

Marcel

**Comment by davidstutz** [comment]
See also #620.

**Comment by marcelgruber** [comment]
Addressed in issue #798.
