### ISSUE TITLE
 Conflict raised between UI-Multiselect and Bootstrap-Multiselect plugin for jqGrid columnChooser method

### ISSUE THREAD

**Issue by snispolymer** [davidstutz/bootstrap-multiselect#756]
I am very new jqgrid plugin and i am trying to create a columnChooser method by the reference of http://www.trirand.com/jqgridwiki/doku.php?id=wiki:jquery_ui_methods#column_chooser. Everything is well and good the widget is loading as expected. But in my application i need bootstrap-multiselect plugin. i am facing conflict between these two plugins. How ever i am loading ui-multiselect plugin before bootstrap-multiselect, still the widget is not loading as expected.

Could you please help me on this, i am working a lot on this, not finding any 
![jqgridcolchooser](https://cloud.githubusercontent.com/assets/14982116/15964643/195bbad2-2f37-11e6-9d61-290c1988d6ea.png)
relevant solution.

I have attached both widget output by screenshot 
![jggridcolchooseruimul](https://cloud.githubusercontent.com/assets/14982116/15964839/2fe17cd2-2f38-11e6-84c4-68c474bd13a0.png)
![jggridcolchooseruimul](https://cloud.githubusercontent.com/assets/14982116/15964858/3f2edb62-2f38-11e6-90e5-3af0ffc2b8bc.png)

please find it.

**Comment by davidstutz** [comment]
I will not go into detail here, as I am not familiar with jqgrid - closing.
