### ISSUE TITLE
Adding data-placeholder collapses multiselect

### ISSUE THREAD

**Issue by ashokgj** [davidstutz/bootstrap-multiselect#759]
Hi,

Adding "data-placeholder" property for the select reported the following error
_Uncaught TypeError: Cannot create property 'nonSelectedText' on boolean 'false'_ 

Replacing lines from 179 to 184 (inside the function **Multiselect**)with the following code fixed the issue for me.
`this.options = this.mergeOptions($.extend({}, options, this.$select.data()));
        // Placeholder via data attributes
        if (this.$select.attr("data-placeholder")) {
            this.options.nonSelectedText = this.$select.data("placeholder");
        }`

**Comment by davidstutz** [comment]
Will have a look.
