### ISSUE TITLE
A small mistake in document.

### ISSUE THREAD

**Issue by PMExtra** [davidstutz/bootstrap-multiselect#760]
http://davidstutz.github.io/bootstrap-multiselect/

In end of section ".multiselect('select', value)"，

> The above parameter does also work when selecting multipe values. Note that onChange is called for each selected option individually!

The code like this now: 
```JS
<script type="text/javascript">
    $(document).ready(function() {
        $('#example-select-onChange-array').multiselect({
            onChange: function(option, checked, select) {
                alert('onChange triggered ...');
            }
        });
 
        $('#example-select-onChange-button').on('click', function() {
            $('#example-select-onChange').multiselect('select', '1', true);
        });
    });
</script>
```
In the line 10, the real code in this page is `$('#example-select-onChange').multiselect('select', ['1', '3'], true);`

This is a small mistake, but I found it. Please correct it.

**Comment by davidstutz** [comment]
Will do.
