### ISSUE TITLE
1 dropdown - 2 groups with Multiselect and Singleselect option?

### ISSUE THREAD

**Issue by anup756** [davidstutz/bootstrap-multiselect#761]
Hi I was wondering if there is a way to achieve this.. I want a single drop-down button with first group as checkbox with multiple selections and second group with just a radio button with single selection..

logic will be like Group1(item1&&item2)&&Group2(item1||item2)....

**Comment by anup756** [comment]
Any solutions??

**Comment by AmBeta** [comment]
sounds weried, two different selectors maybe better :|

**Comment by davidstutz** [comment]
That's currently not possible epecially as it would require generating both checkboxes and radio buttons. Use two multiselects instead.
