### ISSUE TITLE
Required attribute validation doesn't resolve on select in IE10, IE11, Edge

### ISSUE THREAD

**Issue by davidhantson** [davidstutz/bootstrap-multiselect#766]
Hi, I noticed the following when using the multiselect with a required field in IE:

Upon page load the select list is empty, when you try to submit the native required validation triggers. If you then select an item from the multiselect and submit, the validation still triggers.

![required validation ie](https://cloud.githubusercontent.com/assets/10639972/16724019/c6695230-4750-11e6-9b7d-3fa607902f1d.gif)

**Comment by davidstutz** [comment]
Yes, see also #620. Will try to fix.

**Comment by davidstutz** [comment]
Duplicate of #620, closing.
