### ISSUE TITLE
Sync with npm

### ISSUE THREAD

**Issue by liqwid** [davidstutz/bootstrap-multiselect#767]
`npm install bootstrap-multiselect` currently installs version 0.9.16 which is bigger than github version. It also doesn't have fix #709 included.

Please update npm version to have all the bugfixes from github and downgrade it's version(or merge them if they have had diverged)

**Comment by davidstutz** [comment]
Yes, will come with the next release.

**Comment by davidstutz** [comment]
Duplicate of #667 .
