### ISSUE TITLE
Clear filter search on selection

### ISSUE THREAD

**Issue by spurgeonbj** [davidstutz/bootstrap-multiselect#768]
Hi,

Greetings!

Wonder if this feature is already available.

Think this would save a few clicks and make it more easier.

Basically, it would be nice, that search gets cleared, when one of the filtered option is chosen. This will save clicking on filter clear button or backspacing and removing text in the search field.

Kindly let me know if this feature is available, 
if not, request you to kindly specify what code needs to be put in change event, somewhere like this hopefully ...
`$('#example-limit').multiselect({
            onChange: function(option, checked) {
//clear filter text
}`

Thanks a lot for the best multi select!
warm regards
Spurgeon

**Comment by davidstutz** [comment]
It's currently not included, I will think about a simple example.

**Comment by spurgeonbj** [comment]
Thank  you so much!!

**Comment by davidstutz** [comment]
Added an example, see the "Further Examples" section in the documentation (right at the end).

**Comment by spurgeonbj** [comment]
Thanks a ton! God bless you!
