### ISSUE TITLE
Problems with enableCollapsibleOptGroups

### ISSUE THREAD

**Issue by ccaper** [davidstutz/bootstrap-multiselect#773]
enableCollapsibleOptGroups is behaving strange for me.

I am using bootstrap-multiselect 0.9.13, jQuery 2.2.3, bootstrap 3.3.6.

The html for my select is this:
```html
<div id="filterDiv" class="form-group">
  <label>&nbsp;&nbsp;&nbsp;Filter:&nbsp;</label>
    <div class="btn-group">
      <select class="form-control" id="aFilter" multiple="multiple" size="2">
        <optgroup label="Opt 1">
          <option value="opt1Item1">opt1Item1</option>
          <option value="opt1Item2">opt1Item2</option>
          <option value="opt1Item3">opt1Item3</option>
        </optgroup>
        <optgroup label="Opt 2">
          <option value="opt2Item1">opt2Item1</option>
          <option value="opt2Item2">opt2Item2</option>
          <option value="opt2Item3">opt2Item3</option>
        </optgroup>
      </select>
    <button class="clearMulti btn btn-gold">Clear</button>
  </div>
</div>
```

The javascript to enable this is:
```javascript
$(document).ready(function() {
  $('#aFilter').multiselect({
    includeSelectAllOption: false,
    enableCaseInsensitiveFiltering: true,
    enableCollapsibleOptGroups: true,
    numberDisplayed: 0,
    maxHeight: 300,
  });
});
```

When this renders, I get clickable opt group labels (which I don't want), and everything is initially collapsed (I want everything initially expanded).  Even if I explicitly say `enableClickableOptGroups: false` I still get a clickable opt group labels.  Very puzzled as I believe I am following your example almost exactly.  This occurs in both Firefox and Chrome.

I've also included a jsfiddle replicating the above example, and showing how it's behaving.
https://jsfiddle.net/oL8vxv2c/

Am I missing a configuration or is this a bug?

Thank you.

**Comment by davidstutz** [comment]
Please use the latest master version. There were some issues with `enableCollapsibleOptGroups`, in particular #655 where there is a typo in the option name.

**Comment by ccaper** [comment]
Thank you for the quick response.

I just switched to master, and now I am seeing collapsible optgroups behave as expected, but now something in the master branch is not playing nice with bootstrap button groups.

This JSFiddle is pointing to your 0.9.13 version, and shows the buttongroup working correct:
https://jsfiddle.net/oL8vxv2c/

This JSFiddle is pointing to your master, and shows the multi-select and button inverted in order on display:
https://jsfiddle.net/s4kt6zn6/1/

Should there be any problems using your multiselect with bootstrap btn-group class?

Love your plugin, thank you very much.
