### ISSUE TITLE
bootstrap-multiselect and highcharts

### ISSUE THREAD

**Issue by marcopel** [davidstutz/bootstrap-multiselect#775]
First for all, thanks for your plugin!
Maybe a silly question but I have a problem when I try to use bootstrap-multiselect with highcharts.
I'm successfully using your code to limit the number of selected options using the onChange option:
        $('#example-limit').multiselect({
            onChange: function(option, checked) {
                // Get selected options.
                var selectedOptions = $('#example-limit option:selected');

```
            if (selectedOptions.length >= 4) {
                // Disable all other checkboxes.
                ...
            } else {
                // Enable all checkboxes.
               ...
            }
        }
    });
```

I have a jquery function (  ChartOnChangeOption('#mychart');  ) that hides a chart when user changes his preferences (such as start or end date of the chart, type of chart etc.).
Now I 'd like to hide the chart when user changes checkboxes in multiselect too.

I tried to simply add   ChartOnChangeOption('#mychart');    in your above  "onChange: function" code but the behaviour of the 'onchange' is not what I'd expect.

There is some issues in referencing another dom element ( '#mychart' ) within your "onChange: function"? Any help is appreciated.
Thanks

**Comment by davidstutz** [comment]
Not familiar with highcharts, so closing as there didn't seem to be any discussion.
