### ISSUE TITLE
Nuget download empty

### ISSUE THREAD

**Issue by Jojoshua** [davidstutz/bootstrap-multiselect#779]
The nuget install for this does not bring down any javascript or css.

**Comment by tiesont** [comment]
I would disagree. I just downloaded the package and extracted it, and everything is there.

What version of Visual Studio are you using? What project type?

**Comment by tiesont** [comment]
This was actually covered in #634 - the content is there, it's just not configured properly. You can install an older version if you really need NuGet to work.

**Comment by tiesont** [comment]
@davidstutz Would you consider (briefly) adding me as an owner of the package, so that I can correct this? It's a quick fix - you just have to add the resources to a content folder.

**Comment by Jojoshua** [comment]
I'm using visual Studio 2015 update 3 with a standard mvc project. Is there something I need to configure for this to work?

**Comment by tiesont** [comment]
@Jojoshua No. It's just a problem with the package, as noted in the referenced issue. The only way to use the package is for it to be fixed. You can download the zip and add it manually, for now, or use this version of the package: https://www.nuget.org/packages/Bootstrap.Multiselect/0.9.10

It's worth noting that 0.9.10 has bugs that really need fixing, so you're best off manually adding the files from the zip at this point.

**Comment by Jojoshua** [comment]
Thanks for the quick response. My work blocks github so nuget was my only option. I may have to wait on using this until fixed via nuget.

**Comment by tiesont** [comment]
Here's a temp package you use. Run 

`Install-Package BS.Multiselect -Version 0.9.15`

from the package manager console. It's an unlisted package, and I will be deleting it if/when David fixes the "official" package.

**Comment by Jojoshua** [comment]
Wow thanks. Everything pulled in properly. You the man.

**Comment by rajeem** [comment]
Is version 0.9.15 on Nuget not available anymore? I am unable to install it.

**Comment by davidstutz** [comment]
Addressed in #634.
