### ISSUE TITLE
Fixed title

### ISSUE THREAD

**Issue by Gefn** [davidstutz/bootstrap-multiselect#781]
Would be great if we could put a "fixed" title, aka a title that doesn't get updated when items are selected.

I think it corresponds to the main use of such menus, and yet I can't seem to be able to find this options.

**Comment by Gefn** [comment]
At the moment, here's my workaround. I'm a complete newb in Javascript so it's probably very ugly, but I specify the `data-placeholder` attribute of the `select` to the desired value, and all my `select` objects have the `filter` class.  Then, I just do that.

```
        <script type="text/javascript">
            $(document).ready(function() {
                $('.filter').each(function() {
                    var currFilter = $(this);
                    $(this).multiselect({
                        buttonText: function(options, select) {
                            return currFilter.attr('data-placeholder');
                     }
                    });
                });
            });
        </script>
```

It works

**Comment by davidstutz** [comment]
This should be able using the `buttonText` option by simply returning a fixed string.
