### ISSUE TITLE
problem with same option on multiple groups

### ISSUE THREAD

**Issue by RipperXD2** [davidstutz/bootstrap-multiselect#783]
```
<select id="example-multiple-optgroups">
    <optgroup label="Group 1">
        <option value="1-1">Option 1.1</option>
        <option value="1-2" selected="selected">Option 1.2</option>
        <option value="1-3" selected="selected">Option 1.3</option>
    </optgroup>
    <optgroup label="Group 2">
        <option value="2-1">Option 2.1</option>
        <option value="1-2">Option 1.2</option>
        <option value="2-3">Option 2.3</option>
    </optgroup>
</select>
```

i have something like that, and when i select the first "1-2" option everything is working, when i select the second and everything ok, but when i deselect the first or the second "1-2" the problem come, although the other is select this acts like that option dont exist,

**Comment by davidstutz** [comment]
Well, I would say this is not supposed to work as it wouldn't make sense to have a use submit a form where to different options given the same value.
