### ISSUE TITLE
Select all options by default

### ISSUE THREAD

**Issue by psyclight** [davidstutz/bootstrap-multiselect#785]
What can I do to make all options have been already selected  when  page loaded. I have tried a few times,but failed, thank you so much!

**Comment by PauChan2016** [comment]
$('#id option').each(function(){
       	  this.selected=true;
       	});
$('#id').multiselect("refresh");
I use this method finally.

**Comment by davidstutz** [comment]
Use the `selectAll` method or just generate the select element with pre-selected options.

**Comment by sanjoyroy** [comment]
thanks psyclight! that worked!

**Comment by NDDC** [comment]
> $('#id option').each(function(){
> this.selected=true;
> });
> $('#id').multiselect("refresh");
> I used this method finally.

this was great it works on me
