### ISSUE TITLE
Multiselect option selecting heading checkboxes incorrectly

### ISSUE THREAD

**Issue by celina1910** [davidstutz/bootstrap-multiselect#789]
I have implemented multiselect with search option in my application. We have multiple groups in the dropdown. It wlis working perfectly fine for all conditions except one.

If i select all of the options from a group one by one then selects the group heading checkbox ( which is expected) and along with it it selects other group heading checkboxes preceeding the one in question.(which is not correct) 
Please help urgently.

**Comment by davidstutz** [comment]
Cannot reproduce this on master. If it persists on master, please re-open.
