### ISSUE TITLE
Optgroup with input checkbox 

### ISSUE THREAD

**Issue by Reltik** [davidstutz/bootstrap-multiselect#795]
Hi! in the lastest version I see that the optgroup options have a checkbox. Is this intended ? I was using a older version and the optgroup doesn't have it.

Older version
![opt1](https://cloud.githubusercontent.com/assets/9728617/18180335/c32bdbda-705c-11e6-8e28-71b9110092f9.PNG)

Lastest version
![opt2](https://cloud.githubusercontent.com/assets/9728617/18180338/c5f8dbce-705c-11e6-8353-328c3318d473.PNG)

I managed to hide that input checkbox, LOC 940 in file bootstrap-multiple.js

``` js
if (this.options.enableClickableOptGroups && this.options.multiple) {
    $('a label', $li).prepend('<input type="checkbox" style="display:none" value="' + value + '"/>');
}
```

Adding the `display: none` in style. I can make a pull request if you want.

Cheers

**Comment by davidstutz** [comment]
The default behavior is to show the optgroups without checkbox (i.e. by default `enableClickableOptGroups` is disabled) - this also works in the documentation, see one of the last examples at http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-multiple.

**Comment by attilioprimo** [comment]
Hi!
Sorry but I have the opposite problem. I want to show the checkbox of the optgroups father. How can I do?
Thanks
