### ISSUE TITLE
Programatically change button texts

### ISSUE THREAD

**Issue by flavio-alves** [davidstutz/bootstrap-multiselect#800]
I am building an aurelia app and using bootstrap-multiselect v0.9.13 to enhance multiple select elements.

I am also providing to the end user the ability to change language, translating the entire app when he does it.

How can I programatically update `allSelectedText`, `nonSelectedText` and `nSelectedText`, in order to present translated text to the user?

I already tried `.multiselect('setOptions', {allSelectedText: 'Translated text here', ....})` but with no luck...

Any help is appreciated.

**Comment by Aidurber** [comment]
After updating the options, have you tried rebuilding the multiselect?

From the documentation: 
> Used to change configuration after initializing the multiselect. This may be useful in combination with .multiselect('rebuild').


### Example
```
$('#ms').multiselect('setOptions', {allSelectedText: 'Translated text here'})
$('#ms').multiselect('rebuild')
```

**Comment by davidstutz** [comment]
You need to call rebuild after changing options as @Aidurber noticed.
