### ISSUE TITLE
Use of class keyword breaks YUICompressor minification

### ISSUE THREAD

**Issue by ysi-brettm** [davidstutz/bootstrap-multiselect#810]
We're using version 2.4.0.0 of [PureKrome/YUICompressor.NET](https://github.com/PureKrome/YUICompressor.NET) to minify our JavaScript resources and it throws the following error when it gets to bootstrap-multiselect.js:

> Failed to read/parse data in file [js/bootstrap-multiselect.js]
> missing name after . operator

This is caused by referencing a property named "class" (a reserved keyword) on an object. #713 was meant to address this, but the fix was merged manually a piece was missed. Compare 59171ba9dfbba37aa37e563c20cd5ce18cb3f62d to 2b9a5fdb3916d12d343cf77b3b9a1801d582ce9c.

Fixing this should be as simple as changing

```
'class': option.class,
```

to

```
'class': option['class'],
```

**Comment by davidstutz** [comment]
Will ahve a looka t the PR.

**Comment by davidstutz** [comment]
Also see #812 with some more discussion. Will close this one.
