### ISSUE TITLE
 option.class giving us a error 

### ISSUE THREAD

**Issue by josebermudez** [davidstutz/bootstrap-multiselect#812]
IE 8 error.
We are using the http://yui.github.io/yuicompressor/  and option.class giving us a error  and IE8 

1481:46:missing name after . operator

We think  that for compatibility must be used option['class']
![fireshot screen capture 148 - refresh-sf - online javascript and css compressor - refresh-sf_com](https://cloud.githubusercontent.com/assets/1851959/19132227/38fa5974-8b18-11e6-93a5-2a20cd44c426.png)

**Comment by farhad-tarapore** [comment]
Yes, I got the same thing

java -jar ~/Downloads/yuicompressor-2.4.8.jar bootstrap-multiselect.js -o bootstrap-multiselect.min.js
[ERROR] in bootstrap-multiselect.js
  1430:30:invalid property id
[ERROR] in bootstrap-multiselect.js
  1430:31:syntax error
[ERROR] in bootstrap-multiselect.js
  1431:34:syntax error
[ERROR] in bootstrap-multiselect.js
  1432:34:syntax error
[ERROR] in bootstrap-multiselect.js
  1433:22:syntax error
[ERROR] in bootstrap-multiselect.js
  1:0:Compilation produced 5 syntax errors.

**Comment by deepak-prabhu-jabong** [comment]
I got the  similar error..After I commenting out the below attributes it worked.. Seems like syntax errors ... double exclamation is included in the code

var attributes = {
                        'value': option.value,
                        'label': option.label || option.value,
                        'title': option.title
                        //'class': option.class
                        //'selected': !!option.selected,
                        //'disabled': !!option.disabled
                    };

**Comment by demartis** [comment]
I got the same error, 
"class" is a reserved word in ECMAScript 5 and 6.
I resolved accessing to this properties with:

         var attributes = {
                        'value': option.value,
                        'label': option.label || option.value,
                        'title': option.title,
                        'class': option['class'],
                        'selected': !!option['selected'],
                        'disabled': !!option['disabled']
                    };

**Comment by smidgen** [comment]
I got the same error, solved it the same way @demartis did. This is the way to do it without risking loss of functionality.

Normally I don't care about IE8, but we have to contact our client and get them to agree before we can drop IE8 support. Since this is an extremely simple fix, it's worth the effort.

**Comment by davidstutz** [comment]
Fixed by merging #862.
