### ISSUE TITLE
how to use this as directive in my angularjs application?

### ISSUE THREAD

**Issue by vinuuu** [davidstutz/bootstrap-multiselect#815]
i want use this a directive in my angular application?

**Comment by DanielCaspers** [comment]
Why not just wrap it in an Angular 1.5 component you custom role for your application or company? It's pretty common to just make something like this.

`<yourVendorPrefix-multiselect
    config="$ctrl.config"
    functionToBindToPlugin="$ctrl.someFunc()">
</yourVendorPrefix-multiselect>`

Under the hood, you'll still interact with the vanilla plugin JS and jQuery.

**Comment by davidstutz** [comment]
Closing as I am not familiar with Angular and there does not seem to be any ongoing discussion.
