### ISSUE TITLE
Filter does not work as expected

### ISSUE THREAD

**Issue by jaimestuardo** [davidstutz/bootstrap-multiselect#820]
Hello... I have the following situation, for example, I have a multiselect that has the following element: "151025-pp4_¿Cómo hacer una huerta en 1m2?" among several others. 

If I write "huerta" in the search box, that element is found and "huerta" is underlined. However, if I write "huerta en" or "una huerta", that element is not found. 

These are the options:

`buttonClass: 'btn btn-default',
            dropRight: false,
            selectedClass: 'active',
            buttonWidth: 'auto',
            buttonContainer: '<div class="btn-group" />',
            // Maximum height of the dropdown menu.
            // If maximum height is exceeded a scrollbar will be displayed.
            maxHeight: false,
            includeSelectAllOption: false,
            selectAllText: ' Select all',
            selectAllValue: 'multiselect-all',
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true,
            filterPlaceholder: 'Search',
            // possible options: 'text', 'value', 'both'
            filterBehavior: 'text',
            preventInputChangeEvent: false,
            nonSelectedText: 'None selected',
            nSelectedText: 'selected',
            numberDisplayed: 3
`

**Comment by davidstutz** [comment]
Can't reproduce it using one of the examples in the documentation. A minimum working example would be helpful. Feel free to re-open if the problem still occurs.
