### ISSUE TITLE
possibility to define attributes that should be copied from original select to button (not options)

### ISSUE THREAD

**Issue by danisowa** [davidstutz/bootstrap-multiselect#822]
Is it possible to copy some custom-attributes from the original select to the button?

For example

`<select ...... tooltip-placement="right">`

i need

`<button .... tooltip-placement="right">`

I saw:

`// Keep the tab index from the select.
            var tabindex = this.$select.attr('tabindex');
            if (tabindex) {
                this.$button.attr('tabindex', tabindex);
            }`
If the following line is addes tooltip-placement is copied to the button
`this.$button.attr('tooltip-placement', this.$select.attr('tooltip-placement'));`

maybe it is possible to have configuration option in multiselect() function to pass attributes that should be copied to the button and then handle them in a for loop?

**Comment by davidstutz** [comment]
I won't add an option for this. But it is simple to do it manually after initializing the mutliselect, just grab the created button and add the attributes of your choice.
