### ISSUE TITLE
Keeping moved option

### ISSUE THREAD

**Issue by princeofbubbles** [davidstutz/bootstrap-multiselect#823]
David!

Thank you for sharing this great plugin!
Please help me though, I cannot figure out how to keep a selected and moved item in the original list. It always gets removed, which makes sense if there are just two pools but if there are several pools on the right, I want to be able to assign it to more than one destination. Like when there is  **fruit** on the left and **round** and **red** on the right. I need to be able to put a cherry into **round** as well as **red**.

**Comment by davidstutz** [comment]
Sorry, but without a concrete example I really can't follow what you want to accomplish. Feel free to re-open and discuss ;)

**Comment by princeofbubbles** [comment]
Thanks for your reply, David!
As I wrote today a year ago, I want to place an item into more than one bin on the right. I do not know how to make it more concrete, but I will try to illustrate the example with  ASCII art:

**Start:**
[FRUIT]           >                [COLOR RED]  
cherry            <                                             

                      >              [SHAPE ROUND]
                      <

-----------------------------------------------

**Goal:**
[FRUIT]           >                [COLOR RED]  
                      <                     cherry                        

                      >              [SHAPE ROUND]
                      <                     cherry

This is not possible, because as soon as you place the cherry in the [FRUIT RED] bin, it is removed from [FRUIT], so it can not be placed into [SHAPE ROUND]:

**Problem:**
[FRUIT]           >                [COLOR RED]  
                      <                     cherry                        

                      >              [SHAPE ROUND]
                      <

Thanks
