### ISSUE TITLE
Have dropdown behave like radio button

### ISSUE THREAD

**Issue by santoshgiridhar** [davidstutz/bootstrap-multiselect#827]
Is it possible to have feature to select either of one value from the dropdown list.
Text-1
Text-2
Message-1
Message-2
Values which can be selected is Text-1, Text-2, Message-2 [User cannot select Message-1] if he selects Message-1, Text-1 gets unselected.

**Comment by briang123** [comment]
If you're asking if radio buttons can be configured instead of checkboxes, then yes. See docs

**Comment by briang123** [comment]
Remove the multiple attribute

**Comment by davidstutz** [comment]
So either remove the mutiple attribute as suggested. But it seems that your case is more involved. If you have manual constraints you probably need to check `onChange` or similar hooks ...
