### ISSUE TITLE
Drop down not working with angular ng-repeat

### ISSUE THREAD

**Issue by sreekanth-karini** [davidstutz/bootstrap-multiselect#831]
Hi, Thanks for providing this plugin!
This drop down works perfectly with static options data. But when I use angular ng-repeat to options in select tag, it's not working means it is not displaying the drop-down list.
`<select id="employeesList" multiple="multiple">
    <option value="{{employee.id}}" ng-repeat="employee in $root.employeeIdList">{{employee.name}}         </option>   
</select>`
Please provide the solution Thanks!

**Comment by davidstutz** [comment]
Not familiar with Angular, will close it as there wasn't any discussion.
