### ISSUE TITLE
how to restrict the number of options to be selected ?

### ISSUE THREAD

**Issue by AmrataRamchandani** [davidstutz/bootstrap-multiselect#842]
like at a time only 3 at the max can be selected or so ?

**Comment by nikataus** [comment]
One way to do it is to implement onChange method and check inside how many items are selected and if the max is reached (like 3) you can do whatever you want - show alert or disable other options or change the css, etc...


$(document).ready(function() {
        $('#example-includeSelectAllOption-onChange').multiselect({
            includeSelectAllOption: true,
            onChange: function(option, checked) {
////// Add your code
            },
        });
    });

**Comment by devmi** [comment]
Please take a look at the 3rd example on the [Further Examples](http://davidstutz.github.io/bootstrap-multiselect/#further-examples) section on the documentation.
