### ISSUE TITLE
Showing both bootstrap default and multi-select dropdown list 

### ISSUE THREAD

**Issue by rajivptbb** [davidstutz/bootstrap-multiselect#844]
multi-select dropdown was working fine before my system crashed and rebooted. 

After rebooting, multi-select dropdown is working but default bootstrap dropdown is also being shown. That means there are two dropdown lists of same content. Any idea why is it happening?

**Comment by ashishtyagi3** [comment]
Yes happened for me as well after updating to latest bootstrap-multiselect.js file

**Comment by rajivptbb** [comment]
Thank you. I had a number of js and css files that I extend from a parent page. Somehow it got to worked before but didn't after restarting - may be some browser cache or something?

I have rearranged my css and js files and the issue is resolved.
