### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by d-knafo** [davidstutz/bootstrap-multiselect#848]
this project that uses glyphicons. Bootstrap v4 drops the glyphicon font altogether.
Is there an equivalent for icons shipped with Bootstrap V4?
thanks

**Comment by divan** [comment]
I use multiselect with Bootstrap4 and everything works, except glyphicons (there is no free set nowadays, as I understood). Any known solution/fork for that?

**Comment by divan** [comment]
Related: https://github.com/davidstutz/bootstrap-multiselect/pull/1107
