### ISSUE TITLE
What is the latest version? 0.9.13?

### ISSUE THREAD

**Issue by bartclaeys** [davidstutz/bootstrap-multiselect#849]
According to https://cdnjs.com the latest version of bootstrap-multiselect
 is 0.9.13, but on Github it's 2.0, so I'm confused.

Here you can find the latest version, which seems to be 0.9.13:
https://cdnjs.com/libraries/bootstrap-multiselect

**Comment by davidstutz** [comment]
There shouldn't be a version 2.0 around. Please use the master branch whenever possible, 0.9.3 is quite old.

**Comment by bartclaeys** [comment]
Confused about your response. _"There isn't a 2.0 version"_ and _"0.9.3 is quite old"_, so what is the latest version?
