### ISSUE TITLE
ko observable array bound to bootstrap-multiselect is emptied the repopulated on every change

### ISSUE THREAD

**Issue by michaeldevenney** [davidstutz/bootstrap-multiselect#851]
Wanted to start off with a hearty thanks for a great plug-in!  

Our site uses Entity Framework for data persistence, so I'm using Julie Lerman's suggested method for managing object state on the client.  I added a handler to the change event for my observable array so I could update the object state for the item that was just added (or removed).  I started using the code below to test that everything was working as expected when I saw something odd.  The Races observable array arrives from the server with one or more items already in it.  These are properly displayed by the multiselect after initialization but when I try to add or remove items (through the UI, not code) all of the selected items are removed first, then added back to the array.  After that the array is updated with the new item (either removed or added).  All of this I can see in the console.  I have no way of knowing which items are actually new in the array and which were in the array prior and just added as part of refreshing the items.  I traced through the code and couldn't find where it was refreshing the array.  I need a hand getting there and I should be able to figure out what's going on and suggest a fix or submit a pull request.
```
vm.Races.subscribe(function (changes) {
    changes.forEach(function (change) {            
        console.log(change.status + ' ' + change.value.RaceName() + ' at index ' + change.index);
    }});
}, null, "arrayChange");
```

Thanks!

**Comment by davidstutz** [comment]
Not familiar with Knockout, closing as there wasn't any discussion.
