### ISSUE TITLE
Cannot pass whole object to the binded back end

### ISSUE THREAD

**Issue by evenlee** [davidstutz/bootstrap-multiselect#852]
In my case, I want to use the whole object, then I did it like the knockout way, but always the first object selected no matter which one is checked. In [this ](https://jsfiddle.net/joeheyming/q6gemrv5/)fiddle, I did some change to test:
`   <select id="select2" multiple="multiple" class="form-control" data-bind="options: availableObjects, optionsText: 'name', selectedOptions: selectedIds, multiselect: {
    includeSelectAllOption: true
  }">`
` selectedIds: ko.observableArray()`
But it doesn't work.
If this is fixed, I think it will be more perfect.

**Comment by davidstutz** [comment]
Not familiar with Knockout, closing.
