### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by rubenvincenten** [davidstutz/bootstrap-multiselect#854]
It would be good to add translations for various languages.

Here is a dutch translation:

```js
// example location: dist/js/i18n/nl.js
!(function ($, defaults) {
	defaults = $.extend(defaults, {
		allSelectedText  : 'Alles geselecteerd',
		filterPlaceholder: 'Zoeken',
		nSelectedText    : 'geselecteerd',
		nonSelectedText  : 'Niets geselecteerd',
		selectAllText    : ' Selecteer alles'
	});
}(jQuery, jQuery.fn.multiselect.Constructor.prototype.defaults));
```
The structure is written in a way so it minifies correctly (21% smaller when variables are mangled).

**Comment by s1738berger** [comment]
Here the words that can be used for a gemran translation:

selectAllText: 'Alles auswählen',
allSelected: 'Alles ausgewählt',
countSelected: '# von % ausgewählt',
noMatchesFound: 'Nichts gefunden',

**Comment by davidstutz** [comment]
Already mentioned in #428 and #646.
