### ISSUE TITLE
how to select checkbox using jquery?

### ISSUE THREAD

**Issue by d33pak-s1ngh** [davidstutz/bootstrap-multiselect#855]
i have a multi-select dropdown in which i want to select some checkbox using jquery base on the value of option on some event how i can achieve this?

also i want to select all options in multiselect dropdown base on event with jquery.

**Comment by d33pak-s1ngh** [comment]
i got the first one from one of your example
$('#example-select').multiselect('select', ['1', '2', '4']);

**Comment by davidstutz** [comment]
For selecting all options you can use the 'selectAll' method, see docs. You can use this in an event handler then.
