### ISSUE TITLE
how to use collapsible optGroups without enabling multiselect

### ISSUE THREAD

**Issue by sayalichopade** [davidstutz/bootstrap-multiselect#858]
I want to use optGroups to be collapsible, but not letting user select multiple from any optgroup. It does not work if i dont specify multiple="multiple". is there a solution or other way to do this?

**Comment by davidstutz** [comment]
Well you still need to allow multiple options to be selected. The only way to limit the number per options is by hooking into the `onChange` event. There is an example in the Further Examples section for this.
