### ISSUE TITLE
Customizing li template

### ISSUE THREAD

**Issue by ranjithchil** [davidstutz/bootstrap-multiselect#859]
I need to customize checkbox inside mutliselect box to match with already customized checkboxes of my application.

In order to get my application checkbox, I need to have

```
<label class="checkbox">
    <input type="checkbox">
       <i onclick="window.event.cancelBubble = true;"/>
    </input>
</label>
```
However, modifying templates to get the same is not working out.

```
('#workArea').multiselect({
    maxHeight: 200,
    includeSelectAllOption: true,
    buttonWidth: '100%',
    dropRight: true,
    templates: {
        li: '<li><a tabindex="0"><label><input><i></i></input></label></a></li>'
    }
});
```
Above results in

```
<li>
   <a tabindex="0">
      <label class="checkbox" title="Unassigned">
           <input type="checkbox" value="unassignedWorkArea"> Unassigned
      </label>         
   </a>
</li>
```
where `<i></i>` is missing. What do i need to do to make it work?

**Comment by RicardoGralhoz** [comment]
@ranjithchil,  did you find the answer to your question?

**Comment by devmi** [comment]
@ranjithchil,  did you find the answer to your question?

**Comment by ranjithchil** [comment]
Yes @devmi. However, i have not used templates configuration option to achieve what i need. 

 ```
('#workArea').multiselect({
    maxHeight: 200,
    includeSelectAllOption: true,
    buttonWidth: '100%',
    dropRight: true,
    templates: {
        li: '<li><a tabindex="0"><label><input><i></i></input></label></a></li>'
    }
    addCheckBoxes('workArea');
});

function addCheckBoxes(input)
{
	jQuery('#' + input +'UL li a label.checkbox').append('<i onclick="window.event.cancelBubble = true;"></i>');
}
```

It might not be the right/accurate way to code, however, i had to do that way to complete my task and is working fine.

**Comment by devmi** [comment]
Cool! I also have used jQuery to `append/preppend` an `<i>` icon to a menu item before. 

It seems like combining [optionLabel](http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-optionLabel) with [enableHTML](http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-enableHTML) could help achieving this goal too, if XSS injection is taken care of. Please see #475
