### ISSUE TITLE
All Selected problem

### ISSUE THREAD

**Issue by joelmalach** [davidstutz/bootstrap-multiselect#864]
I'm using the Bootstrap Multiselect jquery plugin. My problem is, if the user selects all options, I want it to actually display all the selections like this

Cheese, Tomatoes, Mozzarella, Mushrooms, Pepperoni, Onions

Instead, once I select the 6th option, it displays this

All Selected (6)

**Comment by leankuroneko** [comment]
According to [documentation](http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-allSelectedText): 

You just need to set

`allSelectedText: false`

in your configuration.

**Comment by joelmalach** [comment]
Great – that worked thanks

 

Kind regards

 

Joel

 

 

Joel Malach

 

T 0161 763 4783
M 07540 123 563
E   <mailto:joel@malach.co.uk> joel@malach.co.uk
