### ISSUE TITLE
How to get last selected value from multiselect

### ISSUE THREAD

**Issue by rohit-mittal** [davidstutz/bootstrap-multiselect#865]
Hi,

I have a multi select drop down. There is 4 option. Option A, B, C and D. Currently, option A and B are selected. When i select option C, i want to get last selected value ie C. When i am using .val(), it is returning me A,B,C.

Any idea how to get it?

**Comment by briang123** [comment]
There is a similar question I just answered about this. I suggest adding a custom attribute to manage the selections and pull from there.

**Comment by davidstutz** [comment]
You can hook into `onChange` and save the last selected option(s) in a global variable.
