### ISSUE TITLE
multiselect does not work with angular $compiler

### ISSUE THREAD

**Issue by kiranpvsr** [davidstutz/bootstrap-multiselect#874]
I cannot select the checkboxes after using Angular's $compiler on a page.
The checkboxes do not appear disabled. 
I can click on them but the tickbox does not appear nor the value is shown as selected in the multiselect dropdown.

![image](https://cloud.githubusercontent.com/assets/5746500/23472983/88aac8da-fea6-11e6-9d26-8cfaee920cfa.png)

**Comment by davidstutz** [comment]
Not familiar with Angular, closing - re-open if necessary or for discussion.
