### ISSUE TITLE
form-horizontal style missing

### ISSUE THREAD

**Issue by china-live** [davidstutz/bootstrap-multiselect#883]
It's strange why only the form-inline style but not form-horizontal, intentionally or omitted？

**Comment by CmderQ** [comment]
@china-live You should post your code  let we know what happened!

**Comment by davidstutz** [comment]
Well, I don't really know what you mean ... Feel free to re-open with a more detailed description and some code.

**Comment by china-live** [comment]
![11](https://user-images.githubusercontent.com/12002799/32136438-701aab66-bc40-11e7-880b-8691e9d98ecc.jpg)

![22](https://user-images.githubusercontent.com/12002799/32136432-55869918-bc40-11e7-9bab-5fd054d8d6e1.jpg)

[test.zip](https://github.com/davidstutz/bootstrap-multiselect/files/1424409/test.zip)

**Comment by china-live** [comment]
![11](https://user-images.githubusercontent.com/12002799/32136521-907f9fa0-bc41-11e7-89f0-9579c0e06e3a.jpg)
![22](https://user-images.githubusercontent.com/12002799/32136524-97631b8a-bc41-11e7-90c2-266de22b45ec.jpg)
[test.zip](https://github.com/davidstutz/bootstrap-multiselect/files/1424412/test.zip)
