### ISSUE TITLE
onSelectAll and onDeselectAll not working as documented

### ISSUE THREAD

**Issue by hbarcelos** [davidstutz/bootstrap-multiselect#884]
I'm running `bootstrap@3.3.7`, `jquery@1.12.4` and `bootstrap-multiselect@0.9.13-1`.

I was having this issue as part of a larger application, so I decided to reduce it to the minimum reproducible problem.

Here is my Javascript:
```js
$(function() {
  $('select').multiselect({
    includeSelectAllOption: true,

    onChange: function(option, checked) {
      console.log('CHANGE!')
    },
    onSelectAll: function() {
      console.log('SELECT ALL!')
    },
    onDeselectAll: function() {
      console.log('UNSELECT ALL!')
    }

  })
})
```

And my HTML

```html
      <select multiple>
        <optgroup label="Test 1">
          <option value="1">
            1.1
          </option>
          <option value="2">
            1.2
          </option>
          <option value="3">
            1.3
          </option>
        </optgroup>
      </select>
```

From the docs:

> **onSelectAll** 	
> 
> This function is triggered when the select all option is used to select all options. Note that this can also be triggered manually using the .multiselect('selectAll') method.
>
> Note that the onChange option is not triggered when (de)selecting all options using the select all option. 

> **onDeselectAll** 	
>
> This function is triggered when the select all option is used to deselect all options. Note that this can also be triggered manually using the .multiselect('deselectAll') method.
>
> Note that the onChange option is not triggered when (de)selecting all options using the select all option. 

However, when I click the select all option for the first time, I get:

>     10:16:31.847 SELECT ALL! 1 localhost:3000:38:7
>     10:16:31.849 CHANGE! 1 localhost:3000:35:7

So, the `onChange` option WAS triggered.

When I click for the second time, I get:

>     10:24:32.111 CHANGE! 1 localhost:3000:34:7

So, not only the `onChange` option was triggered, as also the `onDeselectAll` option was not triggered.

**Comment by ruiramos** [comment]
Hey @hbarcelos, had the same problem, fixed it by just using the latest version of the code directly from github. It seems that the latest release was 2 years ago!
