### ISSUE TITLE
multi-column multi-select dropdown

### ISSUE THREAD

**Issue by gradexpert** [davidstutz/bootstrap-multiselect#885]
Hi there can i add a second column in front of the item like this
![classesddl](https://cloud.githubusercontent.com/assets/25625867/24130034/63bd054e-0e3a-11e7-83e4-6f6d1258ed70.png)

**Comment by briang123** [comment]
I believe you would need to return the text as a couple column divs in a row container. The end result would be an LI tag wrapping a div HTML containing your option text.

**Comment by davidstutz** [comment]
Use the `optionlabel` and `enableHTML` options.
