### ISSUE TITLE
Can we changed the value of default "None selected" before we select one

### ISSUE THREAD

**Issue by nanyoullm** [davidstutz/bootstrap-multiselect#888]
Can we changed the value of default "None selected" before we select one?

**Comment by rushdykamel** [comment]
Hi @nanyoullm 
You can do that by using `nonSelectedText` configuration option.

```
$('#example-nonSelectedText').multiselect({
      nonSelectedText: 'Your text here!!!'
});
```

Documentation: http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-nonSelectedText
