### ISSUE TITLE
grouping from database

### ISSUE THREAD

**Issue by gradexpert** [davidstutz/bootstrap-multiselect#889]
I am binding jquery multiselect dynamically from database stored procedure (MVC 4)

HTML

`@Html.ListBoxFor(m => m.Classes, new SelectList(Model.Classes, "Value", "Text"), new { @id = "classList" })`

SCRIPT

`$('#classList').multiselect({ enableClickableOptGroups: true });`

Controller Code

```
SuperMapModel smM = new SuperMapModel();
smM.scM = new SearchControlViewModel();
smM.scM.Classes = new SelectList(repClass.GetClassesByYear(23), "classID", "classname");
```
It works like a charm except for one thing! I want to add grouping/group header like optgroup does.. how can i do that?

**Comment by davidstutz** [comment]
The plugin should naturally support optgroups if you add them in the select - so it depends whether `SelectList` is able to add them. But I am also not familiar with ASP.NET.
