### ISSUE TITLE
how to disable an option in multiselect dynamically

### ISSUE THREAD

**Issue by nanyoullm** [davidstutz/bootstrap-multiselect#891]
I set three options in multiselect, option1, option2 and option3.
when I chose the option1 and option2, can the option3 be disabled dynamically.
what should i do to realize this.
thanks :smile:

**Comment by briang123** [comment]
There is sample code available for this on the documentation site.

**Comment by briang123** [comment]
I have code in here for it. 
https://gist.github.com/1239268caed3c207b51be8f82250a728

**Comment by davidstutz** [comment]
The example in the documentation does not disable the options, but prevents from selecting more options. However, I guess it is also possible to disable options in this case.

**Comment by sbagoban** [comment]
**gujlhjul**
