### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by danyaljj** [davidstutz/bootstrap-multiselect#892]
[This is how I have added the links to css and js file.](https://github.com/danyaljj/Apelles/blob/f234d6b6f68e1035114156da8276d8a862223e4c/public/index.html#L45) and this is the [js definition](https://github.com/danyaljj/Apelles/blob/f234d6b6f68e1035114156da8276d8a862223e4c/public/index.html#L136-L138).  
But sometimes it just stops working. 

<img width="1602" alt="screen shot 2017-04-02 at 5 55 46 pm" src="https://cloud.githubusercontent.com/assets/2441454/24591724/d026bb84-17cd-11e7-9aa5-c8eebdf88c77.png">

Note that it doesn't show any error on not being able to download the package (not a network issue). But then after a few refreshes it starts working. Am I using it right?

**Comment by davidstutz** [comment]
Update to the latest master version please and re-open if it still does not work.
