### ISSUE TITLE
Bootstrap multi select optgroup with one element not working properly

### ISSUE THREAD

**Issue by nayyarmannu** [davidstutz/bootstrap-multiselect#894]
Bootstrap multi select with opt group is not working properly when there is only one option inside optgroup. When I check Option 3.1 (in my example) all the optgroups above it get selected.

Please refer the following [JSFiddle Link](https://jsfiddle.net/ets8j23k/3/) for the example.

Moreover is it possible to give only option, if optgroup has one element inside it? Like this:

`<option value="Option 3.1">Option 3.1</option>`

instead of

```
<optgroup label="Group 3">
   <option value="Option 3.1">Option 3.1</option>
</optgroup>
```

Please help me in solving this issue.

**Comment by nayyarmannu** [comment]
#680 solved the issue.
Replacing 
`n.prevAll('.multiselect-group').find('input').prop('checked', i);`
with
`n.prevAll('.multiselect-group:first').find('input').prop('checked', i);`

**Comment by AnilSinghKushwaha** [comment]
but there is no such code in bootstrap-multiselect.js (0.9.15) version , now wat should i do????
