### ISSUE TITLE
Cannot programatically clear filtering

### ISSUE THREAD

**Issue by DanielCaspers** [davidstutz/bootstrap-multiselect#895]
First of all, I want to start this by saying thanks for this great plugin! 

**Problem**
I am trying to use the multiselect in a BS Modal, which I reset on the `hidden.bs.modal` event. The idea is that users can attempt to add some resource through the modal, and regardless of whether they complete the attempt or cancel, the state of the dialog should be fresh the next time it is opened. 

I found how to reset the button state and selected options in the docs, but can't seem to reset the search query to empty. Any help or guidance in the documentation would be appreciated.

**Code snippets**
Config
```
$('select').multiselect({
	buttonWidth: '100%',
	enableFiltering: true,
	enableCaseInsensitiveFiltering: true
});
```

Dialog hiding logic
```
dialogElement.on('hidden.bs.modal', function () {
	// Reset values in the form for next open
	formElement[0].reset();
	validator.resetForm();

	var selectInputs = $('#' + dialogId).find('select');
	for(var selectInput of selectInputs) {
		$(selectInput).multiselect('deselectAll', false);
		$(selectInput).multiselect('updateButtonText');
	}
});
```

**Video of bug**

![search persists after refresh](https://cloud.githubusercontent.com/assets/6056563/25125904/12627ffe-23f6-11e7-9f05-4cb513ddee41.gif)

**Comment by rludwig21** [comment]
You could add this single line
```
this.$filter.find('.multiselect-search').val('').focus().blur();
```
 to the main bootstrap-multiselect.js file to the "onDropdownHide()" function this way it will always clear the search. The function should be on line 342 in the .js file.

OR like this for each individual multiselect:
```
$('select').multiselect({
	buttonWidth: '100%',
	enableFiltering: true,
	enableCaseInsensitiveFiltering: true,
        onDropdownHide: function() {
              ('.select').val('').focus().blur();
        },
});
```
What happens here is it clears the selected value(s), then focus the cursor on the search (clearing it). The .blur() is necessary to keep the cursor from showing up (remove the blur() and you should see what I mean).

Let me know if you have any issues, going off memory from a few days ago...

**Comment by DanielCaspers** [comment]
That makes perfect sense. Thanks a bunch!

**Comment by rludwig21** [comment]
You're welcome!

**Comment by DanielCaspers** [comment]
After finally getting around to this again, I had to take a slightly different approach than suggested, but now works great for me. Figured I'd update.
```
$('select').multiselect({
	buttonWidth: '100%',
	enableFiltering: true,
	enableCaseInsensitiveFiltering: true,
        onDropdownHide: function() {
		$('button.multiselect-clear-filter').click();
        },
});
```

**Comment by joshbuchea** [comment]
For anyone else stumbling across this issue. While @DanielCaspers' solution successfully cleared the filter input, oddly filtering functionality was left non-functional until a new query was entered & removed, then filter functionality began working again.

Was able to clear the filter input without breaking filter functionality with:

```js
$('#target.bs-multiselect + .btn-group .multiselect-filter input').val('').trigger('keydown');
```

Replace `#target` with your own unique selector and you should be good to go 👍 

Note: `.trigger('keydown')` is necessary

**Comment by hithendra554** [comment]
Just my 2 cents. I did it like this. In bootstrap.multiselect.js there is a method where we dynamically create all filter templates for filters etc like below.

templates: {
              
            }
 In this section search for input control which is search text box and give an id. 
<input id="filterTB" class="form-control multiselect-search" type="text" />

In your multiselect method, write a method to clear the value on onChange. 

 $('#MultiSelectControl').multiselect({
                enableFullValueFiltering: false,
                
                enableFiltering: true,
                filterBehavior: 'text',
                buttonWidth: '210px',
                                enableCaseInsensitiveFiltering: true,
                SelectedText: 'Employer Groups Selected',
                filterPlaceholder: 'Search for Employer Group..',
                  
                onChange: function ($option) {
                    
                    $('#filterTB').val('').trigger('keydown');
                }
            });
