### ISSUE TITLE
How to display Select all option at last?

### ISSUE THREAD

**Issue by puneeth171** [davidstutz/bootstrap-multiselect#913]
In multi select dropdown Select all option should be displayed at last after displaying all other options...
Ex : Select All
       Black
       Red
What i want is 
Ex : Black
       Red
       Select All

**Comment by davidstutz** [comment]
Check https://github.com/davidstutz/bootstrap-multiselect/blob/master/dist/js/bootstrap-multiselect.js#L997 and change `prepend` to `append` and it should wok.
