### ISSUE TITLE
Multiselect dropdown consecutively behaves different

### ISSUE THREAD

**Issue by maclax** [davidstutz/bootstrap-multiselect#914]
I'm trying to display multiselect dropdown on click of a button. An ajax call is call is send to the controller, to load the filter. On the first button click, it works perfectly.
On the second click, it shows up has a expanded scrollable control. On third click, the dropdown is not clickable. This behaviour is not consistent though.

**Comment by ItsNickBarry** [comment]
If you're calling multiselect in response to the ajax call, you should detach the plugin before calling it again:
```javascript
$('#element').multiselect('destroy');
```

**Comment by davidstutz** [comment]
@ItsNickBarry is right. Apart from that it's hard to help you without any code.
