### ISSUE TITLE
filter searches in option's value

### ISSUE THREAD

**Issue by smikheiev** [davidstutz/bootstrap-multiselect#92]
Search filter searches in option's value, not text. I propose replace this strings in search method:

var $option = $('option[text="' + value + '"]', this.$select);
var label = $option.attr('label') || $option.text();
if (label.substring(0, this.query.length).toLowerCase() != this.query.toLowerCase()) {
$(element).hide();
}
else {
$(element).show();
}

to this:
if (value.indexOf(this.query) === -1) {
$(element).hide();
}
else {
$(element).show();
}

**Comment by Gereltuya** [comment]
Has this been pushed yet? I am running into the same issue where my value is ID but my text is the value.

**Comment by tiesont** [comment]
@Gereltuya Can you create a fiddle or something that reproduces your problem? I don't have a ton of time for trouble-shooting, but I can take a look if you can give me something to start with. Otherwise, Bootstrap 4 compatibility is my priority at the moment.
