### ISSUE TITLE
W3C validation errors

### ISSUE THREAD

**Issue by DanielFrak** [davidstutz/bootstrap-multiselect#924]
The W3C Markup Validation service returns two errors for Bootstrap-Multiselect:

> The element label must not appear as a descendant of the a element.

> The element input must not appear as a descendant of the a element.

This is particularly problematic when validating a page with many dropdowns (and can actually choke the validator).

**Comment by davidstutz** [comment]
Has already been discussed here: #648, #480. This is partly due to Bootstrap 3, might change for Bootstrap 4, though.
