### ISSUE TITLE
Multiple select inputs issue

### ISSUE THREAD

**Issue by JayH77** [davidstutz/bootstrap-multiselect#926]
I have more than one SELECT on the same page, and I only want bootstrap-multiselect on one of these.

The following is taken from the 'further documentation' page:

`nonSelectedOptions.each(function() {
var input = $('input[value="' + $(this).val() + '"]');
input.prop('disabled', true);
});`

This works, as it disables all items in select A but it is also disabling items (that have the same index) in select B because this line doesn't specify the select.

Thanks

**Comment by blunket** [comment]
This is only because of your selector. $('input') will select all <input> elements on the page.
