### ISSUE TITLE
number of group!

### ISSUE THREAD

**Issue by nguyenthoai** [davidstutz/bootstrap-multiselect#928]
I can only create 2 groups in a <select> but i want to create 3 group? how?
 <select id="select_custom" multiple="multiple">
                            <optgroup label="Group 1">
                                <option value="1-1">Option 1.1</option>
                            </optgroup>
                            <optgroup label="Group 2">
                                <optgroup label="Group 2-1-1">
                                    <option value="2-1-1">Option 2.1.1</option>
                                </optgroup>
                                <option value="2-2">Option 2.2</option>
                                <option value="2-3">Option 2.3</option>
                            </optgroup>
                        </select>

**Comment by davidstutz** [comment]
So you want to have sub-groups like 2.1.1 or what is your question exactly?

**Comment by Ngthoai** [comment]
yes, i want to group option: 
     Option 1
        Option 1.1
           Option 1.1.1
     Option 2
        Option 2.1
           Option 2.1.1

**Comment by davidstutz** [comment]
That's not possible I guess - I never saw nested groups and it turns out that this is nor supported by HTML - see [here](https://stackoverflow.com/questions/1037732/nesting-optgroups-in-a-dropdownlist-select). So it does not make sense to integrate it into the multiselect plugin.
