### ISSUE TITLE
508 question

### ISSUE THREAD

**Issue by nikataus** [davidstutz/bootstrap-multiselect#935]
Hi,

I'm using this plugin and have more than 200 fields the user can select from. I've made some minor customizations to fit our requirements to make it fully 508 compliant. To provide keyboard support the user can tab through all items and it's working fine. However, I want to prevent 'traps' where the user needs to tab through all items to get to next element in the form. What is the best practice to avoid this trap? Create some scripting key combinations to be able to get out of the controls and move to next one? Please let me know if anyone has done something similar.
Thanks,

**Comment by jasonday** [comment]
I think making all options available by 'tab' is a mistake. Screenreader/keyboard users are going to utilize arrows (as is typical with these type of interactions). Additionally, users can also use list navigation and next form field navigation to navigate through all of the options.

**Comment by nikataus** [comment]
Yes, that's one option to do it. Actually tabs are implemented out of the box, I know I can customize and provide my own template for it. Thanks for your comments!
