### ISSUE TITLE
Any way not to change the background?

### ISSUE THREAD

**Issue by sk29110** [davidstutz/bootstrap-multiselect#938]
I was wondering if there is any way not to change the background color when clicking on the item( it goes blue by default when user select checkbox(checked) and go away if you uncheck).

I could easily overwrite to  background = none for the active class on li and color=black but our app has theme switch so hacking does not work well.

**Comment by davidstutz** [comment]
You can play around with the `selectedClass` option when you are able to apply custom styling. Changing the `selectedClass` option to not be `active` might remove the blue background if you are using Bootstrap as theme.
