### ISSUE TITLE
enableCollapsibleOptGroups: Picking all children in group will tick off other groups

### ISSUE THREAD

**Issue by Hyllesen** [davidstutz/bootstrap-multiselect#939]
I think I've stumbled across a bug when enableCollapsibleOptGroups is enabled.

How to replicate:

1. Select all children in a group manually one by one until all children are selected.
2. Groups above this group will get ticked at the group label somehow ?

I've also made a codepen where you can try to replicate the error:
https://codepen.io/Hylleh/pen/MvxgKK?editors=1010

![image](https://user-images.githubusercontent.com/9279498/29998672-a733b966-9031-11e7-8af0-a71ea3009c23.png)

**Comment by danhallin** [comment]
I had this problem in an older version, current master version does not seem to be afflicted.

**Comment by davidstutz** [comment]
Sounds like an old bug that I can't find right now. As @danhallin mentioned, try using the master branch and re-open if the bug persists.
