### ISSUE TITLE
How i use tree format dropdown in Multi-select plugin 

### ISSUE THREAD

**Issue by KS-Kannu** [davidstutz/bootstrap-multiselect#941]
How i use tree format dropdown in Multi-select plugin  like this

![treeview-style-multi-select-plugin-for-bootstrap-treeselect](https://user-images.githubusercontent.com/31687012/30099844-8b55fdc8-9304-11e7-8386-6f5053deb92d.jpg)

**Comment by Si7ius** [comment]
The site where you gave from this image has good solution:
http://www.jqueryscript.net/demo/Treeview-Style-Multi-Select-Plugin-For-Bootstrap-Treeselect/

**Comment by davidstutz** [comment]
That's currently not possible, also because HTML does not allow nesting optgroups, see #928.
