### ISSUE TITLE
dropup option using dynamically

### ISSUE THREAD

**Issue by ssjogus** [davidstutz/bootstrap-multiselect#946]
hello,

thanks for wonderful plugin and the new feature of 'dropup'..

however what i need is, depending on the location of the dropdown field, it should dropdown or dropup dynamically. Like if I am not opening dropdown, and the it is going out of window, it should automatically have open 'up' else 'down'.

any ideas how we can do that?

thanks in advance..

**Comment by davidstutz** [comment]
Well, you can dynamically change multiselect's options. But you would need to write a piece of code that detects where the select is (i.e. whether to drop up or drop down; which needs to be updated on scrolling, obviously) and then updates the plugin. Have a look at the `setOptions` method in the documentation.
