### ISSUE TITLE
Remove all options

### ISSUE THREAD

**Issue by PeterPetersen** [davidstutz/bootstrap-multiselect#948]
Hi, how can i remove all options?

**Comment by PeterPetersen** [comment]
Client-side :)

**Comment by CZechBoY** [comment]
Look on `setOptions` method example in doc. http://davidstutz.github.io/bootstrap-multiselect/#methods

**Comment by PeterPetersen** [comment]
Hello, with "options" i meant the items in the select, not the config-options, sorry. in your examples you self wrote "select all options" etc.

**Comment by davidstutz** [comment]
Just remove the options using jQuery and the rebuild the mutliselect using the `rebuild` method.

**Comment by qwe900** [comment]
$('#multiselectname').multiselect('dataprovider', []);
 $('#selecteddevicesvibra').multiselect('rebuild');
