### ISSUE TITLE
how can i add a class or id to every dynamically created checkbox in the dropdown using multiselect ?

### ISSUE THREAD

**Issue by mike1011** [davidstutz/bootstrap-multiselect#949]
i want to validate every selected option which is a checkbox created by multiselect. Hence i need to assign a class or id to every dropdown in the multiselect.
i tried buttonClass option, but this one adds class to the hidden select box rather than the options/dropdown itself.

i am using jquery.validate to add custom method to validate selected options.

**Comment by davidstutz** [comment]
You can always use the `optionClass` option to set classes to the checkboxes to help validation. Not sure if that works with jquery.validate.
