### ISSUE TITLE
Search results is very slow  while list size is 9000  

### ISSUE THREAD

**Issue by srikanthadepu557** [davidstutz/bootstrap-multiselect#956]
Search results while filtering are loading slow for the first time in all browsers ..
there are 9000 values in list now , below is my code snippet with multi select plugin
Could you please suggest me a way to get faster results for my search operation in bootstrap multi select .

$('#pid').multiselect({
enableFiltering: true,
enableFullValueFiltering:true,
enableCaseInsensitiveFiltering: true,
maxHeight: 200,
buttonWidth: '225px',
buttonText: function(options, select) {
if (options.length === 0) {
return '-Select-';
} else {
var labels = [];
options.each(function() {
if ($(this).attr('label') !== undefined) {
labels.push($(this).attr('label'));
}
else {
labels.push($(this).html());
}
});
return labels.join(',') + '';
}
}
});

**Comment by LiuChina** [comment]
Now I have encountered this problem，Have you solved this kind of thing?

**Comment by srikanthadepu557** [comment]
No .. I am exploring multiple options but nothing working out as of now .
We are not getting enough support from this community on this plug-in.
Without this plug-in - Autocomplete with multiselect may be option but it's bit difficult to implement .

**Comment by davidstutz** [comment]
This is a known problem, as also described here: #316 #334 #672 #868 #918. Will close this one and leave #918 open.

**Comment by shalludogra** [comment]
Any solution for performance issue ?
