### ISSUE TITLE
Display: none of the <SELECT>

### ISSUE THREAD

**Issue by dsujoy** [davidstutz/bootstrap-multiselect#958]
I have a lot of multiselect dropdows, and someone of the has dependency, so, if a specific option of one dropdown is choosed, it should hide or show the next dropdown (not only a option)

Actually i use 
$('#mydropdown').multiselect('disable');
and
$("#mydropdown").multiselect('enable')

but I can't find a method to hide/show the <select>. Is there a method for that action? It should be useful.

best regards.

**Comment by davidstutz** [comment]
No there is a method. But you can just try to hide the full container - you can use the `buttonContainer` option.

**Comment by siyuren** [comment]
How to use the buttonContainer to hide it? Can you give an example? Thanks.
