### ISSUE TITLE
the label displays the wrong selected items

### ISSUE THREAD

**Issue by hectorcaban** [davidstutz/bootstrap-multiselect#959]
![image](https://user-images.githubusercontent.com/9602129/32393179-ea80cb66-c0ae-11e7-8214-5a3f720a439a.png)

if all the items are selected and a filter is applied and I deselect an item it gives the wrong number items selected. as shown above

**Comment by davidstutz** [comment]
Can't reproduce the problem with the examples in the documentation. The button always shows ALL selected options - even those that are not visible. So if you have 10 options in total, select all, then filter for one option, deselect this, than the button will show 9 selected options ...
If that is still a bug, feel free to provide an example, with code please.
