### ISSUE TITLE
How to Filter the items when the number of items more than 3000 or 4000

### ISSUE THREAD

**Issue by LiuChina** [davidstutz/bootstrap-multiselect#962]
Now,I use this Plug-ins.If the number of items is less than 500  or 800，When using the filter function, the speed will be fast, does not affect the use of results. But when the items is more and more ,such as 3000 or 4000.I see the source code, will be traversal of the 3000 options cycle, the speed will be very slow, affecting the use of results. Cause the page will be stuck for a long time.On the Internet, I did not find how to solve this kind of thing. Is there any solution to this problem?Do I must to modify the source code?First use GitHub,and I am in China,Hoping to get your help.

**Comment by davidstutz** [comment]
Yes the speed issues are known, also see here: #956 #316 #334 #672 #868 #918. Will close this one and leave the others the others open.
